#!/usr/bin/env python3
"""Finalize retained read-only JSON evidence; no remote contact or mutation."""
import argparse,datetime,hashlib,json,pathlib
p=argparse.ArgumentParser(description=__doc__);p.parse_args()
T=pathlib.Path(__file__).resolve().parent
r=json.loads((T/'activation-readback-02.json').read_text());b=json.loads((T/'activation-content-before.json').read_text());session=json.loads((T/'SESSION.json').read_text())
protected=['sessions','messages','files','runs','events','quarantined_workspaces','h003_image_jobs','h005_image_ownership','gateway_lanes','frontier_requests']
checks={t:r['data'][t]==b['data'][t] for t in protected};assert all(checks.values())
for k in ['regular_files_preserved','dispatch_preserved','credentials_metadata_preserved','search_preserved','admin_preserved','unit_exact_path_replacement','status_exact_path_replacement','old_release_preserved','post_storage_guard_pass']:assert r[k],k
assert all(x.get('http_status')==200 for x in r['routes'].values())
assert r['image_id']=='9ef88598cf54a03aa259c5aa2d2878b34b7473cfcec7c8c07cee6ba462c39f1c'
assert 'NRestarts=0' in r['unit_properties']
assert r['frontier_config']=={'model':'glm-5.3-flash','contextWindow':1048576,'maxOutputTokens':65536,'tokenizerRevision':'eb9eb208eb0d988989d07a6a12d0fdeb5f52574a','qualified':True,'templateRevision':'eb9eb208eb0d988989d07a6a12d0fdeb5f52574a'}
body=r['routes']['/api/status/v1/system']['body'];node=next(n for n in body['nodes'] if n['node_id']=='ai-vm');services={x['service_id']:x for x in node['services']}
assert services['glm-5.3-flash']['display_name']=='Frontier GLM-5.3-Flash'
assert services['glm-5.3-flash']['configured_context_tokens']==1048576
assert services['glm-5.3-flash']['max_output_tokens']==65536
assert services['qwen-gpu0']['configured_context_tokens']==services['qwen-gpu1']['configured_context_tokens']==480000
out={'status':'PASS_ACTIVATED_HEALTH_STATUS_AND_CONTENT','finalized_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'session':session,'activation_times':(T/'activation.log').read_text().splitlines(),'observation_utc':r['observed_utc'],'source':session['built_source'],'image':'sha256:'+r['image_id'],'units':r['units'],'process_cwd':r['process_cwd'],'process_exe':r['process_exe'],'unit_properties':r['unit_properties'],'sha256':r['sha256'],'frontier_config':r['frontier_config'],'http':{k:{x:y for x,y in v.items() if x!='body'} for k,v in r['routes'].items()},'health':r['routes']['/api/health']['body'],'observed_services':[{k:v for k,v in services[n].items() if k in ['service_id','display_name','model_alias','deployment_id','availability','ready','admitting','configured_context_tokens','max_output_tokens','observed_at','freshness','age_ms','activity','queue_depth','active_requests']} for n in ['qwen-gpu0','qwen-gpu1','glm-5.3-flash','image']],'userdata':{'protected_content_comparisons':checks,'tables_before':b['data'],'tables_after':r['data'],'files_before':b['files'],'files_after':r['files'],'regular_files_preserved':True,'dispatch_before':b['dispatch'],'dispatch_after':r['dispatch'],'dispatch_preserved':True,'operational_transition':r['operational_before_after'],'owner_lock':r['owner_lock'],'no_database_restore':True,'no_manual_quarantine_clear':True},'preservation':{k:r[k] for k in ['credentials_metadata_preserved','search_preserved','admin_preserved','unit_exact_path_replacement','status_exact_path_replacement','old_release_preserved','post_storage_guard_pass','free_bytes']},'evidence_limit':'Production pool/context and protected runtime continuity accepted from supplied root/Worker1 records; no direct ai-vm probe. Current readiness separately observed via normal Sova status endpoint.','roles':'Qwen ordinary coding/coordinator; Flash research, documents and hard reasoning; accepted source preserved. MiMo disabled/unwired.','image_configuration':'Registry differs from predecessor only by Flash display_name; image service configuration retained.','warnings':['Recorder01 attempted to inspect owner.sqlite while normal app BEGIN EXCLUSIVE lock held; zero-byte lock is not a user/ownership ledger. No restart or bypass.','Recorder02 compared Python tuple states with JSON lists and falsely marked unchanged sessions/runs/image-jobs as differing. This finalizer compares normalized retained JSON, including hashes and all rows; originals retained.','Image lane changed quarantined to idle through normal broker readiness AND idle reconciliation; historical workspace quarantine unchanged.'], 'limits':r['limits'],'push':False,'rollback_used':False}
(T/'RESULT.json').write_text(json.dumps(out,indent=2)+'\n')
print(json.dumps({'status':out['status'],'finalized_utc':out['finalized_utc'],'content_preserved':all(checks.values()),'app_pid':r['units']['ai-harness.service']['MainPID']}))
