/** Actual exited normal application adoption. No serializable brand/enable flag. */
import {privateFile} from './checkpoint.js';import {sha256,stableJson,reviewSnapshot} from './projection.js';import {observeApplicationIdentity} from './process-runner.js';import {processIdentity,verifyNativeProducer,baseline} from '../ordinary-proof.mjs';
const tickets=new WeakMap<object,{qualificationConfigSha256:string;normalConfigSha256:string;normalConfigValueSha256:string;receiptSha256:string}>();export interface NormalRestartTicket{receiptSha256:string}
export const isNormalRestartTicket=(v:unknown):v is NormalRestartTicket=>!!v&&typeof v==='object'&&tickets.has(v);
export function assertNormalRestartQualification(value:unknown,config:any){const b=value&&typeof value==='object'?tickets.get(value):undefined;if(!b||b.qualificationConfigSha256!==sha256(stableJson(config))||(value as NormalRestartTicket).receiptSha256!==b.receiptSha256)throw Error('normal_restart_ticket_exact_qualification_config_required');}
export function assertNormalRestartConfig(value:unknown,config:any,bytes:Buffer){const b=value&&typeof value==='object'?tickets.get(value):undefined;if(!b||b.normalConfigSha256!==sha256(bytes)||b.normalConfigValueSha256!==sha256(stableJson(config)))throw Error('normal_restart_ticket_exact_worker_config_required');assertNormalRestartQualification(value,config.qualificationConfig);}
export async function qualifyNormalRestart(input:any,config:any):Promise<NormalRestartTicket>{
 config=reviewSnapshot(config);input=reviewSnapshot(input);const configBytes=await privateFile(input.configPath);if(stableJson(JSON.parse(configBytes.toString('utf8')))!==stableJson(config))throw Error('actual_normal_config_value_bytes_mismatch');if(process.platform!=='linux')throw Error('actual_linux_normal_restart_required');const bytes=await privateFile(input.path);if(sha256(bytes)!==input.sha256)throw Error('retained_normal_restart_changed');const r=JSON.parse(bytes.toString('utf8')),expected={...config.review.normalProductProof,sessionId:config.sessionId,receiptSources:config.review.receiptSources};if(r.source!=='owned-normal-process-adoption'||r.configSha256!==sha256(configBytes)||r.qualificationSha256!==config.qualificationConfig.qualificationSha256||r.candidateCommit!==config.review.candidateCommit||r.windowId!==config.review.authorization.windowId||r.baseline?.sessionId!==config.sessionId||r.oldReady?.dataDir!==config.dataDir||r.oldClose?.sessionId!==config.sessionId)throw Error('exact_prior_normal_source_packet_required');baseline(r.baseline,expected);const old=processIdentity(JSON.parse(r.oldReady.kernelUtf8));if(sha256(r.oldReady.kernelUtf8)!==r.oldReady.kernelSha256||r.oldExit.code!==0||r.oldExit.signal!==null||stableJson(r.oldExit.process)!==stableJson(old)||r.oldReady.configSha256!==r.configSha256||r.oldReady.workerSha256!==r.workerSha256||!Array.isArray(r.oldClose.nativeProducers)||!r.oldClose.nativeProducers.length)throw Error('actual_old_application_close_exit_source_required');for(const p of r.oldClose.nativeProducers)verifyNativeProducer(p,expected);const g=JSON.parse(r.oldClose.gatewayObservationUtf8);if(sha256(r.oldClose.gatewayObservationUtf8)!==r.oldClose.gatewayObservationSha256||g.outstanding.length||g.sessionId!==config.sessionId||g.records.some((b:string)=>JSON.parse(b).state!=='settled'))throw Error('actual_old_gateway_settlement_required');const actual=await observeApplicationIdentity(process.pid),prior=await observeApplicationIdentity(old.pid).catch(()=>undefined);if(actual.bootId!==old.bootId||actual.pid===old.pid&&actual.startTicks===old.startTicks||prior&&prior.bootId===old.bootId&&prior.startTicks===old.startTicks)throw Error('actual_old_process_absence_and_fresh_kernel_identity_required');const ticket=Object.freeze({receiptSha256:input.sha256});tickets.set(ticket,{qualificationConfigSha256:sha256(stableJson(config.qualificationConfig)),normalConfigSha256:sha256(configBytes),normalConfigValueSha256:sha256(stableJson(config)),receiptSha256:input.sha256});return ticket;
}
