/** Actual normal main.start composition. Never imports/calls temporary bootstrap. */
import {composeCodexProductObservers} from '../../../server/src/codex-product-observation.js';
import {validateCarrierBinding} from './carrier-admission.js';
import {loadQualificationTaskAdmission} from '../../../server/src/qualification-task-admission.js';
import {start} from '../../../server/src/main.js';
import {loadCodexOrdinaryEntry} from '../../../server/src/codex-ordinary-entry.js';
import {createProductionQwenVerifier,loadQwenReceipt} from '../../../server/src/codex-production.js';
import {readProtectedCredential} from '../../../server/src/protected-credential.js';
import * as traceApi from '../../../server/src/codex-receipts.js';
import {parsePostSamplingTrace,parseAutoCallTrace,nativeTimestampNs,nativeCompactionStart,verifyNativeStartedAtTraceJoin,verifyRetainedTrace,verifyTraceSchemaMode,traceSchemaForMode,type NativeTraceMode} from '../native-trace-evidence.mjs';
import {assertH044ProducerSourceActivation} from './policy-selection.js';
import {getCodexReceiptUtf8} from '../../../server/src/codex-receipts.js';
import {translateResponses} from '../../../server/src/codex-responses.js';
import type {CodexHostQualification} from '../../../server/src/codex-host.js';
import type {GatewayOptions} from '../../../server/src/gateway.js';
import {NativeObserver} from './native-observer.js';
import {NativeCountObserver} from './count-observer.js';
import {NativeCollector} from './collector.js';
import {privateFile,durableFile} from './checkpoint.js';
import {sha256,stableJson,reviewSnapshot,identifier} from './projection.js';
import {qualifyEntry,isQualifiedEntry,type EntryQualification} from './qualification.js';
import {reviewedAuthorization} from '../authorization.mjs';
import {lstat,readFile} from 'node:fs/promises';import {join,dirname} from 'node:path';
import {assertNormalRestartConfig} from './normal-restart-ticket.js';
import {collectOrdinaryAutomatic} from './automatic.js';
import {automaticMetadata,automaticFrames} from '../automatic-evidence.mjs';
import {readFileSync,readSync,realpathSync,lstatSync,openSync,fstatSync,closeSync,constants} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {bounded} from './process-runner.js';
/** Root selection only. Closed source review permits the V2 observer; actual
 * regular formatter/config/causal qualification remains an executable gate. */
export function normalProductTraceMode(review:any):NativeTraceMode{
 const mode=review.nativeTrace===undefined?'off':review.nativeTrace?.mode;
 traceSchemaForMode(mode);return mode;
}
export function assertNormalProductTraceReady(mode:NativeTraceMode){
 traceSchemaForMode(mode);
 if(mode==='post-sampling-token-usage-v2')assertH044ProducerSourceActivation('H044');
 if(mode!=='off'&&(typeof traceApi.getCodexRetainedTraceEvidence!=='function'||typeof traceApi.getCodexTraceEvents!=='function'||typeof traceApi.getCodexTraceUtf8!=='function'||typeof traceApi.isVerifiedCodexTraceReceipt!=='function'))throw Error('actual_reviewed_A_trace_producer_API_unavailable');
}
const traceOriginals=new WeakMap<object,traceApi.CodexNativeTraceReceipt>();
/** Source projection only: authentic transport brands and the independent full
 * carrier verifier remain mandatory. No formatter/native acceptance is granted.
 * Preserve all original event bytes; numeric and AUTO NEW streams stay separate. */
export function projectNormalProductTrace(r:traceApi.CodexNativeTraceReceipt,selectedMode:Exclude<NativeTraceMode,'off'>,producer:any,expected:any){
 if(!traceApi.isVerifiedCodexTraceReceipt(r)||r.mode!==selectedMode)throw Error('actual_owned_current_A_trace_receipt_required');
 const retained=traceApi.getCodexRetainedTraceEvidence(r,selectedMode),raw=traceApi.getCodexTraceUtf8(r),events=traceApi.getCodexTraceEvents(r);
 if(!raw||!events||retained.schema!==traceSchemaForMode(selectedMode)||retained.selectedMode!==selectedMode||!Array.isArray(retained.lines)||!Array.isArray(retained.autoCalls))throw Error('actual_discriminated_A_retained_trace_projection_required');
 const packet={...producer,selectedMode,traceReceiptUtf8:raw,traceReceiptSha256:sha256(raw),events:events.map(e=>{
  const lineUtf8=e.bytes.toString('utf8');if(!Buffer.from(lineUtf8).equals(e.bytes))throw Error('original_trace_invalid_utf8');
  const parsed=e.kind==='autoCompactNew'?parseAutoCallTrace(lineUtf8):parsePostSamplingTrace(lineUtf8);
  if(parsed.lineSha256!==e.lineSha256)throw Error('original_trace_projection_digest');
  return {lineUtf8,lineSha256:e.lineSha256,stderrSequence:e.stderrSequence,kind:e.kind};
 })};
 const verified=verifyRetainedTrace(packet,{...expected,mode:selectedMode,traceReceiptSha256:packet.traceReceiptSha256,launchReceiptSha256:packet.launchReceiptSha256,settlementReceiptSha256:packet.settlementReceiptSha256});
 const original=(e:any)=>({lineUtf8:e.lineUtf8,stderrSequence:e.stderrSequence,lineSha256:e.lineSha256});
 if(stableJson(retained.lines)!==stableJson(verified.lines.map(original))||stableJson(retained.autoCalls)!==stableJson(verified.autoCalls.map(original))||stableJson(retained.producer)!==stableJson(verified.producer)||retained.receiptSha256!==packet.traceReceiptSha256)throw Error('actual_A_retained_projection_original_carrier_mismatch');
 const result=reviewSnapshot({...packet,retainedTrace:retained});traceOriginals.set(result,r);return result;
}
export interface AutomaticConfigOriginals {configUtf8:string;catalogUtf8:string;projectionUtf8:string;}
/** A root-reviewed effective projection is an ORIGINAL nonsecret readback, not
 * a boolean readiness flag. Its exact bytes are independently frozen by root;
 * catalog values and actual receipt sources must agree. SOURCE_VALID grants no
 * native provenance to a fixture/readback. Only the qualified producer uses it. */
export function projectAutomaticConfig(originals:AutomaticConfigOriginals,spec:any,packet:any){
 const receipt=traceOriginals.get(packet);if(!receipt||!traceApi.isVerifiedCodexTraceReceipt(receipt))throw Error('actual_original_trace_brand_required');
 const launch=JSON.parse(packet.launchReceiptUtf8),projection=JSON.parse(originals.projectionUtf8),catalog=JSON.parse(originals.catalogUtf8);
 for(const [key,bytes] of [['config',originals.configUtf8],['catalog',originals.catalogUtf8],['projection',originals.projectionUtf8]] as const)if(typeof bytes!=='string'||!bytes||sha256(bytes)!==spec?.[key+'Sha256'])throw Error('actual_frozen_protected_config_original_changed');
 if(spec.configSha256!==launch.sources['codex/config.toml']||spec.catalogSha256!==launch.sources['codex/models.json']||spec.sourceRevision!=='064c6b8c737f5b41d171fdda80bd9ef10ad06eb3'||projection.version!=='0.158.0'||projection.sourceRevision!==spec.sourceRevision||projection.sessionId!==receipt.sessionId||projection.runId!==receipt.runId||projection.launchNonce!==receipt.nonce||projection.configSha256!==spec.configSha256||projection.catalogSha256!==spec.catalogSha256)throw Error('actual_protected_config_run_and_source_binding_required');
 // Frozen TOML original, not a regex-derived effective config. The reviewed
 // native projection resolves config/requirements/thread overrides/defaults.
 // Duplicate/unknown native projection fields cannot smuggle alternate causes.
 const c=projection.resolvedConfig,keys=['contextWindow','autoCompactTokenLimit','maxOutputTokens','effectiveScope','tokenBudgetEnabled','fallbackBufferTokens','postTurnPercent'];
 if(!c||Object.keys(c).sort().join()!==keys.sort().join()||c.contextWindow!==480000||c.autoCompactTokenLimit!==400000||c.maxOutputTokens!==65536||c.effectiveScope!=='total'||c.tokenBudgetEnabled!==false||c.fallbackBufferTokens!==0||c.postTurnPercent!==0||sha256(stableJson(c))!==spec.resolvedConfigSha256)throw Error('actual_exact_400k_effective_config_and_exclusions_required');
 const models=catalog.models?.filter((m:any)=>m.slug==='qwen3.8-27b');
 if(models?.length!==1||models[0].context_window!==c.contextWindow||models[0].max_context_window!==480000||models[0].auto_compact_token_limit!==c.autoCompactTokenLimit||models[0].effective_context_window_percent!==100)throw Error('original_catalog_effective_config_mismatch');
 // Check every explicit relevant scalar in the ORIGINAL mounted TOML. Native
 // source rules supply omitted defaults, never override an explicit setting.
 const wanted=new Set(['model','model_provider','model_catalog_json','model_context_window','model_auto_compact_token_limit','model_max_output_tokens','features.token_budget']),settings:Record<string,unknown>={};let section='';
 for(const line of originals.configUtf8.split('\n')){const table=/^\s*\[([A-Za-z0-9_.]+)\]\s*(?:#.*)?$/.exec(line);if(table){section=table[1];continue;}const scalar=/^\s*([A-Za-z0-9_]+)\s*=\s*(.*?)\s*(?:#.*)?$/.exec(line);if(!scalar)continue;const key=(section?section+'.':'')+scalar[1];if(!wanted.has(key))continue;if(key in settings)throw Error('duplicate_relevant_original_config_key');const literal=scalar[2];if(/^(true|false)$/.test(literal))settings[key]=literal==='true';else if(/^(0|[1-9]\d*)$/.test(literal))settings[key]=Number(literal);else if(/^"[^"\\]*"$/.test(literal))settings[key]=JSON.parse(literal);else throw Error('unsupported_explicit_original_config_scalar');}
 if(settings.model!=='qwen3.8-27b'||settings.model_provider!=='sova'||settings.model_catalog_json!=='/opt/sova/codex/models.json')throw Error('actual_original_config_model_provider_catalog_required');
 for(const [key,value] of [['model_context_window',480000],['model_auto_compact_token_limit',400000],['model_max_output_tokens',65536],['features.token_budget',false]] as const)if(key in settings&&settings[key]!==value)throw Error('explicit_original_config_effective_projection_conflict');
 // Defaults/omitted fields require root's reviewed native source projection,
 // covering each alternate cause. Bind exact original source files AND spans;
 // a descriptive source/name/hash without original bytes is insufficient.
 const rules=projection.sourceRules;
 if(!Array.isArray(rules)||rules.length!==4||stableJson(rules.map((x:any)=>x.key).sort())!==stableJson(['effectiveScope','tokenBudgetEnabled','fallbackBufferTokens','postTurnPercent'].sort())||!Array.isArray(spec.sourceRules)||rules.length!==spec.sourceRules.length)throw Error('original_reviewed_native_config_source_rules_required');
 for(const rule of rules){const reviewed=spec.sourceRules.find((r:any)=>r.key===rule.key);if(!reviewed||reviewed.value!==c[rule.key]||rule.value!==c[rule.key]||typeof rule.originalUtf8!=='string'||sha256(rule.originalUtf8)!==reviewed.originalSha256||!Number.isSafeInteger(rule.startByte)||!Number.isSafeInteger(rule.endByte)||rule.startByte<0||rule.endByte<=rule.startByte||rule.endByte>Buffer.byteLength(rule.originalUtf8)||rule.startByte!==reviewed.startByte||rule.endByte!==reviewed.endByte||Buffer.from(rule.originalUtf8).subarray(rule.startByte,rule.endByte).toString('utf8')!==reviewed.spanUtf8||sha256(reviewed.spanUtf8)!==reviewed.spanSha256||rule.sourceRevision!==spec.sourceRevision)throw Error('original_reviewed_native_config_source_span_changed');}
 return reviewSnapshot({status:'SOURCE_VALID',nativeAcceptance:'NOT_TESTED',resolvedConfig:c,resolvedConfigSha256:spec.resolvedConfigSha256,configSha256:spec.configSha256,catalogSha256:spec.catalogSha256,projectionSha256:spec.projectionSha256});
}
/** Original regular formatter record and stdout item spans are independent
 * carriers. No host arrival ordering; each native timestamp is preserved.
 * The packet must contain a completed regular turn and no AUTO call/compaction.
 * Its last numeric sample demonstrates the selected400k/480k formatter fields. */
export function verifyRegularSamplingExclusion(packet:any,frames:any[],expected:any){
 const receipt=traceOriginals.get(packet);if(!receipt||receipt.mode!==expected.mode||receipt.sessionId!==expected.sessionId||receipt.runId!==expected.runId||receipt.nonce!==expected.launchNonce)throw Error('actual_regular_trace_brand_mode_run_required');
 const trace=verifyRetainedTrace(packet,{sessionId:expected.sessionId,mode:expected.mode,receiptSources:expected.receiptSources,launchReceiptSha256:packet.launchReceiptSha256,settlementReceiptSha256:packet.settlementReceiptSha256,traceReceiptSha256:packet.traceReceiptSha256});
 if(trace.autoCalls.length||!trace.lines.length||sha256(stableJson(frames))!==expected.framesSha256||!frames.length)throw Error('actual_regular_original_item_span_exclusion_required');
 let seq=-1;for(const f of frames){if(!Number.isSafeInteger(f.sequence)||f.sequence<0||f.sequence<=seq||typeof f.bytesUtf8!=='string'||sha256(f.bytesUtf8)!==f.sha256||stableJson(JSON.parse(f.bytesUtf8))!==stableJson(f.value)||!['to-native','from-native'].includes(f.direction))throw Error('original_regular_native_frame_changed');seq=f.sequence;}
 const calls=frames.filter(f=>f.direction==='to-native'&&f.value.method==='turn/start'),acks=frames.filter(f=>f.direction==='from-native'&&f.value.id===calls[0]?.value.id),starts=frames.filter(f=>f.direction==='from-native'&&f.value.method==='turn/started'),ends=frames.filter(f=>f.direction==='from-native'&&f.value.method==='turn/completed');
 if(calls.length!==1||calls[0].value.params?.threadId!==expected.nativeThreadId||acks.length!==1||acks[0].value.error||acks[0].value.result?.turn?.id!==expected.nativeTurnId||starts.length!==1||starts[0].value.params?.threadId!==expected.nativeThreadId||starts[0].value.params.turn?.id!==expected.nativeTurnId||ends.length!==1||ends[0].value.params?.threadId!==expected.nativeThreadId||ends[0].value.params.turn?.id!==expected.nativeTurnId||ends[0].value.params.turn.status!=='completed'||calls[0].sequence>=starts[0].sequence||starts[0].sequence>=ends[0].sequence||acks[0].sequence<=calls[0].sequence||acks[0].sequence>=ends[0].sequence||frames.some(f=>['thread/compact/start','thread/rollback','thread/fork','thread/unarchive'].includes(f.value.method)||f.value.params?.item?.type==='contextCompaction'))throw Error('actual_regular_completed_operation_causal_exclusion_required');
 const itemStarts=frames.filter(f=>f.direction==='from-native'&&f.value.method==='item/started'),itemEnds=frames.filter(f=>f.direction==='from-native'&&f.value.method==='item/completed');
 if(!itemStarts.length||itemStarts.length!==itemEnds.length||new Set(itemStarts.map(f=>f.value.params?.item?.id)).size!==itemStarts.length||itemStarts.some(f=>{const p=f.value.params,matched=itemEnds.filter(e=>e.value.params?.item?.id===p?.item?.id);return !p?.item?.id||p.threadId!==expected.nativeThreadId||p.turnId!==expected.nativeTurnId||f.sequence<=starts[0].sequence||matched.length!==1||matched[0].sequence<=f.sequence||matched[0].sequence>=ends[0].sequence||matched[0].value.params.threadId!==expected.nativeThreadId||matched[0].value.params.turnId!==expected.nativeTurnId||matched[0].value.params.item.type!==p.item.type;}))throw Error('original_regular_item_span_pairing_required');
 // Task ancestry+same settled producer and complete RPC span exclude alternate
 // item causes. No invented Turn.startedAt/completedAt or pipe arrival clocks.
 let time=-1n,sequence=0;const samples=trace.lines.map((line:any)=>{const p=parsePostSamplingTrace(line.lineUtf8),spans=[...(p.raw.spans??[]),...(p.raw.span?[p.raw.span]:[])],tasks=spans.filter(s=>s.name==='turn'),at=nativeTimestampNs(p.raw.timestamp);if(p.nativeTurnId!==expected.nativeTurnId||!tasks.length||tasks.some(s=>s['thread.id']!==expected.nativeThreadId||s['turn.id']!==expected.nativeTurnId)||spans.some(s=>s.name==='run_auto_compact')||at<time||!Number.isSafeInteger(line.stderrSequence)||line.stderrSequence<=sequence||p.scope!=='Total'||p.scopeTokens!==p.totalUsageTokens||p.autoLimit!==400000||p.fullLimit!==480000||p.raw.fields.full_context_window_limit_reached||p.raw.fields.token_limit_reached!==(p.totalUsageTokens>=400000))throw Error('actual_regular_formatter_and_native_causal_span_required');time=at;sequence=line.stderrSequence;return p;});
 const latest=samples.at(-1)!;if(latest.totalUsageTokens>=400000)throw Error('regular_baseline_already_at_threshold_no_invented_AUTO_omission');
 return reviewSnapshot({status:'SOURCE_VALID',nativeAcceptance:'NOT_TESTED',lineSha256:latest.lineSha256,framesSha256:expected.framesSha256,traceReceiptSha256:packet.traceReceiptSha256,nativeThreadId:expected.nativeThreadId,nativeTurnId:expected.nativeTurnId,totalUsageTokens:latest.totalUsageTokens,autoCalls:[],excluded:['manual','pre_turn','post_turn','token_budget','hard_cap'],generationAllowed:false});
}
export function assertFiniteAutomaticTurn(input:any,sessionId:string,threadId:string,approvedText:string,dispatched:number){
 if(dispatched!==0||input.sessionId!==sessionId||input.threadId!==threadId||input.method!=='turn/start'||stableJson(input.params?.input)!==stableJson([{type:'text',text:approvedText,text_elements:[]}]))throw Error('single_exact_approved_automatic_turn_required');
}
function protectedOriginal(path:string,digest:string){
 if(typeof path!=='string'||realpathSync(path)!==path)throw Error('canonical_protected_auto_original_required');const parent=lstatSync(dirname(path));if(!parent.isDirectory()||parent.uid!==process.getuid?.()||(parent.mode&0o077))throw Error('private_auto_original_parent_required');
 const fd=openSync(path,constants.O_RDONLY|constants.O_NOFOLLOW);try{const before=fstatSync(fd);if(!before.isFile()||before.uid!==process.getuid?.()||before.nlink!==1||(before.mode&0o777)!==0o600||before.size<1||before.size>16*1024*1024)throw Error('protected_auto_original_file_required');const bytes=Buffer.alloc(before.size),again=Buffer.alloc(before.size),n=readSync(fd,bytes,0,bytes.length,0),m=readSync(fd,again,0,again.length,0),after=fstatSync(fd);if(n!==before.size||m!==before.size||!bytes.equals(again)||before.ino!==after.ino||before.size!==after.size||before.mtimeMs!==after.mtimeMs||sha256(bytes)!==digest||!Buffer.from(bytes.toString('utf8')).equals(bytes))throw Error('protected_auto_original_changed');return bytes.toString('utf8');}finally{closeSync(fd);}
}
export async function kernelProcessReceipt(pid=process.pid){if(process.platform!=='linux')throw Error('native_normal_process_requires_linux_kernel');const procStatUtf8=await readFile(`/proc/${pid}/stat`,'utf8'),bootIdUtf8=await readFile('/proc/sys/kernel/random/boot_id','utf8'),fields=procStatUtf8.slice(procStatUtf8.lastIndexOf(') ')+2).trim().split(/\s+/);return {source:'linux-proc-process-observation',pid,startTicks:fields[19],bootId:bootIdUtf8.trim(),procStatUtf8,bootIdUtf8};}
export class NormalProductProducer {
 readonly observer:NativeObserver;readonly counts:NativeCountObserver;
 private automaticReady?:any;private automaticCaptured=false;private automaticDispatched=0;
 private originalReceiptDirectories=new Map<string,string>();
 private reviewedRegularFrames?:any[];
 /** Explicit closed original import only. This does not create an observer,
  * invent runtime provenance or qualify native startup. The protected source
  * review and already genuine EntryQualification precede every original read. */
 async adoptReviewedRegularOriginals(){
  const spec=this.config.review.automaticPreparation,regular=spec?.regular;if(!regular?.originalDirectory)return;
  if(!isQualifiedEntry(this.qualification)||this.traceCaptures.size||this.currentProcess||!this.application||this.config.review.authorization.task!=='H044')throw Error('qualified_fresh_normal_original_adoption_required');
  const dir=regular.originalDirectory,uid=process.getuid!(),binding=regular.binding;
  if(!binding||binding.uid!==uid||binding.sessionId!==this.config.sessionId||binding.runId!==regular.runId||binding.nonce!==regular.launchNonce||binding.nativeTraceMode!==regular.mode||stableJson(binding.sources)!==stableJson(this.qualification.receiptSources))throw Error('root_exact_original_regular_binding_required');
  for(const [name,digest] of [['launch',regular.launchReceiptSha256],['settlement',regular.settlementReceiptSha256],['trace',regular.traceReceiptSha256]])protectedOriginal(join(dir,name+'.json'),digest);
  const read=(name:'launch'|'settlement'|'trace')=>traceApi.waitCodexReceiptFile(dir,uid,name,100,()=>true),launch=traceApi.validateCodexLaunchReceipt(await read('launch'),binding,regular.observedProducer,regular.validatedAtMs),settlement=traceApi.validateCodexSettlementReceipt(await read('settlement'),binding,launch,regular.settledValidatedAtMs),trace=traceApi.validateCodexTraceReceipt(await read('trace'),binding,launch,settlement),producer={launchReceiptUtf8:this.raw(launch),launchReceiptSha256:regular.launchReceiptSha256,settlementReceiptUtf8:this.raw(settlement),settlementReceiptSha256:regular.settlementReceiptSha256};
  const packet=projectNormalProductTrace(trace,regular.mode,producer,{sessionId:this.config.sessionId,receiptSources:this.qualification.receiptSources}),frames=JSON.parse(protectedOriginal(regular.framesPath,regular.framesSha256));verifyRegularSamplingExclusion(packet,frames,regular);
  this.originalReceiptDirectories.set(trace.nonce,dir);this.assertTraceOriginals(packet);this.traceCaptures.set(trace.nonce,packet);this.reviewedRegularFrames=reviewSnapshot(frames);
  const baseline=JSON.parse(protectedOriginal(regular.baselinePath,regular.baselineSha256));if(baseline.stateSha256!==spec.baselineStateSha256||baseline.nativeThreadId!==regular.nativeThreadId)throw Error('root_exact_original_regular_baseline_required');await this.reopenBaseline(baseline);
 }
 private assertTraceOriginals(packet:any){const receipt=traceOriginals.get(packet),dir=receipt&&this.originalReceiptDirectories.get(receipt.nonce);if(!receipt||!dir)throw Error('actual_original_receipt_directory_required');for(const name of ['launch','settlement','trace']){const key=name==='trace'?'traceReceipt':name+'Receipt';if(protectedOriginal(join(dir,name+'.json'),packet[key+'Sha256'])!==packet[key+'Utf8'])throw Error('actual_original_receipt_changed');}for(const event of receipt.events){if(sha256(protectedOriginal(join(dir,event.file),event.sha256))!==event.sha256)throw Error('actual_original_trace_line_changed');}}
 private traceCaptures=new Map<string,any>();private traceFailure?:Error;private captureFailure?:Error;private application:any;private captures=new Map<string,any>();private producers=new Map<string,any>();private rolloutPath?:string;private currentProcess?:object;private holding=false;private reopenedBaseline?:any;private fault?:{plan:any;baseline:any;checkpoint:any;consumed:boolean;failedRunUtf8?:string};private recovery?:any;
 constructor(readonly config:any,readonly qualification:EntryQualification){this.observer=new NativeObserver(config.hostPrivate);this.counts=new NativeCountObserver(config.hostPrivate);}
 active(signal?:AbortSignal){if(signal?.aborted||Date.now()>=reviewedAuthorization(this.config.review).dispatchCutoffAt)throw Error('normal_product_dispatch_cutoff');}
 attach(application:any){if(this.application||!application.gateway||application.store.databasePath!==join(this.config.dataDir,'harness.sqlite'))throw Error('actual_normal_application_gateway_unavailable');this.application=application;}
 private owned(id:string){if(id!==this.config.sessionId)throw Error('normal_producer_foreign_session');return this.application;}
 private raw(r:any){const bytes=getCodexReceiptUtf8(r);if(!bytes)throw Error('actual_current_transport_receipt_required');return bytes;}
 capture:NonNullable<GatewayOptions['diagnostics']>['capture']=event=>{if(event.sessionId!==this.config.sessionId)return;try{if(this.captureFailure)throw this.captureFailure;if(event.phase==='pre_normalization'){if(this.captures.has(event.requestId))throw Error('normal_capture_duplicate');const bytes=Buffer.from(event.bytes),raw=bytes.toString('utf8');if(!Buffer.from(raw).equals(bytes))throw Error('normal_capture_invalid_utf8');this.captures.set(event.requestId,{requestId:event.requestId,sessionId:event.sessionId,firstRequestUtf8:raw,captureSha256:sha256(raw),observedAt:new Date().toISOString()});}else if(event.phase==='normalized_request'){const c=this.captures.get(event.requestId);if(!c?.normalizedRequestUtf8||c.normalizedRequestUtf8!==Buffer.from(event.bytes).toString('utf8'))throw Error('normal_actual_gateway_normalization_changed');}}catch(error){this.captureFailure=error instanceof Error?error:Error('normal_capture_failed');throw this.captureFailure;}};

 private traceHooks():Pick<CodexHostQualification,'nativeTraceMode'|'onNativeTraceReceipt'>{
  const selectedMode=normalProductTraceMode(this.config.review);assertNormalProductTraceReady(selectedMode);
  if(selectedMode==='off')return {nativeTraceMode:undefined,onNativeTraceReceipt:undefined};
  return {nativeTraceMode:selectedMode,onNativeTraceReceipt:r=>{try{
   if(this.traceFailure)throw this.traceFailure;
   if(!traceApi.isVerifiedCodexTraceReceipt(r))throw Error('actual_owned_current_A_trace_receipt_required');
   if(r.sessionId!==this.config.sessionId||r.mode!==selectedMode||this.traceCaptures.has(r.nonce))throw Error('actual_owned_current_A_trace_receipt_required');
   const producer=this.producers.get(r.nonce);if(!producer?.settlementReceiptUtf8)throw Error('actual_trace_after_owned_settlement_required');
   // Settled evidence is accepted through expiry; the reserve forbids new
   // dispatch, not collection of the already owned operation's originals.
   reviewedAuthorization(this.config.review);verifyTraceSchemaMode(r.schema,selectedMode);
   const packet=projectNormalProductTrace(r,selectedMode,producer,{sessionId:this.config.sessionId,receiptSources:this.qualification.receiptSources});
   // Projection rechecks the complete original carrier. The branded callback
   // remains mandatory; a valid JSON packet cannot create it.
   this.traceCaptures.set(r.nonce,packet);
  }catch(e){this.traceFailure=e instanceof Error?e:Error('actual_trace_capture_failed');throw this.traceFailure;}}};
 }
 hooks(base:CodexHostQualification):CodexHostQualification{
  const traceHooks=this.traceHooks();
  if(normalProductTraceMode(this.config.review)==='off'&&(base.nativeTraceMode!==undefined||base.onNativeTraceReceipt!==undefined))throw Error('explicit_off_cannot_inherit_native_trace_configuration');
  return {...base,
   ...traceHooks,
   observations:{onNativeProcess:(event:any)=>{if(event.sessionId===this.config.sessionId){if(this.holding)throw Error('normal_owned_capture_blocks_new_launch');this.currentProcess=event.process;this.observer.registerObserved(event.sessionId,event.process);}},onRawNative:(event:any)=>{if(event.sessionId===this.config.sessionId)this.observer.ingestObserved(event);},onVerifiedCount:async(event:any,signal:AbortSignal)=>{
    const c=this.captures.get(event.context?.requestId);if(this.captureFailure)throw this.captureFailure;if(!c)throw Error('normal_owned_count_raw_capture_missing');this.active(signal);const app=this.owned(c.sessionId),runs=app.store.db.prepare("SELECT id,kind FROM runs WHERE session_id=? AND status='running'").all(c.sessionId);if(this.holding||runs.length!==1)throw Error('actual_unique_normal_store_run_required');const raw=JSON.parse(c.firstRequestUtf8),m=JSON.parse(raw.client_metadata?.['x-codex-turn-metadata']??'null'),translated={...translateResponses(raw).body,model:event.lane};if(!m||m.thread_id!==app.store.getSession(c.sessionId).nativeSessionId||typeof m.turn_id!=='string'||stableJson(translated)!==stableJson(event.body)||sha256(JSON.stringify(event.body))!==event.bodySha256)throw Error('normal_compiled_request_actual_owner_translation');const policy=this.config.review.normalToolPolicies?.[m.request_kind==='compaction'?'compaction':'parent'];if(!policy||sha256(stableJson(raw.tools))!==policy.rawToolsSha256||sha256(stableJson(event.body.tools))!==policy.translatedToolsSha256)throw Error('normal_reviewed_distinct_tool_policy_before_dispatch');Object.assign(c,{runId:String(runs[0].id),nativeThreadId:m.thread_id,nativeTurnId:m.turn_id,normalizedRequestUtf8:JSON.stringify(event.body),normalizedSha256:event.bodySha256});await durableFile(join(this.config.hostPrivate,`${c.requestId}-normal-provider-capture.json`),stableJson(c));await this.counts.retainVerifiedEvent(event,signal);this.active(signal);
   }},
   beforeNativeAction:async input=>{await base.beforeNativeAction?.(input);if(input.sessionId===this.config.sessionId)this.active();if(input.sessionId===this.config.sessionId&&this.holding)throw Error('normal_capture_blocks_native_mutation');if(input.sessionId===this.config.sessionId&&this.automaticReady){const ready=this.automaticReady,spec=this.config.review.automaticPreparation.config,packet=this.traceCaptures.get(this.config.review.automaticPreparation.regular.launchNonce);assertFiniteAutomaticTurn(input,this.config.sessionId,ready.regular.nativeThreadId,this.config.review.automaticPlan.approvedText,this.automaticDispatched);this.assertTraceOriginals(packet);projectAutomaticConfig({configUtf8:protectedOriginal(spec.configPath,spec.configSha256),catalogUtf8:protectedOriginal(spec.catalogPath,spec.catalogSha256),projectionUtf8:protectedOriginal(spec.projectionPath,spec.projectionSha256)},spec,packet);if(!traceApi.isVerifiedCodexLaunchReceipt(input.launchReceipt)||input.launchReceipt.sources['codex/config.toml']!==spec.configSha256||input.launchReceipt.sources['codex/models.json']!==spec.catalogSha256||!this.rolloutPath||sha256(readFileSync(this.rolloutPath))!==ready.baselineStateSha256)throw Error('automatic_actual_dispatch_config_baseline_changed');this.automaticDispatched++;}},
   onNativeLaunchReceipt:r=>{base.onNativeLaunchReceipt?.(r);if(r.sessionId===this.config.sessionId){if(this.producers.has(r.nonce))throw Error('actual_normal_launch_receipt_no_replay');const origin=traceApi.codexReceiptProvenance(r);if(!origin)throw Error('actual_normal_original_launch_path_required');this.originalReceiptDirectories.set(r.nonce,dirname(origin.rawPath));this.producers.set(r.nonce,{launchReceiptUtf8:this.raw(r),launchReceiptSha256:sha256(this.raw(r))});}},
   onNativeThread:async input=>{await base.onNativeThread?.(input);if(input.sessionId===this.config.sessionId){if(!input.rolloutPath)throw Error('actual_normal_rollout_path_missing');this.rolloutPath=input.rolloutPath;await durableFile(join(this.config.hostPrivate,`${input.launchReceipt.nonce}-normal-thread.json`),stableJson({source:'actual-normal-native-thread',sessionId:input.sessionId,threadId:input.threadId,rolloutPath:input.rolloutPath,method:input.method,observedSettings:input.observedSettings}));}},
   onNativeSettlementReceipt:r=>{base.onNativeSettlementReceipt?.(r);if(r.sessionId===this.config.sessionId){const p=this.producers.get(r.nonce);if(!p||p.settlementReceiptUtf8)throw Error('normal_settlement_without_actual_launch_or_replayed');p.settlementReceiptUtf8=this.raw(r);p.settlementReceiptSha256=sha256(p.settlementReceiptUtf8);if(!this.currentProcess||!r.cleanupOk)throw Error('actual_normal_cleanup_missing');this.observer.cleanupObserved(this.currentProcess);}},
  } as CodexHostQualification;
 }
 async reopenBaseline(baseline:any){const app=this.owned(baseline.sessionId);if(this.rolloutPath||baseline.nativeThreadId!==app.store.getSession(baseline.sessionId).nativeSessionId||sha256(baseline.stateUtf8)!==baseline.stateSha256)throw Error('normal_reopen_exact_accepted_parent_required');const path=baseline.rolloutPath;if(typeof path!=='string'||!path.startsWith(app.files.profile(baseline.sessionId)+'/')||sha256(await readFile(path))!==baseline.stateSha256)throw Error('normal_reopen_protected_rollout_changed');await app.files.assertNoLinks(path);const session=app.store.getSession(baseline.sessionId);if(session.nativeState.ownership!=='idle'||session.nativeState.activeTurnId!==null||app.store.isQuarantined(session.workspaceId)||app.store.runs(session.id).some((r:any)=>['queued','running','cancelling'].includes(r.status)))throw Error('normal_reopened_owner_not_idle');this.active();const token=app.gateway.issueToken(session.id,'codex');try{this.active();}finally{app.gateway.revokeToken(token);}this.rolloutPath=path;this.reopenedBaseline=baseline;}
 private async reopenedState(sessionId:string){const app=this.owned(sessionId);await app.files.assertNoLinks(this.rolloutPath);const before=await lstat(this.rolloutPath!),bytes=await readFile(this.rolloutPath!),after=await lstat(this.rolloutPath!);if(!before.isFile()||before.nlink!==1||before.ino!==after.ino||before.size!==after.size||before.mtimeMs!==after.mtimeMs||sha256(bytes)!==this.reopenedBaseline.stateSha256)throw Error('actual_reopened_rollout_changed');const receiptUtf8=stableJson({source:'normal-store-reopened-rollout',sessionId,nativeThreadId:this.reopenedBaseline.nativeThreadId,stateSha256:sha256(bytes),observedAt:new Date().toISOString(),newNativeLaunch:false});return {...this.reopenedBaseline,stateUtf8:bytes.toString('utf8'),stateSha256:sha256(bytes),receiptUtf8,receiptSha256:sha256(receiptUtf8)};}
 async gatewayObservation(sessionId:string){const app=this.owned(sessionId),native=app.store.getSession(sessionId).nativeState;if(!await app.gateway.confirmSettlement({sessionId})||native.ownership!=='idle'||native.activeTurnId!==null)throw Error('normal_owner_not_settled');const bracket=await app.gateway.observeNoGeneration(sessionId,async()=>null);const row=app.store.db.prepare('SELECT MAX(sequence) AS n FROM h041_gateway_admissions WHERE session_id=?').get(sessionId);if(row?.n===undefined)throw Error('actual_durable_gateway_admission_snapshot_unavailable');const records=app.store.db.prepare('SELECT record FROM h021_gateway_requests WHERE session_id=? ORDER BY rowid').all(sessionId).map((r:any)=>String(r.record));return {source:'owned-normal-gateway-observation',sessionId,ownerId:bracket.proof.ownerId,admissionSequence:Number(row.n??0),outstanding:app.gateway.sessionWork(sessionId),records};}
 async settled(sessionId:string,signal:AbortSignal){signal.throwIfAborted();const app=this.owned(sessionId);if(this.holding)throw Error('normal_capture_already_held');this.holding=true;try{return await app.gateway.observeNoGeneration(sessionId,async()=>{
  const gateway=await this.gatewayObservation(sessionId),session=app.store.getSession(sessionId);if(!this.rolloutPath)throw Error('actual_normal_rollout_unobserved');const collector=new NativeCollector({store:app.store,files:app.files,gateway:app.gateway,guard:{} as any,observer:this.observer,hostPrivate:this.config.hostPrivate,withCaptureHold:async (work:()=>Promise<any>)=>work()});if(this.currentProcess)this.observer.gateway(sessionId,session.nativeSessionId,session.nativeState.lastSettledTurnId??null,true);const state=this.reopenedBaseline&&!this.currentProcess?await this.reopenedState(sessionId):await collector.captureState(sessionId,'normal-product-owned-no-writer');
  const stat=await lstat(app.store.databasePath),inventory=app.store.memory.inventory(sessionId),rows=app.store.db.prepare('SELECT rowid,id,kind,source_key,sha256,bytes,availability FROM h041_originals WHERE session_id=? AND rowid<=? ORDER BY rowid').all(sessionId,inventory.through);if(rows.length>4096||rows.length!==inventory.count||sha256(rows.map((r:any)=>JSON.stringify(r)+'\n').join(''))!==inventory.sha256)throw Error('actual_full_original_inventory');
  const originalInventoryUtf8=stableJson({sessionId,through:inventory.through,count:inventory.count,sha256:inventory.sha256,rows,references:rows.map((r:any)=>app.store.memory.resolve(sessionId,r.id))});const accepted=app.store.db.prepare('SELECT v.body FROM h041_memory_current c JOIN h041_memory_versions v ON v.id=c.version_id AND v.session_id=c.session_id WHERE c.session_id=?').get(sessionId),acceptedStateUtf8=accepted?String(accepted.body):'null';
  const baseline={source:'owned-normal-product-baseline',sessionId,...state,rolloutPath:this.rolloutPath,storeIdentity:{canonicalPath:app.store.databasePath,ino:stat.ino,dev:stat.dev},originalInventoryUtf8,originalInventorySha256:sha256(originalInventoryUtf8),acceptedStateUtf8,acceptedStateSha256:sha256(acceptedStateUtf8),gatewayAdmissionSequence:gateway.admissionSequence};await durableFile(join(this.config.hostPrivate,`${sha256(stableJson(baseline))}-normal-baseline.json`),stableJson(baseline));return baseline;
 }).then(async(value:any)=>{const noGenerationUtf8=stableJson(value.proof),baseline={...value.value,noGenerationUtf8,noGenerationSha256:sha256(noGenerationUtf8)};await durableFile(join(this.config.hostPrivate,`${sha256(stableJson(baseline))}-normal-baseline.json`),stableJson(baseline));return baseline;});}finally{this.holding=false;}}
 async settleRun(sessionId:string,runId:string,signal:AbortSignal){const app=this.owned(sessionId),deadline=reviewedAuthorization(this.config.review).expiresAt;await bounded(new Promise<void>((resolve,reject)=>{const check=()=>{if(signal.aborted)return reject(Error('normal_run_cancelled'));const row=app.store.db.prepare('SELECT status FROM runs WHERE session_id=? AND id=?').get(sessionId,runId);if(!row)return reject(Error('actual_normal_run_absent'));if(['completed','failed','cancelled'].includes(row.status)){resolve();return;}if(Date.now()>=deadline)return reject(Error('normal_settlement_deadline'));setTimeout(check,20);};check();}),Math.max(1,deadline-Date.now()),'normal_run_settlement_timeout');if(await app.gateway.observeSettlement({sessionId},signal)!==true)throw Error('actual_normal_gateway_settlement_false');const state=app.store.getSession(sessionId);if(state.nativeState.ownership!=='idle'||state.nativeState.activeTurnId!==null)throw Error('actual_normal_native_not_idle');this.observer.gateway(sessionId,state.nativeSessionId,state.nativeState.lastSettledTurnId??null,true);const row=app.store.db.prepare('SELECT status FROM runs WHERE session_id=? AND id=?').get(sessionId,runId);const operation=this.observer.operation(sessionId),tracePackets=[...this.traceCaptures.values()].filter(p=>JSON.parse(p.traceReceiptUtf8).events.some((e:any)=>e.turnId===operation.nativeTurnId));for(const packet of tracePackets)await durableFile(join(this.config.hostPrivate,`${runId}-${packet.traceReceiptSha256}-actual-original-trace.json`),stableJson(packet));return {sessionId,runId,nativeThreadId:state.nativeSessionId,nativeOutcome:row.status,settlement:{state:'released'},nativeFramesUtf8:stableJson(this.observer.frames(sessionId)),requests:[...this.captures.values()].filter(c=>c.runId===runId),tracePackets,traceStatus:this.traceFailure?'FAIL':tracePackets.length?'SOURCE_VALID':'NOT_TESTED'};}
 async closeReceipt(sessionId:string){const g=await this.gatewayObservation(sessionId),values=[...this.producers.values()];if(!values.length||values.some(v=>!v.settlementReceiptUtf8))throw Error('normal_close_native_producer_missing');const gatewayObservationUtf8=stableJson(g);return {source:'owned-normal-product-close',sessionId,nativeProducers:values,outstanding:[],gatewayObservationUtf8,gatewayObservationSha256:sha256(gatewayObservationUtf8)};}

 async armVerificationFault(plan:any,baseline:any,signal:AbortSignal){this.active(signal);if(this.fault||plan.kind!=='manual-replacement-verification'||stableJson(plan)!==stableJson(this.config.review.verificationFault)||baseline.sessionId!==this.config.sessionId)throw Error('root_frozen_one_shot_manual_fault_required');const current=await this.settled(this.config.sessionId,signal);if(current.stateUtf8!==baseline.stateUtf8||current.acceptedStateUtf8!==baseline.acceptedStateUtf8||current.originalInventoryUtf8!==baseline.originalInventoryUtf8)throw Error('actual_fault_baseline_changed');this.active(signal);this.fault={plan,baseline,checkpoint:null,consumed:false};}
 beforeNativeReplacementCommit=async(input:any)=>{if(input.sessionId!==this.config.sessionId)return;this.active();const f=this.fault;if(!f||f.consumed)return;const app=this.owned(input.sessionId),run=app.store.db.prepare('SELECT id,kind,status FROM runs WHERE session_id=? AND id=?').get(input.sessionId,input.runId);if(run?.status!=='running'||run.kind!=='compact'||input.checkpoint.sessionId!==input.sessionId||input.checkpoint.runId!==input.runId||input.checkpoint.nativeThreadId!==f.baseline.nativeThreadId||!input.checkpoint.compactions.some((c:any)=>c.status==='completed'))throw Error('fault_requires_actual_owned_completed_compaction');f.consumed=true;f.checkpoint=input.checkpoint;await durableFile(join(this.config.hostPrivate,`${input.checkpoint.id}-actual-negative-only-fault.json`),stableJson({source:'actual-completed-replacement-negative-only-verifier',sessionId:input.sessionId,runId:input.runId,checkpoint:input.checkpoint,beforeBaselineSha256:sha256(stableJson(f.baseline)),planSha256:sha256(stableJson(f.plan))}));this.active();throw Error('root_reviewed_negative_only_replacement_verification_rejected');};
 beforeNativeRecovery=async(input:any,signal:AbortSignal)=>{this.active(signal);if(input.sessionId!==this.config.sessionId||!this.fault?.consumed||input.checkpointId!==this.fault.checkpoint.id)throw Error('exact_owned_fault_recovery_required');};
 onNativeRecoveryObserved=async(input:any,signal:AbortSignal)=>{this.active(signal);if(input.sessionId!==this.config.sessionId||input.checkpointId!==this.fault?.checkpoint.id)throw Error('actual_owned_recovery_observation_scope');const e=input.evidence;if(e.launch.kind!=='launch'||e.settlement.kind!=='settlement'||e.thread.kind!=='thread')throw Error('actual_recovery_observation_types');const launchReceiptUtf8=this.raw(e.launch.receipt),settlementReceiptUtf8=this.raw(e.settlement.receipt);this.observer.gateway(input.sessionId,e.thread.threadId,e.gateway.lastSettledTurnId??null,true);this.recovery={source:'actual-normal-recovery-observed',sessionId:input.sessionId,checkpointId:input.checkpointId,freshProducer:{launchReceiptUtf8,launchReceiptSha256:sha256(launchReceiptUtf8),settlementReceiptUtf8,settlementReceiptSha256:sha256(settlementReceiptUtf8)},nativeFrames:this.observer.frames(input.sessionId),noGeneration:e.noGeneration};await durableFile(join(this.config.hostPrivate,`${input.checkpointId}-actual-recovery-observed.json`),stableJson(this.recovery));this.active(signal);};
 async recoveryCapture(checkpointId:string,signal:AbortSignal){const app=this.owned(this.config.sessionId),f=this.fault;if(!f?.consumed||f.checkpoint.id!==checkpointId)throw Error('actual_armed_fault_checkpoint_missing');const checkpoint=app.store.checkpoints.status(this.config.sessionId).find((r:any)=>r.id===checkpointId),failedRun=app.store.runs(this.config.sessionId).find((r:any)=>r.id===f.checkpoint.runId);if(failedRun?.status!=='failed'||!checkpoint)throw Error('actual_sticky_failed_run_missing');const failedRunUtf8=stableJson(failedRun);if(f.failedRunUtf8&&f.failedRunUtf8!==failedRunUtf8)throw Error('original_failed_run_changed');if(!this.recovery){f.failedRunUtf8=failedRunUtf8;f.checkpoint=checkpoint;}if(!f.failedRunUtf8)throw Error('pre_recovery_failed_run_capture_required');if(!this.recovery)return {nativeOutcome:'failed',failedRunUtf8,beforeBaselineSha256:sha256(stableJson(f.baseline)),checkpointId,sessionId:this.config.sessionId};
  const after=await this.settled(this.config.sessionId,signal),beforeInventory=JSON.parse(f.baseline.originalInventoryUtf8),afterInventory=JSON.parse(after.originalInventoryUtf8),retainedRows=afterInventory.rows.filter((r:any)=>r.rowid<=beforeInventory.through);if(stableJson(retainedRows)!==stableJson(beforeInventory.rows))throw Error('actual_original_prefix_after_recovery_changed');const transitions=app.store.db.prepare('SELECT body FROM h041_checkpoint_transitions WHERE session_id=? AND run_id=?').all(this.config.sessionId,f.checkpoint.runId).map((r:any)=>JSON.parse(String(r.body))),transition=transitions.find((r:any)=>r.kind==='fresh_parent_no_replay');if(!transition)throw Error('actual_fresh_parent_transition_not_applied');const pair=(key:string,value:any)=>{const text=stableJson(value);return {[key+'Utf8']:text,[key+'Sha256']:sha256(text)};},g=await this.gatewayObservation(this.config.sessionId);
  const receipt={source:'owned-normal-product-recovery-v1',sessionId:this.config.sessionId,checkpointId,...pair('beforeBaseline',f.baseline),...pair('afterBaseline',after),...pair('checkpoint',f.checkpoint),failedRunBeforeUtf8:f.failedRunUtf8,failedRunBeforeSha256:sha256(f.failedRunUtf8),...pair('failedRunAfter',failedRun),preservedOriginalRolloutUtf8:f.baseline.stateUtf8,preservedOriginalRolloutSha256:f.baseline.stateSha256,...pair('checkpointOriginalInventory',f.checkpoint.originalInventory),afterCheckpointOriginalInventoryUtf8:stableJson(checkpoint.originalInventory),...pair('afterBaselineOriginalInventory',{...beforeInventory,rows:retainedRows}),freshProducer:this.recovery.freshProducer,...pair('nativeFrames',this.recovery.nativeFrames),...pair('noGeneration',this.recovery.noGeneration),...pair('gatewayObservation',g),...pair('recoveredCheckpoint',checkpoint),...pair('recoveryTransition',transition),replayedActionIds:[]};return {failedRunUtf8,...pair('recoveryReceipt',receipt)};
 }

 prepareAutomatic(plan:any,signal:AbortSignal){
  this.active(signal);assertH044ProducerSourceActivation(this.config.review.authorization.task);if(stableJson(plan)!==stableJson(this.config.review.automaticPlan))throw Error('root_frozen_automatic_plan_required');
  const unavailable=(reason:string)=>({status:'NOT_TESTED',nativeAcceptance:'NOT_TESTED',qualificationSha256:this.qualification.qualificationSha256,planSha256:sha256(stableJson(plan)),sourceSha256:null,resolvedConfigSha256:null,errors:[reason],generationAllowed:false});
  if(this.traceFailure||this.captureFailure)return unavailable('actual_original_capture_failed');
  if(!isQualifiedEntry(this.qualification))return unavailable('actual_native_startup_and_owned_shutdown_qualification_required');
  const spec=this.config.review.automaticPreparation;if(!spec)return unavailable('exact_root_reviewed_automatic_projection_and_regular_originals_required');
  if(this.automaticReady||this.automaticCaptured)throw Error('finite_automatic_preparation_no_replay');
  if(plan.contextWindow!==480000||plan.autoCompactTokenLimit!==400000||plan.maxOutputTokens!==65536||plan.maximumGenerationTurns!==1||plan.expectedPhase!=='mid_turn'||typeof plan.approvedText!=='string'||!plan.approvedText||Buffer.byteLength(plan.approvedText)>2000000||typeof plan.summaryPrefix!=='string'||!plan.summaryPrefix)throw Error('finite_current_400k_mid_turn_plan_required');
  const packet=this.traceCaptures.get(spec.regular.launchNonce);if(!packet)return unavailable('actual_previous_regular_sampling_original_trace_unavailable');this.assertTraceOriginals(packet);
  if(normalProductTraceMode(this.config.review)!==spec.regular.mode||spec.regular.sessionId!==this.config.sessionId||stableJson(spec.regular.receiptSources)!==stableJson(this.qualification.receiptSources))throw Error('current_selected_regular_trace_source_binding_required');
  const frames=JSON.parse(protectedOriginal(spec.regular.framesPath,spec.regular.framesSha256)),observed=this.reviewedRegularFrames??this.observer.frames(this.config.sessionId);
  if(frames.some((f:any)=>!observed.some((o:any)=>stableJson(o)===stableJson(f)))||observed.some((f:any)=>f.sequence>frames.at(-1)?.sequence&&f.direction==='to-native'&&['turn/start','thread/compact/start','thread/rollback','thread/fork','thread/unarchive'].includes(f.value.method)))throw Error('current_original_regular_frame_span_and_no_intervening_mutation_required');
  const regular=verifyRegularSamplingExclusion(packet,frames,spec.regular),originals={configUtf8:protectedOriginal(spec.config.configPath,spec.config.configSha256),catalogUtf8:protectedOriginal(spec.config.catalogPath,spec.config.catalogSha256),projectionUtf8:protectedOriginal(spec.config.projectionPath,spec.config.projectionSha256)},config=projectAutomaticConfig(originals,spec.config,packet);
  const app=this.owned(this.config.sessionId),session=app.store.getSession(this.config.sessionId);if(session.nativeSessionId!==regular.nativeThreadId||session.nativeState.ownership!=='idle'||session.nativeState.activeTurnId!==null||session.nativeState.lastSettledTurnId!==regular.nativeTurnId||!this.rolloutPath||sha256(readFileSync(this.rolloutPath))!==spec.baselineStateSha256||app.store.runs(session.id).some((r:any)=>['queued','running','cancelling'].includes(r.status))||app.gateway.sessionWork(session.id).length)throw Error('current_settled_regular_baseline_required');
  const sourceSha256=sha256(readFileSync(fileURLToPath(import.meta.url)));if(sourceSha256!==this.config.review.activeContextProducerSourceSha256||sha256(stableJson(plan))!==this.config.review.activeContextProducerPlanSha256)throw Error('root_exact_current_automatic_producer_source_plan_required');
  this.automaticReady=reviewSnapshot({status:'SOURCE_VALID',nativeAcceptance:'NOT_TESTED',generationAllowed:true,errors:[],qualificationSha256:this.qualification.qualificationSha256,planSha256:sha256(stableJson(plan)),sourceSha256,resolvedConfigSha256:config.resolvedConfigSha256,resolvedConfig:config.resolvedConfig,regular,baselineStateSha256:spec.baselineStateSha256,configProjectionSha256:config.projectionSha256,selectedMode:spec.regular.mode,receiptSources:this.qualification.receiptSources});return this.automaticReady;
 }
 async automaticCapture(runId:string,operationId:string,baseline:any,signal:AbortSignal){
  signal.throwIfAborted();const sessionId=this.config.sessionId,ready=this.automaticReady;
  if(!ready||this.automaticDispatched!==1||this.automaticCaptured||baseline.stateSha256!==ready.baselineStateSha256)throw Error('actual_finite_automatic_ready_baseline_required');this.automaticCaptured=true;
  const capture=await collectOrdinaryAutomatic({application:this.application,qualification:this.qualification,observer:this.observer,counts:this.counts,gateway:this.application.gateway,layout:{hostPrivate:this.config.hostPrivate},tracePackets:()=>[...this.traceCaptures.values()],guard:{requests:()=>[...this.captures.values()]},evidence:{parentProducer:()=>{const op=this.observer.operation(sessionId),nonce=JSON.parse([...this.producers.values()].at(-1).launchReceiptUtf8).nonce,p=this.producers.get(nonce);if(!p?.settlementReceiptUtf8||op.sessionId!==sessionId)throw Error('actual_auto_owned_producer_missing');return p;}},withCaptureHold:async (work:()=>Promise<any>)=>{if(this.holding)throw Error('actual_auto_hold_already_active');this.holding=true;try{return await work();}finally{this.holding=false;}}},{sessionId,storeRunId:runId,operationId,baseline,summaryPrefix:this.config.review.automaticPlan.summaryPrefix});
  const r=JSON.parse(capture.automaticReceiptUtf8);if(!r.nativeTracePacketUtf8)throw Error('actual_automatic_original_trace_missing_no_retry');const rawPacket=JSON.parse(r.nativeTracePacketUtf8),packet=this.traceCaptures.get(JSON.parse(rawPacket.traceReceiptUtf8).nonce);
  if(!packet||!traceOriginals.has(packet)||stableJson(packet)!==r.nativeTracePacketUtf8||packet.selectedMode!==ready.selectedMode)throw Error('actual_current_automatic_trace_origin_required');this.assertTraceOriginals(packet);
  const regularPacket=this.traceCaptures.get(this.config.review.automaticPreparation.regular.launchNonce);this.assertTraceOriginals(regularPacket);
  const spec=this.config.review.automaticPreparation.config,projected=projectAutomaticConfig({configUtf8:protectedOriginal(spec.configPath,spec.configSha256),catalogUtf8:protectedOriginal(spec.catalogPath,spec.catalogSha256),projectionUtf8:protectedOriginal(spec.projectionPath,spec.projectionSha256)},spec,regularPacket);
  if(projected.resolvedConfigSha256!==ready.resolvedConfigSha256)throw Error('automatic_protected_config_changed');
  const trace=verifyRetainedTrace(packet,{sessionId,mode:ready.selectedMode,receiptSources:ready.receiptSources,traceReceiptSha256:packet.traceReceiptSha256,launchReceiptSha256:packet.launchReceiptSha256,settlementReceiptSha256:packet.settlementReceiptSha256});
  const launch=JSON.parse(packet.launchReceiptUtf8);if(launch.sources['codex/config.toml']!==projected.configSha256||launch.sources['codex/models.json']!==projected.catalogSha256)throw Error('automatic_current_config_sources_changed');
  const metadata=automaticMetadata(JSON.parse(r.requests[0].firstRequestUtf8),r.nativeThreadId,r.nativeTurnId),frames=JSON.parse(r.nativeFramesUtf8),operation=JSON.parse(r.nativeOperationUtf8),start=automaticFrames(frames,r.nativeThreadId,r.nativeTurnId).start,nativeStart=nativeCompactionStart(start,r.nativeThreadId,r.nativeTurnId),records=r.gatewayRecords.map((s:string)=>JSON.parse(s)),record=records.find((x:any)=>x.id===r.requests[0].requestId),gateway={requestId:record?.id,nativeThreadId:record?.nativeMetadata?.thread_id,nativeTurnId:record?.nativeMetadata?.turn_id,windowId:record?.nativeMetadata?.window_id,contextWindowId:record?.nativeMetadata?.context_window_id,state:record?.state};
  const causalInput={lines:trace.lines,autoCalls:trace.autoCalls,startFrame:start,producer:trace.producer,operation,metadata,gateway,resolvedConfig:ready.resolvedConfig};
  verifyNativeStartedAtTraceJoin(trace.schema==='codex-native-trace-v2'?{...causalInput,schema:trace.schema,mode:'post-sampling-token-usage-v2'}:{...causalInput,schema:trace.schema,mode:'post-sampling-token-usage-v1'});
  r.nativeResolvedConfigProofUtf8=stableJson(ready.resolvedConfig);r.nativeTraceCausalProofUtf8=stableJson({source:'native-v2-item-started-timestamp-v1',launchNonce:trace.producer.launchNonce,processId:trace.producer.processId,requestId:record.id,startFrameSha256:nativeStart.frameSha256,startedAtMs:nativeStart.startedAtMs,preparationSha256:sha256(stableJson(ready))});
  const automaticReceiptUtf8=stableJson(r);await durableFile(join(this.config.hostPrivate,`${operationId}-automatic-causal-config-originals.json`),automaticReceiptUtf8);return {...capture,automaticReceiptUtf8,automaticReceiptSha256:sha256(automaticReceiptUtf8)};
 }
 nativeEvidence(){return {frames:()=>this.observer.frames(this.config.sessionId),captures:()=>[...this.captures.values()],producers:()=>[...this.producers.values()],counts:this.counts};}
}
export async function startNormalProduct(configPath:string,restart?:import('./normal-restart-ticket.js').NormalRestartTicket){
 const configBytes=await privateFile(configPath),config=reviewSnapshot(JSON.parse(configBytes.toString('utf8'))),a=reviewedAuthorization(config.review);if(restart)assertNormalRestartConfig(restart,config,configBytes);if(process.platform!=='linux'||!process.getuid?.()||config.review.approvedBy!=='root'||config.review.actor!=='worker1'||!identifier(config.sessionId)||Date.now()>=a.dispatchCutoffAt)throw Error('reviewed_actual_normal_product_entry_required');

 assertH044ProducerSourceActivation(config.review.authorization.task);
 const qualification=await qualifyEntry(config.qualificationConfig,restart);if(!isQualifiedEntry(qualification))throw Error('actual_current_native_qualification_required');
 const ordinary=loadCodexOrdinaryEntry(config.ordinaryEntryPath,config.ordinaryEntryKeyPath,{serverDir:config.serverDir,deploymentDir:config.deploymentDir});if(!ordinary)throw Error('genuine_protected_normal_data_entry_required');
 const receipt=await loadQwenReceipt(config.qwenReceiptPath),inferenceKey=await readProtectedCredential(config.inferenceKeyPath),controlKey=await readProtectedCredential(config.controlKeyPath),verifyLane=createProductionQwenVerifier(receipt,{inferenceKey,controlKey});
 assertNormalProductTraceReady(normalProductTraceMode(config.review));
 const base:CodexHostQualification={protocolQualified:true,rootlessQualified:true,verifyLane,qualifiedAliases:Object.keys(receipt.lanes),outputLimit:65536,nativeReceiptPolicy:ordinary.nativeReceiptPolicy};
 const taskAdmission=config.carrier?loadQualificationTaskAdmission(validateCarrierBinding({...config,bootstrap:{review:config.review}}).admissionPath):undefined;
 if(taskAdmission){await taskAdmission.registerSession({sessionId:config.sessionId,role:'parent'});await taskAdmission.verify({sessionId:config.sessionId,requestId:'normal-product-open',lane:'qwen3.8-27b'});}
 const producer=new NormalProductProducer(config,qualification);producer.active();const application=await start({taskAdmission,beforeNativeRecovery:producer.beforeNativeRecovery,onNativeRecoveryObserved:producer.onNativeRecoveryObserved,beforeNativeReplacementCommit:producer.beforeNativeReplacementCommit,enablePreview:true,qualification:composeCodexProductObservers(base,ordinary,producer.hooks(base)),ordinary,providerDiagnostics:{capture:producer.capture}});try{producer.attach(application);await producer.adoptReviewedRegularOriginals();return {application,producer,qualification,config};}catch(error){await application.close();throw error;}
}
export default Object.freeze({enabled:false,capabilities:[],nativeAcceptance:'NOT_TESTED'});
