/** Actual normal main.start composition. Never imports/calls temporary bootstrap. */
import {composeCodexProductObservers} from '../../../server/src/codex-product-observation.js';
import {start} from '../../../server/src/main.js';
import {loadCodexOrdinaryEntry} from '../../../server/src/codex-ordinary-entry.js';
import {createProductionQwenVerifier,loadQwenReceipt} from '../../../server/src/codex-production.js';
import {readProtectedCredential} from '../../../server/src/protected-credential.js';
import * as traceApi from '../../../server/src/codex-receipts.js';
import {parsePostSamplingTrace} from '../native-trace-evidence.mjs';
import {getCodexReceiptUtf8} from '../../../server/src/codex-receipts.js';
import {translateResponses} from '../../../server/src/codex-responses.js';
import type {CodexHostQualification} from '../../../server/src/codex-host.js';
import type {GatewayOptions} from '../../../server/src/gateway.js';
import {NativeObserver} from './native-observer.js';
import {NativeCountObserver} from './count-observer.js';
import {NativeCollector} from './collector.js';
import {privateFile,durableFile} from './checkpoint.js';
import {sha256,stableJson,reviewSnapshot,identifier} from './projection.js';
import {qualifyEntry,isQualifiedEntry,type EntryQualification} from './qualification.js';
import {reviewedAuthorization} from '../authorization.mjs';
import {lstat,readFile} from 'node:fs/promises';import {join,dirname} from 'node:path';
import {assertNormalRestartConfig} from './normal-restart-ticket.js';
import {collectOrdinaryAutomatic} from './automatic.js';
import {bounded} from './process-runner.js';
export async function kernelProcessReceipt(pid=process.pid){if(process.platform!=='linux')throw Error('native_normal_process_requires_linux_kernel');const procStatUtf8=await readFile(`/proc/${pid}/stat`,'utf8'),bootIdUtf8=await readFile('/proc/sys/kernel/random/boot_id','utf8'),fields=procStatUtf8.slice(procStatUtf8.lastIndexOf(') ')+2).trim().split(/\s+/);return {source:'linux-proc-process-observation',pid,startTicks:fields[19],bootId:bootIdUtf8.trim(),procStatUtf8,bootIdUtf8};}
export class NormalProductProducer {
 readonly observer:NativeObserver;readonly counts:NativeCountObserver;
 private traceCaptures=new Map<string,any>();private traceFailure?:Error;private captureFailure?:Error;private application:any;private captures=new Map<string,any>();private producers=new Map<string,any>();private rolloutPath?:string;private currentProcess?:object;private holding=false;private reopenedBaseline?:any;private fault?:{plan:any;baseline:any;checkpoint:any;consumed:boolean;failedRunUtf8?:string};private recovery?:any;
 constructor(readonly config:any,readonly qualification:EntryQualification){this.observer=new NativeObserver(config.hostPrivate);this.counts=new NativeCountObserver(config.hostPrivate);}
 active(signal?:AbortSignal){if(signal?.aborted||Date.now()>=reviewedAuthorization(this.config.review).dispatchCutoffAt)throw Error('normal_product_dispatch_cutoff');}
 attach(application:any){if(this.application||!application.gateway||application.store.databasePath!==join(this.config.dataDir,'harness.sqlite'))throw Error('actual_normal_application_gateway_unavailable');this.application=application;}
 private owned(id:string){if(id!==this.config.sessionId)throw Error('normal_producer_foreign_session');return this.application;}
 private raw(r:any){const bytes=getCodexReceiptUtf8(r);if(!bytes)throw Error('actual_current_transport_receipt_required');return bytes;}
 capture:NonNullable<GatewayOptions['diagnostics']>['capture']=event=>{if(event.sessionId!==this.config.sessionId)return;try{if(this.captureFailure)throw this.captureFailure;if(event.phase==='pre_normalization'){if(this.captures.has(event.requestId))throw Error('normal_capture_duplicate');const bytes=Buffer.from(event.bytes),raw=bytes.toString('utf8');if(!Buffer.from(raw).equals(bytes))throw Error('normal_capture_invalid_utf8');this.captures.set(event.requestId,{requestId:event.requestId,sessionId:event.sessionId,firstRequestUtf8:raw,captureSha256:sha256(raw),observedAt:new Date().toISOString()});}else if(event.phase==='normalized_request'){const c=this.captures.get(event.requestId);if(!c?.normalizedRequestUtf8||c.normalizedRequestUtf8!==Buffer.from(event.bytes).toString('utf8'))throw Error('normal_actual_gateway_normalization_changed');}}catch(error){this.captureFailure=error instanceof Error?error:Error('normal_capture_failed');throw this.captureFailure;}};

 hooks(base:CodexHostQualification):CodexHostQualification{
  return {...base,
   ...(this.config.review.nativeTrace?.mode==='post-sampling-token-usage-v1'?{nativeTraceMode:'post-sampling-token-usage-v1',onNativeTraceReceipt:(r:any)=>{try{const api=traceApi as any,raw=api.getCodexTraceUtf8?.(r),events=api.getCodexTraceEvents?.(r);if(!api.isVerifiedCodexTraceReceipt?.(r)||!raw||!events||r.sessionId!==this.config.sessionId||this.traceCaptures.has(r.nonce))throw Error('actual_owned_current_A_trace_receipt_required');const producer=this.producers.get(r.nonce);if(!producer?.settlementReceiptUtf8)throw Error('actual_trace_after_owned_settlement_required');const packet={...producer,traceReceiptUtf8:raw,traceReceiptSha256:sha256(raw),events:events.map((e:any)=>{const lineUtf8=e.bytes.toString('utf8');if(!Buffer.from(lineUtf8).equals(e.bytes))throw Error('original_trace_invalid_utf8');parsePostSamplingTrace(lineUtf8);return {lineUtf8};})};this.traceCaptures.set(r.nonce,packet);}catch(e){this.traceFailure=e instanceof Error?e:Error('actual_trace_capture_failed');throw this.traceFailure;}}}:{}),
   observations:{onNativeProcess:(event:any)=>{if(event.sessionId===this.config.sessionId){if(this.holding)throw Error('normal_owned_capture_blocks_new_launch');this.currentProcess=event.process;this.observer.registerObserved(event.sessionId,event.process);}},onRawNative:(event:any)=>{if(event.sessionId===this.config.sessionId)this.observer.ingestObserved(event);},onVerifiedCount:async(event:any,signal:AbortSignal)=>{
    const c=this.captures.get(event.context?.requestId);if(this.captureFailure)throw this.captureFailure;if(!c)throw Error('normal_owned_count_raw_capture_missing');this.active(signal);const app=this.owned(c.sessionId),runs=app.store.db.prepare("SELECT id,kind FROM runs WHERE session_id=? AND status='running'").all(c.sessionId);if(this.holding||runs.length!==1)throw Error('actual_unique_normal_store_run_required');const raw=JSON.parse(c.firstRequestUtf8),m=JSON.parse(raw.client_metadata?.['x-codex-turn-metadata']??'null'),translated={...translateResponses(raw).body,model:event.lane};if(!m||m.thread_id!==app.store.getSession(c.sessionId).nativeSessionId||typeof m.turn_id!=='string'||stableJson(translated)!==stableJson(event.body)||sha256(JSON.stringify(event.body))!==event.bodySha256)throw Error('normal_compiled_request_actual_owner_translation');const policy=this.config.review.normalToolPolicies?.[m.request_kind==='compaction'?'compaction':'parent'];if(!policy||sha256(stableJson(raw.tools))!==policy.rawToolsSha256||sha256(stableJson(event.body.tools))!==policy.translatedToolsSha256)throw Error('normal_reviewed_distinct_tool_policy_before_dispatch');Object.assign(c,{runId:String(runs[0].id),nativeThreadId:m.thread_id,nativeTurnId:m.turn_id,normalizedRequestUtf8:JSON.stringify(event.body),normalizedSha256:event.bodySha256});await durableFile(join(this.config.hostPrivate,`${c.requestId}-normal-provider-capture.json`),stableJson(c));await this.counts.retainVerifiedEvent(event,signal);this.active(signal);
   }},
   beforeNativeAction:async input=>{await base.beforeNativeAction?.(input);if(input.sessionId===this.config.sessionId)this.active();if(input.sessionId===this.config.sessionId&&this.holding)throw Error('normal_capture_blocks_native_mutation');},
   onNativeLaunchReceipt:r=>{base.onNativeLaunchReceipt?.(r);if(r.sessionId===this.config.sessionId)this.producers.set(r.nonce,{launchReceiptUtf8:this.raw(r),launchReceiptSha256:sha256(this.raw(r))});},
   onNativeThread:async input=>{await base.onNativeThread?.(input);if(input.sessionId===this.config.sessionId){if(!input.rolloutPath)throw Error('actual_normal_rollout_path_missing');this.rolloutPath=input.rolloutPath;await durableFile(join(this.config.hostPrivate,`${input.launchReceipt.nonce}-normal-thread.json`),stableJson({source:'actual-normal-native-thread',sessionId:input.sessionId,threadId:input.threadId,rolloutPath:input.rolloutPath,method:input.method,observedSettings:input.observedSettings}));}},
   onNativeSettlementReceipt:r=>{base.onNativeSettlementReceipt?.(r);if(r.sessionId===this.config.sessionId){const p=this.producers.get(r.nonce);if(!p)throw Error('normal_settlement_without_actual_launch');p.settlementReceiptUtf8=this.raw(r);p.settlementReceiptSha256=sha256(p.settlementReceiptUtf8);if(!this.currentProcess||!r.cleanupOk)throw Error('actual_normal_cleanup_missing');this.observer.cleanupObserved(this.currentProcess);}},
  } as CodexHostQualification;
 }
 async reopenBaseline(baseline:any){const app=this.owned(baseline.sessionId);if(this.rolloutPath||baseline.nativeThreadId!==app.store.getSession(baseline.sessionId).nativeSessionId||sha256(baseline.stateUtf8)!==baseline.stateSha256)throw Error('normal_reopen_exact_accepted_parent_required');const path=baseline.rolloutPath;if(typeof path!=='string'||!path.startsWith(app.files.profile(baseline.sessionId)+'/')||sha256(await readFile(path))!==baseline.stateSha256)throw Error('normal_reopen_protected_rollout_changed');await app.files.assertNoLinks(path);const session=app.store.getSession(baseline.sessionId);if(session.nativeState.ownership!=='idle'||session.nativeState.activeTurnId!==null||app.store.isQuarantined(session.workspaceId)||app.store.runs(session.id).some((r:any)=>['queued','running','cancelling'].includes(r.status)))throw Error('normal_reopened_owner_not_idle');this.active();const token=app.gateway.issueToken(session.id,'codex');try{this.active();}finally{app.gateway.revokeToken(token);}this.rolloutPath=path;this.reopenedBaseline=baseline;}
 private async reopenedState(sessionId:string){const app=this.owned(sessionId);await app.files.assertNoLinks(this.rolloutPath);const before=await lstat(this.rolloutPath!),bytes=await readFile(this.rolloutPath!),after=await lstat(this.rolloutPath!);if(!before.isFile()||before.nlink!==1||before.ino!==after.ino||before.size!==after.size||before.mtimeMs!==after.mtimeMs||sha256(bytes)!==this.reopenedBaseline.stateSha256)throw Error('actual_reopened_rollout_changed');const receiptUtf8=stableJson({source:'normal-store-reopened-rollout',sessionId,nativeThreadId:this.reopenedBaseline.nativeThreadId,stateSha256:sha256(bytes),observedAt:new Date().toISOString(),newNativeLaunch:false});return {...this.reopenedBaseline,stateUtf8:bytes.toString('utf8'),stateSha256:sha256(bytes),receiptUtf8,receiptSha256:sha256(receiptUtf8)};}
 async gatewayObservation(sessionId:string){const app=this.owned(sessionId),native=app.store.getSession(sessionId).nativeState;if(!await app.gateway.confirmSettlement({sessionId})||native.ownership!=='idle'||native.activeTurnId!==null)throw Error('normal_owner_not_settled');const bracket=await app.gateway.observeNoGeneration(sessionId,async()=>null);const row=app.store.db.prepare('SELECT MAX(sequence) AS n FROM h041_gateway_admissions WHERE session_id=?').get(sessionId);if(row?.n===undefined)throw Error('actual_durable_gateway_admission_snapshot_unavailable');const records=app.store.db.prepare('SELECT record FROM h021_gateway_requests WHERE session_id=? ORDER BY rowid').all(sessionId).map((r:any)=>String(r.record));return {source:'owned-normal-gateway-observation',sessionId,ownerId:bracket.proof.ownerId,admissionSequence:Number(row.n??0),outstanding:app.gateway.sessionWork(sessionId),records};}
 async settled(sessionId:string,signal:AbortSignal){signal.throwIfAborted();const app=this.owned(sessionId);if(this.holding)throw Error('normal_capture_already_held');this.holding=true;try{return await app.gateway.observeNoGeneration(sessionId,async()=>{
  const gateway=await this.gatewayObservation(sessionId),session=app.store.getSession(sessionId);if(!this.rolloutPath)throw Error('actual_normal_rollout_unobserved');const collector=new NativeCollector({store:app.store,files:app.files,gateway:app.gateway,guard:{} as any,observer:this.observer,hostPrivate:this.config.hostPrivate,withCaptureHold:async (work:()=>Promise<any>)=>work()});if(this.currentProcess)this.observer.gateway(sessionId,session.nativeSessionId,session.nativeState.lastSettledTurnId??null,true);const state=this.reopenedBaseline&&!this.currentProcess?await this.reopenedState(sessionId):await collector.captureState(sessionId,'normal-product-owned-no-writer');
  const stat=await lstat(app.store.databasePath),inventory=app.store.memory.inventory(sessionId),rows=app.store.db.prepare('SELECT rowid,id,kind,source_key,sha256,bytes,availability FROM h041_originals WHERE session_id=? AND rowid<=? ORDER BY rowid').all(sessionId,inventory.through);if(rows.length>4096||rows.length!==inventory.count||sha256(rows.map((r:any)=>JSON.stringify(r)+'\n').join(''))!==inventory.sha256)throw Error('actual_full_original_inventory');
  const originalInventoryUtf8=stableJson({sessionId,through:inventory.through,count:inventory.count,sha256:inventory.sha256,rows,references:rows.map((r:any)=>app.store.memory.resolve(sessionId,r.id))});const accepted=app.store.db.prepare('SELECT v.body FROM h041_memory_current c JOIN h041_memory_versions v ON v.id=c.version_id AND v.session_id=c.session_id WHERE c.session_id=?').get(sessionId),acceptedStateUtf8=accepted?String(accepted.body):'null';
  const baseline={source:'owned-normal-product-baseline',sessionId,...state,rolloutPath:this.rolloutPath,storeIdentity:{canonicalPath:app.store.databasePath,ino:stat.ino,dev:stat.dev},originalInventoryUtf8,originalInventorySha256:sha256(originalInventoryUtf8),acceptedStateUtf8,acceptedStateSha256:sha256(acceptedStateUtf8),gatewayAdmissionSequence:gateway.admissionSequence};await durableFile(join(this.config.hostPrivate,`${sha256(stableJson(baseline))}-normal-baseline.json`),stableJson(baseline));return baseline;
 }).then(async(value:any)=>{const noGenerationUtf8=stableJson(value.proof),baseline={...value.value,noGenerationUtf8,noGenerationSha256:sha256(noGenerationUtf8)};await durableFile(join(this.config.hostPrivate,`${sha256(stableJson(baseline))}-normal-baseline.json`),stableJson(baseline));return baseline;});}finally{this.holding=false;}}
 async settleRun(sessionId:string,runId:string,signal:AbortSignal){const app=this.owned(sessionId),deadline=reviewedAuthorization(this.config.review).expiresAt;await bounded(new Promise<void>((resolve,reject)=>{const check=()=>{if(signal.aborted)return reject(Error('normal_run_cancelled'));const row=app.store.db.prepare('SELECT status FROM runs WHERE session_id=? AND id=?').get(sessionId,runId);if(!row)return reject(Error('actual_normal_run_absent'));if(['completed','failed','cancelled'].includes(row.status)){resolve();return;}if(Date.now()>=deadline)return reject(Error('normal_settlement_deadline'));setTimeout(check,20);};check();}),Math.max(1,deadline-Date.now()),'normal_run_settlement_timeout');if(await app.gateway.observeSettlement({sessionId},signal)!==true)throw Error('actual_normal_gateway_settlement_false');const state=app.store.getSession(sessionId);if(state.nativeState.ownership!=='idle'||state.nativeState.activeTurnId!==null)throw Error('actual_normal_native_not_idle');this.observer.gateway(sessionId,state.nativeSessionId,state.nativeState.lastSettledTurnId??null,true);const row=app.store.db.prepare('SELECT status FROM runs WHERE session_id=? AND id=?').get(sessionId,runId);const operation=this.observer.operation(sessionId),tracePackets=[...this.traceCaptures.values()].filter(p=>JSON.parse(p.traceReceiptUtf8).events.some((e:any)=>e.turnId===operation.nativeTurnId));for(const packet of tracePackets)await durableFile(join(this.config.hostPrivate,`${runId}-${packet.traceReceiptSha256}-actual-original-trace.json`),stableJson(packet));return {sessionId,runId,nativeThreadId:state.nativeSessionId,nativeOutcome:row.status,settlement:{state:'released'},nativeFramesUtf8:stableJson(this.observer.frames(sessionId)),requests:[...this.captures.values()].filter(c=>c.runId===runId),tracePackets,traceStatus:this.traceFailure?'FAIL':tracePackets.length?'SOURCE_VALID':'NOT_TESTED'};}
 async closeReceipt(sessionId:string){const g=await this.gatewayObservation(sessionId),values=[...this.producers.values()];if(!values.length||values.some(v=>!v.settlementReceiptUtf8))throw Error('normal_close_native_producer_missing');const gatewayObservationUtf8=stableJson(g);return {source:'owned-normal-product-close',sessionId,nativeProducers:values,outstanding:[],gatewayObservationUtf8,gatewayObservationSha256:sha256(gatewayObservationUtf8)};}

 async armVerificationFault(plan:any,baseline:any,signal:AbortSignal){this.active(signal);if(this.fault||plan.kind!=='manual-replacement-verification'||stableJson(plan)!==stableJson(this.config.review.verificationFault)||baseline.sessionId!==this.config.sessionId)throw Error('root_frozen_one_shot_manual_fault_required');const current=await this.settled(this.config.sessionId,signal);if(current.stateUtf8!==baseline.stateUtf8||current.acceptedStateUtf8!==baseline.acceptedStateUtf8||current.originalInventoryUtf8!==baseline.originalInventoryUtf8)throw Error('actual_fault_baseline_changed');this.active(signal);this.fault={plan,baseline,checkpoint:null,consumed:false};}
 beforeNativeReplacementCommit=async(input:any)=>{if(input.sessionId!==this.config.sessionId)return;this.active();const f=this.fault;if(!f||f.consumed)return;const app=this.owned(input.sessionId),run=app.store.db.prepare('SELECT id,kind,status FROM runs WHERE session_id=? AND id=?').get(input.sessionId,input.runId);if(run?.status!=='running'||run.kind!=='compact'||input.checkpoint.sessionId!==input.sessionId||input.checkpoint.runId!==input.runId||input.checkpoint.nativeThreadId!==f.baseline.nativeThreadId||!input.checkpoint.compactions.some((c:any)=>c.status==='completed'))throw Error('fault_requires_actual_owned_completed_compaction');f.consumed=true;f.checkpoint=input.checkpoint;await durableFile(join(this.config.hostPrivate,`${input.checkpoint.id}-actual-negative-only-fault.json`),stableJson({source:'actual-completed-replacement-negative-only-verifier',sessionId:input.sessionId,runId:input.runId,checkpoint:input.checkpoint,beforeBaselineSha256:sha256(stableJson(f.baseline)),planSha256:sha256(stableJson(f.plan))}));this.active();throw Error('root_reviewed_negative_only_replacement_verification_rejected');};
 beforeNativeRecovery=async(input:any,signal:AbortSignal)=>{this.active(signal);if(input.sessionId!==this.config.sessionId||!this.fault?.consumed||input.checkpointId!==this.fault.checkpoint.id)throw Error('exact_owned_fault_recovery_required');};
 onNativeRecoveryObserved=async(input:any,signal:AbortSignal)=>{this.active(signal);if(input.sessionId!==this.config.sessionId||input.checkpointId!==this.fault?.checkpoint.id)throw Error('actual_owned_recovery_observation_scope');const e=input.evidence;if(e.launch.kind!=='launch'||e.settlement.kind!=='settlement'||e.thread.kind!=='thread')throw Error('actual_recovery_observation_types');const launchReceiptUtf8=this.raw(e.launch.receipt),settlementReceiptUtf8=this.raw(e.settlement.receipt);this.observer.gateway(input.sessionId,e.thread.threadId,e.gateway.lastSettledTurnId??null,true);this.recovery={source:'actual-normal-recovery-observed',sessionId:input.sessionId,checkpointId:input.checkpointId,freshProducer:{launchReceiptUtf8,launchReceiptSha256:sha256(launchReceiptUtf8),settlementReceiptUtf8,settlementReceiptSha256:sha256(settlementReceiptUtf8)},nativeFrames:this.observer.frames(input.sessionId),noGeneration:e.noGeneration};await durableFile(join(this.config.hostPrivate,`${input.checkpointId}-actual-recovery-observed.json`),stableJson(this.recovery));this.active(signal);};
 async recoveryCapture(checkpointId:string,signal:AbortSignal){const app=this.owned(this.config.sessionId),f=this.fault;if(!f?.consumed||f.checkpoint.id!==checkpointId)throw Error('actual_armed_fault_checkpoint_missing');const checkpoint=app.store.checkpoints.status(this.config.sessionId).find((r:any)=>r.id===checkpointId),failedRun=app.store.runs(this.config.sessionId).find((r:any)=>r.id===f.checkpoint.runId);if(failedRun?.status!=='failed'||!checkpoint)throw Error('actual_sticky_failed_run_missing');const failedRunUtf8=stableJson(failedRun);if(f.failedRunUtf8&&f.failedRunUtf8!==failedRunUtf8)throw Error('original_failed_run_changed');if(!this.recovery){f.failedRunUtf8=failedRunUtf8;f.checkpoint=checkpoint;}if(!f.failedRunUtf8)throw Error('pre_recovery_failed_run_capture_required');if(!this.recovery)return {nativeOutcome:'failed',failedRunUtf8,beforeBaselineSha256:sha256(stableJson(f.baseline)),checkpointId,sessionId:this.config.sessionId};
  const after=await this.settled(this.config.sessionId,signal),beforeInventory=JSON.parse(f.baseline.originalInventoryUtf8),afterInventory=JSON.parse(after.originalInventoryUtf8),retainedRows=afterInventory.rows.filter((r:any)=>r.rowid<=beforeInventory.through);if(stableJson(retainedRows)!==stableJson(beforeInventory.rows))throw Error('actual_original_prefix_after_recovery_changed');const transitions=app.store.db.prepare('SELECT body FROM h041_checkpoint_transitions WHERE session_id=? AND run_id=?').all(this.config.sessionId,f.checkpoint.runId).map((r:any)=>JSON.parse(String(r.body))),transition=transitions.find((r:any)=>r.kind==='fresh_parent_no_replay');if(!transition)throw Error('actual_fresh_parent_transition_not_applied');const pair=(key:string,value:any)=>{const text=stableJson(value);return {[key+'Utf8']:text,[key+'Sha256']:sha256(text)};},g=await this.gatewayObservation(this.config.sessionId);
  const receipt={source:'owned-normal-product-recovery-v1',sessionId:this.config.sessionId,checkpointId,...pair('beforeBaseline',f.baseline),...pair('afterBaseline',after),...pair('checkpoint',f.checkpoint),failedRunBeforeUtf8:f.failedRunUtf8,failedRunBeforeSha256:sha256(f.failedRunUtf8),...pair('failedRunAfter',failedRun),preservedOriginalRolloutUtf8:f.baseline.stateUtf8,preservedOriginalRolloutSha256:f.baseline.stateSha256,...pair('checkpointOriginalInventory',f.checkpoint.originalInventory),afterCheckpointOriginalInventoryUtf8:stableJson(checkpoint.originalInventory),...pair('afterBaselineOriginalInventory',{...beforeInventory,rows:retainedRows}),freshProducer:this.recovery.freshProducer,...pair('nativeFrames',this.recovery.nativeFrames),...pair('noGeneration',this.recovery.noGeneration),...pair('gatewayObservation',g),...pair('recoveredCheckpoint',checkpoint),...pair('recoveryTransition',transition),replayedActionIds:[]};return {failedRunUtf8,...pair('recoveryReceipt',receipt)};
 }

 prepareAutomatic(plan:any,signal:AbortSignal){this.active(signal);if(stableJson(plan)!==stableJson(this.config.review.automaticPlan))throw Error('root_frozen_automatic_plan_required');return {status:'NOT_TESTED',qualificationSha256:this.qualification.qualificationSha256,planSha256:sha256(stableJson(plan)),sourceSha256:null,resolvedConfigSha256:null,errors:[this.traceFailure?'actual_trace_capture_failed':this.traceCaptures.size?'independently_qualified_protected_config_and_native_clock_causal_bracket_unavailable':'actual_previous_regular_sampling_original_trace_unavailable'],generationAllowed:false};}
 async automaticCapture(runId:string,operationId:string,baseline:any,signal:AbortSignal){signal.throwIfAborted();const sessionId=this.config.sessionId;return collectOrdinaryAutomatic({application:this.application,qualification:this.qualification,observer:this.observer,counts:this.counts,gateway:this.application.gateway,layout:{hostPrivate:this.config.hostPrivate},tracePackets:()=>[...this.traceCaptures.values()],guard:{requests:()=>[...this.captures.values()]},evidence:{parentProducer:()=>{const op=this.observer.operation(sessionId),nonce=JSON.parse([...this.producers.values()].at(-1).launchReceiptUtf8).nonce,p=this.producers.get(nonce);if(!p?.settlementReceiptUtf8||op.sessionId!==sessionId)throw Error('actual_auto_owned_producer_missing');return p;}},withCaptureHold:async (work:()=>Promise<any>)=>{if(this.holding)throw Error('actual_auto_hold_already_active');this.holding=true;try{return await work();}finally{this.holding=false;}}},{sessionId,storeRunId:runId,operationId,baseline,summaryPrefix:this.config.review.automaticPlan.summaryPrefix});}
 nativeEvidence(){return {frames:()=>this.observer.frames(this.config.sessionId),captures:()=>[...this.captures.values()],producers:()=>[...this.producers.values()],counts:this.counts};}
}
export async function startNormalProduct(configPath:string,restart?:import('./normal-restart-ticket.js').NormalRestartTicket){
 const configBytes=await privateFile(configPath),config=reviewSnapshot(JSON.parse(configBytes.toString('utf8'))),a=reviewedAuthorization(config.review);if(restart)assertNormalRestartConfig(restart,config,configBytes);if(process.platform!=='linux'||!process.getuid?.()||config.review.approvedBy!=='root'||config.review.actor!=='worker1'||!identifier(config.sessionId)||Date.now()>=a.dispatchCutoffAt)throw Error('reviewed_actual_normal_product_entry_required');
 
 const qualification=await qualifyEntry(config.qualificationConfig,restart);if(!isQualifiedEntry(qualification))throw Error('actual_current_native_qualification_required');
 const ordinary=loadCodexOrdinaryEntry(config.ordinaryEntryPath,config.ordinaryEntryKeyPath,{serverDir:config.serverDir,deploymentDir:config.deploymentDir});if(!ordinary)throw Error('genuine_protected_normal_data_entry_required');
 const receipt=await loadQwenReceipt(config.qwenReceiptPath),inferenceKey=await readProtectedCredential(config.inferenceKeyPath),controlKey=await readProtectedCredential(config.controlKeyPath),verifyLane=createProductionQwenVerifier(receipt,{inferenceKey,controlKey});
 if(config.review.nativeTrace&&(config.review.nativeTrace.mode!=='post-sampling-token-usage-v1'||typeof (traceApi as any).getCodexTraceEvents!=='function'||typeof (traceApi as any).getCodexTraceUtf8!=='function'))throw Error('actual_reviewed_A_trace_producer_API_unavailable');
 const base:CodexHostQualification={protocolQualified:true,rootlessQualified:true,verifyLane,qualifiedAliases:Object.keys(receipt.lanes),outputLimit:65536,nativeReceiptPolicy:ordinary.nativeReceiptPolicy};
 const producer=new NormalProductProducer(config,qualification);producer.active();const application=await start({beforeNativeRecovery:producer.beforeNativeRecovery,onNativeRecoveryObserved:producer.onNativeRecoveryObserved,beforeNativeReplacementCommit:producer.beforeNativeReplacementCommit,enablePreview:true,qualification:composeCodexProductObservers(base,ordinary,producer.hooks(base)),ordinary,providerDiagnostics:{capture:producer.capture}});try{producer.attach(application);return {application,producer,qualification,config};}catch(error){await application.close();throw error;}
}
export default Object.freeze({enabled:false,capabilities:[],nativeAcceptance:'NOT_TESTED'});
