/** Actual protected browser CDP carrier. Existing browser only; no downloads. */
import {reviewedAuthorization} from '../authorization.mjs';import {projectBrowserNetwork} from './browser-evidence.js';import {sha256,stableJson} from './projection.js';import {durableFile} from './checkpoint.js';import {join} from 'node:path';
export class NormalBrowser {
 private socket:any;private sequence=0;private pending=new Map<number,{resolve(v:any):void;reject(e:any):void}>();private events:any[]=[];private calls:any[]=[];private failure?:Error;
 constructor(readonly config:any){const u=new URL(config.webSocketUrl);if(u.protocol!=='ws:'||u.hostname!=='127.0.0.1'||u.username||u.password||!/^\/devtools\/page\/[a-zA-Z0-9-]+$/.test(u.pathname)||new URL(config.origin).protocol!=='https:')throw Error('reviewed_existing_owned_browser_endpoint_required');}
 private active(signal?:AbortSignal){if(signal?.aborted||this.failure||Date.now()>=reviewedAuthorization(this.config.review).dispatchCutoffAt)throw this.failure??Error('normal_browser_dispatch_cutoff');}
 async connect(signal:AbortSignal){this.active(signal);const Socket=(globalThis as any).WebSocket;if(!Socket)throw Error('actual_installed_node_websocket_required');this.socket=new Socket(this.config.webSocketUrl);await new Promise<void>((resolve,reject)=>{this.socket.addEventListener('open',()=>resolve(),{once:true});this.socket.addEventListener('error',()=>reject(Error('owned_browser_connection_failed')),{once:true});});this.socket.addEventListener('message',(event:any)=>{try{if(typeof event.data!=='string'||Buffer.byteLength(event.data)>32*1024*1024)throw Error('browser_actual_cdp_frame_bound');const value=JSON.parse(event.data);if(value.id!==undefined){const call=this.calls.find(c=>c.id===value.id);if(call)call.responseUtf8=event.data;const p=this.pending.get(value.id);if(p){this.pending.delete(value.id);value.error?p.reject(Error('actual_browser_command_rejected')):p.resolve(value.result);}return;}const projected=projectBrowserNetwork(value.method,value.params,this.config.origin,this.config.sessionId);if(projected)this.events.push(projected);if(['Network.requestWillBeSent','Network.responseReceived'].includes(value.method)){const v=value.params,path=v.request?.url??v.response?.url;if(path&&new URL(path).origin===this.config.origin&&new URL(path).pathname===`/api/sessions/${this.config.sessionId}/memory/accept`)this.events.push({method:value.method,requestId:v.requestId,timestamp:v.timestamp,...(v.request?{path:new URL(path).pathname,requestMethod:v.request.method,postData:v.request.postData}:{status:v.response.status})});}}catch(error){this.failure=error as Error;for(const p of this.pending.values())p.reject(this.failure);this.pending.clear();}});await this.command('Network.enable',{},signal);await this.command('Runtime.enable',{},signal);const location=await this.command('Runtime.evaluate',{expression:'location.origin',returnByValue:true},signal);if(location.result?.value!==this.config.origin)throw Error('actual_protected_browser_origin_mismatch');this.active(signal);}
 async command(method:string,params:any,signal:AbortSignal){this.active(signal);const id=++this.sequence,requestUtf8=JSON.stringify({id,method,params}),call:any={id,requestUtf8,requestSha256:sha256(requestUtf8),observedAtMs:Date.now()};this.calls.push(call);const result=await new Promise<any>((resolve,reject)=>{const finish=()=>{clearTimeout(timer);signal.removeEventListener('abort',cancel);this.pending.delete(id);},cancel=()=>{finish();reject(Error('actual_browser_command_cancelled_no_replay'));},timer=setTimeout(()=>{finish();reject(Error('actual_browser_command_timeout_no_replay'));},10000);this.pending.set(id,{resolve:v=>{finish();resolve(v);},reject:e=>{finish();reject(e);}});signal.addEventListener('abort',cancel,{once:true});try{this.active(signal);this.socket.send(requestUtf8);}catch(error){finish();reject(error);}});this.active(signal);return result;}

 async request(path:string,init:{method:string;bodyUtf8?:string;signal:AbortSignal}){if(!path.startsWith(`/api/sessions/${this.config.sessionId}/`)||path.includes('..')||path.includes('#'))throw Error('normal_browser_owned_route');const expression=`(async()=>{const r=await fetch(${JSON.stringify(path)},{method:${JSON.stringify(init.method)},credentials:'same-origin',cache:'no-store',redirect:'error'${init.bodyUtf8===undefined?'':`,headers:{'content-type':'application/json'},body:${JSON.stringify(init.bodyUtf8)}`}});const t=await r.text();return {status:r.status,text:t}})()`;const v=await this.command('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},init.signal);if(v.exceptionDetails||typeof v.result?.value?.text!=='string')throw Error('actual_protected_browser_fetch_failed');return {status:v.result.value.status,bodyBytes:Buffer.from(v.result.value.text)};}
 async review(sessionId:string,proposalId:string,expectedVersion:string|null,signal:AbortSignal){if(sessionId!==this.config.sessionId)throw Error('foreign_browser_review');const start=this.events.length,firstCall=this.calls.length;const v=await this.command('Runtime.evaluate',{expression:"(()=>{const a=[...document.querySelectorAll('button')].filter(b=>b.textContent?.trim()==='Accept reviewed proposal'&&!b.disabled);if(a.length!==1)throw Error('ambiguous review button');const r=a[0].getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()",returnByValue:true},signal);if(v.exceptionDetails)throw Error('actual_browser_review_button_missing');const {x,y}=v.result.value;await this.command('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'left',clickCount:1},signal);await this.command('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button:'left',clickCount:1},signal);let request:any,response:any;const deadline=Date.now()+10000;while(Date.now()<deadline){this.active(signal);request=this.events.slice(start).find(e=>e.method==='Network.requestWillBeSent'&&e.requestMethod==='POST'&&e.path.endsWith('/memory/accept'));response=request&&this.events.slice(start).find(e=>e.method==='Network.responseReceived'&&e.requestId===request.requestId);if(response)break;await new Promise<void>(r=>setTimeout(r,20));}this.active(signal);if(!request||!response)throw Error('actual_browser_review_network_missing');const body=JSON.parse(request.postData??'null');if(body?.proposalId!==proposalId||body.expectedVersion!==expectedVersion)throw Error('actual_browser_review_other_proposal');const actionReceiptUtf8=stableJson({action:'click',role:'button',name:'Accept reviewed proposal',observedAtMs:Date.now(),cdpCalls:this.calls.slice(firstCall).filter(c=>JSON.parse(c.requestUtf8).method==='Input.dispatchMouseEvent')}),receiptUtf8=stableJson({source:'owned-protected-browser-memory-review',sessionId,requestId:request.requestId,responseRequestId:response.requestId,requestPath:request.path,requestBodyUtf8:request.postData,method:request.requestMethod,status:response.status,actionReceiptUtf8});await durableFile(join(this.config.hostPrivate,`${sha256(receiptUtf8)}-browser-human.json`),receiptUtf8);return {receiptUtf8};}
 close(){this.socket?.close();for(const p of this.pending.values())p.reject(Error('actual_browser_carrier_closed'));this.pending.clear();}
}
export default Object.freeze({enabled:false,capabilities:[],nativeAcceptance:'NOT_TESTED'});
