/** Actual normal main.start composition. Never imports/calls temporary bootstrap. */
import {composeCodexProductObservers} from '../../../server/src/codex-product-observation.js';
import {start} from '../../../server/src/main.js';
import {loadCodexOrdinaryEntry} from '../../../server/src/codex-ordinary-entry.js';
import {createProductionQwenVerifier,loadQwenReceipt} from '../../../server/src/codex-production.js';
import {readProtectedCredential} from '../../../server/src/protected-credential.js';
import {getCodexReceiptUtf8} from '../../../server/src/codex-receipts.js';
import {translateResponses} from '../../../server/src/codex-responses.js';
import type {CodexHostQualification} from '../../../server/src/codex-host.js';
import type {GatewayOptions} from '../../../server/src/gateway.js';
import {NativeObserver} from './native-observer.js';
import {NativeCountObserver} from './count-observer.js';
import {NativeCollector} from './collector.js';
import {privateFile,durableFile} from './checkpoint.js';
import {sha256,stableJson,reviewSnapshot,identifier} from './projection.js';
import {qualifyEntry,isQualifiedEntry,type EntryQualification} from './qualification.js';
import {reviewedAuthorization} from '../authorization.mjs';
import {lstat,readFile} from 'node:fs/promises';import {join,dirname} from 'node:path';
import {bounded} from './process-runner.js';
export async function kernelProcessReceipt(pid=process.pid){if(process.platform!=='linux')throw Error('native_normal_process_requires_linux_kernel');const procStatUtf8=await readFile(`/proc/${pid}/stat`,'utf8'),bootIdUtf8=await readFile('/proc/sys/kernel/random/boot_id','utf8'),fields=procStatUtf8.slice(procStatUtf8.lastIndexOf(') ')+2).trim().split(/\s+/);return {source:'linux-proc-process-observation',pid,startTicks:fields[19],bootId:bootIdUtf8.trim(),procStatUtf8,bootIdUtf8};}
export class NormalProductProducer {
 readonly observer:NativeObserver;readonly counts:NativeCountObserver;
 private captureFailure?:Error;private application:any;private captures=new Map<string,any>();private producers=new Map<string,any>();private rolloutPath?:string;private currentProcess?:object;private holding=false;private reopenedBaseline?:any;
 constructor(readonly config:any,readonly qualification:EntryQualification){this.observer=new NativeObserver(config.hostPrivate);this.counts=new NativeCountObserver(config.hostPrivate);}
 active(signal?:AbortSignal){if(signal?.aborted||Date.now()>=reviewedAuthorization(this.config.review).dispatchCutoffAt)throw Error('normal_product_dispatch_cutoff');}
 attach(application:any){if(this.application||!application.gateway||application.store.databasePath!==join(this.config.dataDir,'harness.sqlite'))throw Error('actual_normal_application_gateway_unavailable');this.application=application;}
 private owned(id:string){if(id!==this.config.sessionId)throw Error('normal_producer_foreign_session');return this.application;}
 private raw(r:any){const bytes=getCodexReceiptUtf8(r);if(!bytes)throw Error('actual_current_transport_receipt_required');return bytes;}
 capture:NonNullable<GatewayOptions['diagnostics']>['capture']=event=>{if(event.sessionId!==this.config.sessionId)return;try{if(this.captureFailure)throw this.captureFailure;if(event.phase==='pre_normalization'){if(this.captures.has(event.requestId))throw Error('normal_capture_duplicate');const bytes=Buffer.from(event.bytes),raw=bytes.toString('utf8');if(!Buffer.from(raw).equals(bytes))throw Error('normal_capture_invalid_utf8');this.captures.set(event.requestId,{requestId:event.requestId,sessionId:event.sessionId,firstRequestUtf8:raw,captureSha256:sha256(raw),observedAt:new Date().toISOString()});}else if(event.phase==='normalized_request'){const c=this.captures.get(event.requestId);if(!c?.normalizedRequestUtf8||c.normalizedRequestUtf8!==Buffer.from(event.bytes).toString('utf8'))throw Error('normal_actual_gateway_normalization_changed');}}catch(error){this.captureFailure=error instanceof Error?error:Error('normal_capture_failed');throw this.captureFailure;}};

 hooks(base:CodexHostQualification):CodexHostQualification{
  return {...base,
   observations:{onNativeProcess:(event:any)=>{if(event.sessionId===this.config.sessionId){if(this.holding)throw Error('normal_owned_capture_blocks_new_launch');this.currentProcess=event.process;this.observer.registerObserved(event.sessionId,event.process);}},onRawNative:(event:any)=>{if(event.sessionId===this.config.sessionId)this.observer.ingestObserved(event);},onVerifiedCount:async(event:any,signal:AbortSignal)=>{
    const c=this.captures.get(event.context?.requestId);if(this.captureFailure)throw this.captureFailure;if(!c)throw Error('normal_owned_count_raw_capture_missing');this.active(signal);const app=this.owned(c.sessionId),runs=app.store.db.prepare("SELECT id,kind FROM runs WHERE session_id=? AND status='running'").all(c.sessionId);if(this.holding||runs.length!==1)throw Error('actual_unique_normal_store_run_required');const raw=JSON.parse(c.firstRequestUtf8),m=JSON.parse(raw.client_metadata?.['x-codex-turn-metadata']??'null'),translated={...translateResponses(raw).body,model:event.lane};if(!m||m.thread_id!==app.store.getSession(c.sessionId).nativeSessionId||typeof m.turn_id!=='string'||stableJson(translated)!==stableJson(event.body)||sha256(JSON.stringify(event.body))!==event.bodySha256)throw Error('normal_compiled_request_actual_owner_translation');const policy=this.config.review.normalToolPolicies?.[m.request_kind==='compaction'?'compaction':'parent'];if(!policy||sha256(stableJson(raw.tools))!==policy.rawToolsSha256||sha256(stableJson(event.body.tools))!==policy.translatedToolsSha256)throw Error('normal_reviewed_distinct_tool_policy_before_dispatch');Object.assign(c,{runId:String(runs[0].id),nativeThreadId:m.thread_id,nativeTurnId:m.turn_id,normalizedRequestUtf8:JSON.stringify(event.body),normalizedSha256:event.bodySha256});await durableFile(join(this.config.hostPrivate,`${c.requestId}-normal-provider-capture.json`),stableJson(c));await this.counts.retainVerifiedEvent(event,signal);this.active(signal);
   }},
   beforeNativeAction:async input=>{await base.beforeNativeAction?.(input);if(input.sessionId===this.config.sessionId)this.active();if(input.sessionId===this.config.sessionId&&this.holding)throw Error('normal_capture_blocks_native_mutation');},
   onNativeLaunchReceipt:r=>{base.onNativeLaunchReceipt?.(r);if(r.sessionId===this.config.sessionId)this.producers.set(r.nonce,{launchReceiptUtf8:this.raw(r),launchReceiptSha256:sha256(this.raw(r))});},
   onNativeThread:async input=>{await base.onNativeThread?.(input);if(input.sessionId===this.config.sessionId){if(!input.rolloutPath)throw Error('actual_normal_rollout_path_missing');this.rolloutPath=input.rolloutPath;await durableFile(join(this.config.hostPrivate,`${input.launchReceipt.nonce}-normal-thread.json`),stableJson({source:'actual-normal-native-thread',sessionId:input.sessionId,threadId:input.threadId,rolloutPath:input.rolloutPath,method:input.method,observedSettings:input.observedSettings}));}},
   onNativeSettlementReceipt:r=>{base.onNativeSettlementReceipt?.(r);if(r.sessionId===this.config.sessionId){const p=this.producers.get(r.nonce);if(!p)throw Error('normal_settlement_without_actual_launch');p.settlementReceiptUtf8=this.raw(r);p.settlementReceiptSha256=sha256(p.settlementReceiptUtf8);if(!this.currentProcess||!r.cleanupOk)throw Error('actual_normal_cleanup_missing');this.observer.cleanupObserved(this.currentProcess);}},
  } as CodexHostQualification;
 }
 async reopenBaseline(baseline:any){const app=this.owned(baseline.sessionId);if(this.rolloutPath||baseline.nativeThreadId!==app.store.getSession(baseline.sessionId).nativeSessionId||sha256(baseline.stateUtf8)!==baseline.stateSha256)throw Error('normal_reopen_exact_accepted_parent_required');const path=baseline.rolloutPath;if(typeof path!=='string'||!path.startsWith(app.files.profile(baseline.sessionId)+'/')||sha256(await readFile(path))!==baseline.stateSha256)throw Error('normal_reopen_protected_rollout_changed');await app.files.assertNoLinks(path);const session=app.store.getSession(baseline.sessionId);if(session.nativeState.ownership!=='idle'||session.nativeState.activeTurnId!==null||app.store.isQuarantined(session.workspaceId)||app.store.runs(session.id).some((r:any)=>['queued','running','cancelling'].includes(r.status)))throw Error('normal_reopened_owner_not_idle');this.active();const token=app.gateway.issueToken(session.id,'codex');try{this.active();}finally{app.gateway.revokeToken(token);}this.rolloutPath=path;this.reopenedBaseline=baseline;}
 private async reopenedState(sessionId:string){const app=this.owned(sessionId);await app.files.assertNoLinks(this.rolloutPath);const before=await lstat(this.rolloutPath!),bytes=await readFile(this.rolloutPath!),after=await lstat(this.rolloutPath!);if(!before.isFile()||before.nlink!==1||before.ino!==after.ino||before.size!==after.size||before.mtimeMs!==after.mtimeMs||sha256(bytes)!==this.reopenedBaseline.stateSha256)throw Error('actual_reopened_rollout_changed');const receiptUtf8=stableJson({source:'normal-store-reopened-rollout',sessionId,nativeThreadId:this.reopenedBaseline.nativeThreadId,stateSha256:sha256(bytes),observedAt:new Date().toISOString(),newNativeLaunch:false});return {...this.reopenedBaseline,stateUtf8:bytes.toString('utf8'),stateSha256:sha256(bytes),receiptUtf8,receiptSha256:sha256(receiptUtf8)};}
 async gatewayObservation(sessionId:string){const app=this.owned(sessionId),native=app.store.getSession(sessionId).nativeState;if(!await app.gateway.confirmSettlement({sessionId})||native.ownership!=='idle'||native.activeTurnId!==null)throw Error('normal_owner_not_settled');const bracket=await app.gateway.observeNoGeneration(sessionId,async()=>null);const row=app.store.db.prepare('SELECT MAX(sequence) AS n FROM h041_gateway_admissions WHERE session_id=?').get(sessionId);if(row?.n===undefined)throw Error('actual_durable_gateway_admission_snapshot_unavailable');const records=app.store.db.prepare('SELECT record FROM h021_gateway_requests WHERE session_id=? ORDER BY rowid').all(sessionId).map((r:any)=>String(r.record));return {source:'owned-normal-gateway-observation',sessionId,ownerId:bracket.proof.ownerId,admissionSequence:Number(row.n??0),outstanding:app.gateway.sessionWork(sessionId),records};}
 async settled(sessionId:string,signal:AbortSignal){signal.throwIfAborted();const app=this.owned(sessionId);if(this.holding)throw Error('normal_capture_already_held');this.holding=true;try{return await app.gateway.observeNoGeneration(sessionId,async()=>{
  const gateway=await this.gatewayObservation(sessionId),session=app.store.getSession(sessionId);if(!this.rolloutPath)throw Error('actual_normal_rollout_unobserved');const collector=new NativeCollector({store:app.store,files:app.files,gateway:app.gateway,guard:{} as any,observer:this.observer,hostPrivate:this.config.hostPrivate,withCaptureHold:async work=>work()});if(this.currentProcess)this.observer.gateway(sessionId,session.nativeSessionId,session.nativeState.lastSettledTurnId??null,true);const state=this.reopenedBaseline&&!this.currentProcess?await this.reopenedState(sessionId):await collector.captureState(sessionId,'normal-product-owned-no-writer');
  const stat=await lstat(app.store.databasePath),inventory=app.store.memory.inventory(sessionId),rows=app.store.db.prepare('SELECT rowid,id,kind,source_key,sha256,bytes,availability FROM h041_originals WHERE session_id=? AND rowid<=? ORDER BY rowid').all(sessionId,inventory.through);if(rows.length>4096||rows.length!==inventory.count||sha256(rows.map((r:any)=>JSON.stringify(r)+'\n').join(''))!==inventory.sha256)throw Error('actual_full_original_inventory');
  const originalInventoryUtf8=stableJson({sessionId,through:inventory.through,count:inventory.count,sha256:inventory.sha256,rows,references:rows.map((r:any)=>app.store.memory.resolve(sessionId,r.id))});const accepted=app.store.db.prepare('SELECT v.body FROM h041_memory_current c JOIN h041_memory_versions v ON v.id=c.version_id AND v.session_id=c.session_id WHERE c.session_id=?').get(sessionId),acceptedStateUtf8=accepted?String(accepted.body):'null';
  const baseline={source:'owned-normal-product-baseline',sessionId,...state,rolloutPath:this.rolloutPath,storeIdentity:{canonicalPath:app.store.databasePath,ino:stat.ino,dev:stat.dev},originalInventoryUtf8,originalInventorySha256:sha256(originalInventoryUtf8),acceptedStateUtf8,acceptedStateSha256:sha256(acceptedStateUtf8),gatewayAdmissionSequence:gateway.admissionSequence};await durableFile(join(this.config.hostPrivate,`${sha256(stableJson(baseline))}-normal-baseline.json`),stableJson(baseline));return baseline;
 }).then(async(value:any)=>{const noGenerationUtf8=stableJson(value.proof),baseline={...value.value,noGenerationUtf8,noGenerationSha256:sha256(noGenerationUtf8)};await durableFile(join(this.config.hostPrivate,`${sha256(stableJson(baseline))}-normal-baseline.json`),stableJson(baseline));return baseline;});}finally{this.holding=false;}}
 async settleRun(sessionId:string,runId:string,signal:AbortSignal){const app=this.owned(sessionId),deadline=reviewedAuthorization(this.config.review).expiresAt;await bounded(new Promise<void>((resolve,reject)=>{const check=()=>{if(signal.aborted)return reject(Error('normal_run_cancelled'));const row=app.store.db.prepare('SELECT status FROM runs WHERE session_id=? AND id=?').get(sessionId,runId);if(!row)return reject(Error('actual_normal_run_absent'));if(['completed','failed','cancelled'].includes(row.status)){resolve();return;}if(Date.now()>=deadline)return reject(Error('normal_settlement_deadline'));setTimeout(check,20);};check();}),Math.max(1,deadline-Date.now()),'normal_run_settlement_timeout');if(await app.gateway.observeSettlement({sessionId},signal)!==true)throw Error('actual_normal_gateway_settlement_false');const state=app.store.getSession(sessionId);if(state.nativeState.ownership!=='idle'||state.nativeState.activeTurnId!==null)throw Error('actual_normal_native_not_idle');this.observer.gateway(sessionId,state.nativeSessionId,state.nativeState.lastSettledTurnId??null,true);const row=app.store.db.prepare('SELECT status FROM runs WHERE session_id=? AND id=?').get(sessionId,runId);return {sessionId,runId,nativeThreadId:state.nativeSessionId,nativeOutcome:row.status,settlement:{state:'released'},nativeFramesUtf8:stableJson(this.observer.frames(sessionId)),requests:[...this.captures.values()].filter(c=>c.runId===runId)};}
 async closeReceipt(sessionId:string){const g=await this.gatewayObservation(sessionId),values=[...this.producers.values()];if(!values.length||values.some(v=>!v.settlementReceiptUtf8))throw Error('normal_close_native_producer_missing');const gatewayObservationUtf8=stableJson(g);return {source:'owned-normal-product-close',sessionId,nativeProducers:values,outstanding:[],gatewayObservationUtf8,gatewayObservationSha256:sha256(gatewayObservationUtf8)};}
 nativeEvidence(){return {frames:()=>this.observer.frames(this.config.sessionId),captures:()=>[...this.captures.values()],producers:()=>[...this.producers.values()],counts:this.counts};}
}
export async function startNormalProduct(configPath:string){
 const config=reviewSnapshot(JSON.parse((await privateFile(configPath)).toString('utf8'))),a=reviewedAuthorization(config.review);if(process.platform!=='linux'||!process.getuid?.()||config.review.approvedBy!=='root'||config.review.actor!=='worker1'||!identifier(config.sessionId)||Date.now()>=a.dispatchCutoffAt)throw Error('reviewed_actual_normal_product_entry_required');
 
 const qualification=await qualifyEntry(config.qualificationConfig);if(!isQualifiedEntry(qualification))throw Error('actual_current_native_qualification_required');
 const ordinary=loadCodexOrdinaryEntry(config.ordinaryEntryPath,config.ordinaryEntryKeyPath,{serverDir:config.serverDir,deploymentDir:config.deploymentDir});if(!ordinary)throw Error('genuine_protected_normal_data_entry_required');
 const receipt=await loadQwenReceipt(config.qwenReceiptPath),inferenceKey=await readProtectedCredential(config.inferenceKeyPath),controlKey=await readProtectedCredential(config.controlKeyPath),verifyLane=createProductionQwenVerifier(receipt,{inferenceKey,controlKey});
 const base:CodexHostQualification={protocolQualified:true,rootlessQualified:true,verifyLane,qualifiedAliases:Object.keys(receipt.lanes),outputLimit:65536,nativeReceiptPolicy:ordinary.nativeReceiptPolicy};
 const producer=new NormalProductProducer(config,qualification);producer.active();const application=await start({enablePreview:true,qualification:composeCodexProductObservers(base,ordinary,producer.hooks(base)),ordinary,providerDiagnostics:{capture:producer.capture}});try{producer.attach(application);return {application,producer,qualification,config};}catch(error){await application.close();throw error;}
}
export default Object.freeze({enabled:false,capabilities:[],nativeAcceptance:'NOT_TESTED'});
