/** Owned whole normal application restart, independently checked raw receipts. */
import {OwnedApplicationRunner,type RunnerInput} from './process-runner.js';
import {sha256,stableJson} from './projection.js';import {durableFile} from './checkpoint.js';
import {verifyNormalRestart} from '../ordinary-proof.mjs';import {join} from 'node:path';
const pair=(key:string,value:any)=>{const text=stableJson(value);return {[key+'Utf8']:text,[key+'Sha256']:sha256(text)};};
export class NormalApplicationRunner {
 private runner:OwnedApplicationRunner;private ready:any;private restarted=false;
 constructor(readonly input:RunnerInput,readonly expected:any){this.runner=new OwnedApplicationRunner(input);}
 async start(signal:AbortSignal){await this.runner.start(signal);this.ready=await this.runner.call('readyReceipt',{},signal);if(this.ready.configSha256!==this.input.configSha256||this.ready.workerSha256!==this.input.workerSha256)throw Error('actual_normal_worker_source_closure');}
 call(method:string,args:any,signal?:AbortSignal){return this.runner.call(method,args,signal);}
 async restart(sessionId:string,baseline:any,signal:AbortSignal){if(this.restarted||sessionId!==this.expected.sessionId)throw Error('normal_restart_single_owned_budget');this.restarted=true;const before=await this.runner.call('baseline',{},signal);if(before.nativeThreadId!==baseline.nativeThreadId||before.stateUtf8!==baseline.stateUtf8||before.originalInventoryUtf8!==baseline.originalInventoryUtf8||before.acceptedStateUtf8!==baseline.acceptedStateUtf8||stableJson(before.storeIdentity)!==stableJson(baseline.storeIdentity))throw Error('normal_restart_accepted_baseline_changed');const oldReady=this.ready,oldClose=await this.runner.call('closeReceipt',{},signal),exit=await this.runner.shutdownAndConfirm();if(exit.code!==0||exit.signal!==null)throw Error('actual_normal_old_application_exit_required');const kernel=JSON.parse(oldReady.kernelUtf8),oldExit={source:'owned-node-subprocess-exit',process:{pid:kernel.pid,startTicks:kernel.startTicks,bootId:kernel.bootId},...exit,observedAt:new Date().toISOString()};const adoption={source:'owned-normal-process-adoption',candidateCommit:this.expected.candidateCommit,windowId:this.expected.windowId,qualificationSha256:this.expected.qualificationSha256,configSha256:this.input.configSha256,workerSha256:this.input.workerSha256,baseline:before,oldReady,oldExit,oldClose},adoptionBytes=stableJson(adoption),adoptionPath=join(this.input.hostPrivate,sha256(adoptionBytes)+'-normal-adoption.json');await durableFile(adoptionPath,adoptionBytes);this.runner=new OwnedApplicationRunner(this.input);await this.runner.start(signal);await this.runner.call('adoptNormalRestart',{path:adoptionPath,sha256:sha256(adoptionBytes)},signal);this.ready=await this.runner.call('readyReceipt',{},signal);if(this.ready.configSha256!==this.input.configSha256||this.ready.workerSha256!==this.input.workerSha256)throw Error('actual_normal_reopened_worker_source_closure');await this.runner.call('reopenBaseline',{baseline:before},signal);const after=await this.runner.call('baseline',{},signal),receipt={source:'owned-normal-product-restart-v1',sessionId,candidateCommit:this.expected.candidateCommit,windowId:this.expected.windowId,...pair('beforeBaseline',baseline),...pair('afterBaseline',after),...pair('oldReady',oldReady),...pair('newReady',this.ready),...pair('oldExit',oldExit),...pair('oldClose',oldClose),replayedActionIds:[]},observation=pair('restartReceipt',receipt),verification=verifyNormalRestart(observation,{...this.expected,workerSha256:this.input.workerSha256,configSha256:this.input.configSha256,beforeBaselineSha256:sha256(stableJson(baseline))});await durableFile(join(this.input.hostPrivate,`${observation.restartReceiptSha256}-normal-restart.json`),stableJson({observation,verification}));if(verification.status!=='SOURCE_VALID')throw Error('normal_restart_independent_verification_failed');return {...observation,verification};}
 shutdown(){return this.runner.shutdownAndConfirm();}
}
export default Object.freeze({enabled:false,capabilities:[],nativeAcceptance:'NOT_TESTED'});
