/** Synthetic source fixture. Does not qualify Linux transport or native isolation. */
import { validateCodexLaunchReceipt, validateCodexSettlementReceipt, CODEX_RECEIPT_SOURCES, type CodexReceiptBinding } from '../../src/codex-receipts.js';
export function receiptFixture() {
 const now=Date.now(), prefix='user.slice/user-1000.slice/user@1000.service/aiharnesstasks.slice';
 const binding: CodexReceiptBinding={nonce:'a'.repeat(64),runId:'probe-run',sessionId:'session-1',startedAtMs:now-100,uid:1000,gid:1000,deploymentDir:'/trusted/deploy',imageJobsQualified:false,profileDir:'/task/profile',workspace:'/task/workspace',sources:Object.fromEntries(CODEX_RECEIPT_SOURCES.map(k=>[k,'b'.repeat(64)]))};
 const producer={pid:300,startTicks:'1234',uid:1000,bootId:'00000000-0000-0000-0000-000000000001',cgroupPath:'/'+prefix+'/test.scope'};
 const ro=(source:string,destination:string)=>({source,destination,rw:false,type:'bind'});
 const mounts=[{source:'/task/profile',destination:'/task/profile',rw:true,type:'bind'},{source:'/task/workspace',destination:'/task/workspace',rw:true,type:'bind'},ro('/trusted/tools/image/image-mcp.mjs','/opt/ai-harness/tools/image/image-mcp.mjs'),ro('/trusted/tools/image/image.mjs','/opt/ai-harness/tools/image/image.mjs'),ro('/trusted/deploy/codex/config.toml','/task/profile/codex-home/config.toml'),ro('/trusted/deploy/codex/models.json','/opt/sova/codex/models.json'),ro('/trusted/deploy/codex/skills/sova-local-tools','/task/profile/codex-home/skills/sova-local-tools')];
 const rawLaunch={schema:'codex-launch-v1',nonce:binding.nonce,runId:binding.runId,sessionId:binding.sessionId,checkedAtMs:now,producer,sources:binding.sources,egress:{bootId:producer.bootId,uid:1000,cgroupPath:prefix,cgroupInode:23,nftSha256:'c'.repeat(64),checkedBoottime:120,receiptSha256:'d'.repeat(64)},container:{id:'e'.repeat(64),name:'ai-harness-'+'f'.repeat(32),imageId:'sha256:d8841743002e16de1f9269a850a2f06a73055688befec4c309778ca8a4c11aad',imageRevision:'064c6b8c737f5b41d171fdda80bd9ef10ad06eb3',imagePatchset:'dd0ff12a651db4cc8521cddb8e5094c5a197ca87cef6b7ec797343da67d9f1ec',pid:400,pidStartTicks:'1240',rootless:true,user:'1000:1000',network:'slirp4netns:allow_host_loopback=true',capDrop:['ALL'],securityOpt:['no-new-privileges','seccomp=/trusted/deploy/security/chromium-seccomp.json'],readOnly:true,privileged:false,mounts,additionalMounts:[],workdir:binding.workspace,profileDir:binding.profileDir,workspace:binding.workspace}};
 const launch=validateCodexLaunchReceipt(structuredClone(rawLaunch),binding,producer,now);
 const rawSettlement={schema:'codex-settlement-v1',nonce:binding.nonce,runId:binding.runId,sessionId:binding.sessionId,checkedAtMs:now+1,producer,containerName:launch.container.name,containerId:launch.container.id,engineExitStatus:-15,requestedStop:true,cliReaped:true,rmExit:0,existsExit:1,pipesJoined:true,cleanupOk:true};
 const settlement=validateCodexSettlementReceipt(structuredClone(rawSettlement),binding,launch,now+1);
 return {binding,producer,now,rawLaunch,rawSettlement,launch,settlement};
}
