import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,readdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {cases,taskText,prepare,validateGo,runOne,runBatch} from './h021-matched-acceptance.mjs';
const source='9ee552dcc8fd5086c97d47eea33828c8e0cf15c5';
const readback=Buffer.from('fixture operator readback; no actual deployment');
const go=path=>({schema:'h021-matched-batch-go-v1',exactSource:source,origin:'http://127.0.0.1:19876',scope:'Sova API matched batch',model:'qwen3.8-27b',lane:'Qwen0',context:480000,outputCap:1024,retryCount:0,sharedAdmission:true,previousOwnerSettled:true,protocolQualified:true,nativeCli:'0.158.0',imageDigest:'a'.repeat(64),profileSha256:'b'.repeat(64),readbackSha256:createHash('sha256').update(readback).digest('hex'),pilotId:'offline-fixture',laneOwner:'fixture',coordinator:'fixture',readbackPath:path,expiresUtc:new Date(Date.now()+60000).toISOString(),engine:'codex',caseId:'python-boundary',schedule:[{engine:'codex',caseId:'python-boundary'}]});
const response=value=>new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}});
async function setup(t){const root=await mkdtemp(join(tmpdir(),'h021-accept-runner-'));t.after(()=>rm(root,{recursive:true,force:true}));const receipt=join(root,'readback.json');await writeFile(receipt,readback);const inputs=join(root,'inputs');await prepare(inputs);return {root,inputs,g:go(receipt)};}
test('preparation excludes private answers, reference solutions and image case',async t=>{const {inputs}=await setup(t);assert.deepEqual((await readdir(join(inputs,'python-boundary'))).sort(),['bins.py','test_bins.py']);assert.deepEqual(await readdir(join(inputs,'pdf-units')),[]);const text=taskText(cases.find(c=>c.id==='pdf-units'));assert(!/250|3\.3|0\.25|write_pdf|test_pdf_tools/.test(text));assert(!cases.some(c=>c.id==='image-specialist'));});
test('exact GO rejects mismatched source, stale grant, wrong lane/cap and unsettled owner',()=>{const base=go('/unused');for(const patch of [{exactSource:'f'.repeat(40)},{expiresUtc:'2020-01-01'},{lane:'MiMo'},{outputCap:65536},{previousOwnerSettled:false},{sharedAdmission:false},{retryCount:1},{origin:'http://user:password@localhost'}])assert.throws(()=>validateGo({...base,...patch},source));});
test('no fetch occurs before readback digest verification',async t=>{const {root,inputs,g}=await setup(t);let calls=0;await assert.rejects(runOne({...g,readbackSha256:'f'.repeat(64)},inputs,join(root,'run'),{source,fetcher:()=>{calls++;throw Error('unexpected')}}));assert.equal(calls,0);});
async function fakeApi(inputs,fail){const calls=[];const uploadBytes=[];let messages=0;const snapshot={session:{engineKind:'codex',status:'idle'},runs:[{id:'r1',status:'completed'}],messages:[{id:'m1',content:'done'}],events:[],activities:[],artifacts:[]};return {calls,get messages(){return messages},fetcher:async(url,options)=>{const path=new URL(url).pathname;calls.push([options.method??'GET',path]);if(path==='/api/health')return response({engines:{default:'minimax',codex:{available:true,protocolQualified:true}}});if(path==='/api/sessions')return response({session:{id:'s1',engineKind:'codex'}});if(path.endsWith('/uploads')){const file=options.body.get('file');uploadBytes.push(Buffer.from(await file.arrayBuffer()));return response({attachment:{id:String(uploadBytes.length)}});}if(path.startsWith('/api/attachments/'))return new Response(uploadBytes[Number(path.split('/')[3])-1]);if(path.endsWith('/messages')){messages++;if(fail)throw Error('lost response after accepted dispatch');return response({runId:'r1'});}return response(snapshot);}};}
test('accepted then disconnected prompt is never replayed and durable intent remains',async t=>{const {root,inputs,g}=await setup(t);const api=await fakeApi(inputs,true),out=join(root,'run');const result=await runOne(g,inputs,out,{source,fetcher:api.fetcher,wait:async()=>{}});assert.equal(api.messages,1);assert.equal(result.verdict,'BLOCKED_OR_UNCERTAIN');assert.equal(result.retryCount,0);assert.equal(JSON.parse(await readFile(join(out,'DISPATCH-INTENT.json'))).sessionId,'s1');assert.match(result.settlement,/AUTHORITATIVE/);});
test('terminal application readback remains pending independent correctness and central settlement',async t=>{const {root,inputs,g}=await setup(t);const api=await fakeApi(inputs,false),out=join(root,'run');const result=await runOne(g,inputs,out,{source,fetcher:api.fetcher,wait:async()=>{}});assert.equal(api.messages,1);assert.equal(api.calls.filter(([method,path])=>method==='GET'&&path==='/api/sessions/s1').length,2);assert.equal(result.verdict,'PENDING_INDEPENDENT_CHECK');assert.equal(result.inputTokens,null);assert.equal(result.outputTokens,null);assert(result.settlement.includes('AUTHORITATIVE'));await assert.rejects(runOne(g,inputs,out,{source,fetcher:api.fetcher}));assert.equal(api.messages,1);});
test('prepared input has no prebuilt binary or answer key',async t=>{const {inputs}=await setup(t);assert.deepEqual((await readdir(join(inputs,'cpp-bounds'))).sort(),['prefix.hpp','test_prefix.cpp']);assert.deepEqual((await readdir(join(inputs,'node-async-validation'))).sort(),['load.mjs','test_load.mjs']);});

test('batch refuses missing host hook before any HTTP',async t=>{const {root,inputs,g}=await setup(t);let calls=0;await assert.rejects(runBatch(g,inputs,join(root,'batch'),{source,fetcher:async()=>{calls++;}}));assert.equal(calls,0);});
test('batch never advances after unconfirmed authoritative settlement',async t=>{const {root,inputs,g}=await setup(t);g.schedule.push({engine:'codex',caseId:'node-async-validation'});const api=await fakeApi(inputs,false);const result=await runBatch(g,inputs,join(root,'batch'),{source,fetcher:api.fetcher,wait:async()=>{},confirmSettlement:async q=>({sessionId:q.sessionId,settled:false})});assert.equal(result.status,'BLOCKED');assert.equal(api.messages,1);assert.equal(result.results.length,1);});
test('one grant advances sequentially only after authoritative settlement',async t=>{const {root,inputs,g}=await setup(t);g.schedule.push({engine:'codex',caseId:'node-async-validation'});const api=await fakeApi(inputs,false);let settles=0;const result=await runBatch(g,inputs,join(root,'batch'),{source,fetcher:api.fetcher,wait:async()=>{},confirmSettlement:async q=>{assert.equal(api.messages,++settles);return {sessionId:q.sessionId,settled:true,evidence:'OFFLINE FIXTURE ONLY'};}});assert.equal(api.messages,2);assert.equal(settles,2);assert.equal(result.status,'PENDING_INDEPENDENT_CHECKS');});
