import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import path from 'node:path';
import {readFile} from 'node:fs/promises';
// Exact helper source with explicit fake HTTP responses; no Linux import shims.
const source=await readFile(new URL('../codex/browser-mcp.mjs',import.meta.url),'utf8');
const text=source.slice(source.indexOf('export async function downloadResponse'),source.indexOf('const root='));
const downloadResponse=vm.runInNewContext(text.replace('export ','')+';downloadResponse',{Date,URL,path,publicURL:()=>{throw Error('explicit fixture policy required');}});
function fixture(responses){const calls=[],disposed=[];return {calls,disposed,context:{request:{async get(url,options){const i=calls.length;calls.push({url,options});const r=responses[i];return {status:()=>r.status,headers:()=>r.headers??{},body:async()=>r.body??Buffer.from('test'),dispose:async()=>disposed.push(i)};}}}};}
test('inline PDF bytes are accepted without a page download event',async()=>{const f=fixture([{status:200,headers:{'content-type':'application/pdf'},body:Buffer.from('%PDF-1.7 fixture')}]);const r=await downloadResponse(f.context,'https://example.com/inline.pdf',async u=>u);assert.equal(r.suggestedName,'inline.pdf');assert.equal(r.bytes.subarray(0,5).toString(),'%PDF-');assert.equal(f.calls[0].options.maxRedirects,0);assert(f.calls[0].options.timeout<=20000);assert.deepEqual(f.disposed,[0]);});
test('every redirect is validated before fetch and blocked private target is never requested',async()=>{const f=fixture([{status:302,headers:{location:'http://127.0.0.1:8081/v1'}}]);const checked=[];await assert.rejects(downloadResponse(f.context,'https://example.com/start',async u=>{checked.push(u);if(u.includes('127.0.0.1'))throw Error('private target');return u;}),/private target/);assert.equal(f.calls.length,1);assert.equal(checked.length,2);assert.deepEqual(f.disposed,[0]);});
test('relative redirects preserve final URL and bounded manual redirect count',async()=>{const f=fixture([{status:302,headers:{location:'/final.pdf'}},{status:200}]);const checked=[];const r=await downloadResponse(f.context,'https://example.com/start',async u=>(checked.push(u),u));assert.equal(r.url,'https://example.com/final.pdf');assert.equal(checked.length,2);assert.deepEqual(f.disposed,[0,1]);const loop=fixture(Array.from({length:6},()=>({status:302,headers:{location:'/again'}})));await assert.rejects(downloadResponse(loop.context,'https://example.com/start',async u=>u),/excessive/);assert.equal(loop.calls.length,6);assert.equal(loop.disposed.length,6);});
test('HTTP errors and artifact bodies above20MiB are rejected and disposed',async()=>{for(const response of [{status:403},{status:200,body:Buffer.alloc(20*1024*1024+1)}]){const f=fixture([response]);await assert.rejects(downloadResponse(f.context,'https://example.com/file',async u=>u));assert.deepEqual(f.disposed,[0]);}});
