Unattended-Upgrade::Package-Blacklist {
    "^libnvidia-(cfg1|common|compute|decode|encode|extra|fbc1|gl)(-|$)";
    "^nvidia-(compute-utils|dkms|driver|firmware|headless|kernel-common|kernel-source|utils|open)(-|$)";
    "^xserver-xorg-video-nvidia(-|$)";
    "^linux-(modules|objects|signatures)-nvidia(-|$)";
};
