/** SOURCE08 synthetic original producer format and independent proof consumers. */
import test from 'node:test';import assert from 'node:assert/strict';
import {retainedArtifactSourceFixture} from './fixtures/h041-artifact-source-fixture.js';
import {verifyFreshArtifactOwner} from '../../acceptance/compaction/artifact-source-proof.mjs';
const verify=(x:ReturnType<typeof retainedArtifactSourceFixture>,now=x.at+1000)=>verifyFreshArtifactOwner(x.packet,x.expected,x.freshExpected,x.route,now);
test('SOURCE original A vmSTAT fields bind current protected manifest +74 original content stats +same guarded route, nativeNULL remains unreported',()=>{const x=retainedArtifactSourceFixture();assert.equal(verify(x).status,'SOURCE_VALID');for(const mutate of [(v:any)=>v.control.fields.active_identity='FOREIGN',(v:any)=>v.control.fields.generation++, (v:any)=>v.control.fields.endpoint.base_url='http://FOREIGN/v1',(v:any)=>v.container.startedAt='2026-10-01T14:00:00Z',(v:any)=>v.installedManifest.stat.st_uid=1000,(v:any)=>v.statEvidence.files['tokenizer.json'].st_ino++,(v:any)=>v.nativeMetadata['/get_server_info'].fields.tokenizer_revision='invented']){const y=retainedArtifactSourceFixture();mutate(y.current);y.refreshCurrent();assert.throws(()=>verify(y));}const y=retainedArtifactSourceFixture();delete (y.current.installedManifest as any).stat;y.refreshCurrent();assert.equal(verify(y).status,'NOT_TESTED');});
test('SOURCE genuine command dates are finite/ordered BEFORE arithmetic; missing/NaN/future/expired/reversed deny',()=>{for(const patch of [{finishedUtc:undefined},{finishedUtc:'invalid'},{startedUtc:undefined},{startedUtc:'not-a-date'},{startedUtc:'2026-10-01T14:31:00Z'}]){const x=retainedArtifactSourceFixture();x.refreshCurrent(x.current,patch);assert.throws(()=>verify(x),/timestamps/);}for(const now of [NaN,Infinity,-Infinity])assert.throws(()=>verify(retainedArtifactSourceFixture(),now),/timestamps/);const x=retainedArtifactSourceFixture();assert.throws(()=>verify(x,x.at-1));assert.throws(()=>verify(x,x.at+60001));assert.equal(verify(x,x.at+60000).status,'SOURCE_VALID');});
import fs from 'node:fs/promises';import {syncBuiltinESMExports} from 'node:module';import {mkdtempSync,realpathSync,rmSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {sha256,stableJson} from '../../acceptance/compaction/native-adapter/projection.js';import {receiptFixture} from './helpers/codex-receipt-fixture.js';
import {qualifyNormalRestart,assertNormalRestartQualification,assertNormalRestartConfig} from '../../acceptance/compaction/native-adapter/normal-restart-ticket.js';
const pair=(key:string,v:any)=>{const text=stableJson(v);return {[key+'Utf8']:text,[key+'Sha256']:sha256(text)};};
test('SOURCE synthetic kernel seam: actual retained restart bytes qualify only EXACT config/qualification/session/window; ticket copies/transplants deny',async t=>{
 const directory=realpathSync(mkdtempSync(join(tmpdir(),'h041-source08-ticket-')));t.after(()=>rmSync(directory,{recursive:true,force:true}));
 const descriptor=Object.getOwnPropertyDescriptor(process,'platform')!;Object.defineProperty(process,'platform',{value:'linux'});t.after(()=>Object.defineProperty(process,'platform',descriptor));
 const read=fs.readFile;const boot='00000000-0000-0000-0000-000000000001',fields=Array(20).fill('0');fields[0]='S';fields[19]='200';
 t.mock.method(fs,'readFile',async(path:any,...args:any[])=>{if(String(path)==='/proc/sys/kernel/random/boot_id')return boot+'\n';if(String(path)===`/proc/${process.pid}/stat`)return `${process.pid} (SOURCE mock kernel) ${fields.join(' ')}\n`;if(String(path)==='/proc/100/stat')throw Error('SOURCE synthetic old process absent');return (read as any)(path,...args);});syncBuiltinESMExports();t.after(()=>{t.mock.restoreAll();syncBuiltinESMExports();});
 const f=receiptFixture(),sessionId=f.binding.sessionId,config:any={sessionId,dataDir:'/SOURCE',qualificationConfig:{qualificationSha256:sha256('SOURCE-protected-packet'),frozenSource:sha256('SOURCE-build')},review:{normalProductProof:{dataDir:'/SOURCE'},receiptSources:f.binding.sources,candidateCommit:'a'.repeat(40),authorization:{windowId:'SOURCE-window'}}},configBytes=Buffer.from(stableJson(config));
 const oldFields=[...fields];oldFields[19]='100';const kernel={source:'linux-proc-process-observation',pid:100,startTicks:'100',bootId:boot,procStatUtf8:`100 (SOURCE old kernel) ${oldFields.join(' ')}\n`,bootIdUtf8:boot+'\n'},stateUtf8=JSON.stringify({type:'session_meta',payload:{id:'SOURCE-parent'}})+'\n';
 const baseline={source:'owned-normal-product-baseline',sessionId,nativeThreadId:'SOURCE-parent',stateUtf8,stateSha256:sha256(stateUtf8),storeIdentity:{canonicalPath:'/SOURCE/harness.sqlite',ino:1,dev:2},...pair('originalInventory',{sessionId,through:0,count:0,sha256:sha256(''),rows:[],references:[]}),...pair('acceptedState',null)};
 const receipt={source:'owned-normal-process-adoption',configSha256:sha256(configBytes),qualificationSha256:config.qualificationConfig.qualificationSha256,candidateCommit:config.review.candidateCommit,windowId:config.review.authorization.windowId,baseline,oldReady:{dataDir:'/SOURCE',configSha256:sha256(configBytes),workerSha256:sha256('SOURCE-worker'),...pair('kernel',kernel)},workerSha256:sha256('SOURCE-worker'),oldExit:{code:0,signal:null,process:{pid:100,startTicks:'100',bootId:boot}},oldClose:{sessionId,nativeProducers:[{...pair('launchReceipt',f.rawLaunch),...pair('settlementReceipt',f.rawSettlement)}],...pair('gatewayObservation',{sessionId,outstanding:[],records:[]})}};
 const configPath=join(directory,'config.json'),path=join(directory,'adoption.json');writeFileSync(configPath,configBytes,{mode:0o600});const bytes=stableJson(receipt);writeFileSync(path,bytes,{mode:0o600});const ticket=await qualifyNormalRestart({path,sha256:sha256(bytes),configPath},config);
 assert.doesNotThrow(()=>assertNormalRestartConfig(ticket,config,configBytes));assert.doesNotThrow(()=>assertNormalRestartQualification(ticket,structuredClone(config.qualificationConfig)));
 for(const mutate of [(x:any)=>x.sessionId='FOREIGN',(x:any)=>x.review.authorization.windowId='FOREIGN',(x:any)=>x.qualificationConfig.frozenSource=sha256('FOREIGN'),(x:any)=>x.review.candidateCommit='b'.repeat(40)]){const x=structuredClone(config);mutate(x);assert.throws(()=>assertNormalRestartConfig(ticket,x,Buffer.from(stableJson(x))));}
 assert.throws(()=>assertNormalRestartConfig(ticket,config,Buffer.from(stableJson(config)+'\n')));assert.throws(()=>assertNormalRestartQualification({...ticket},config.qualificationConfig));assert.throws(()=>assertNormalRestartQualification(ticket,{...config.qualificationConfig,qualificationSha256:sha256('FOREIGN')}));
});
import {parsePostSamplingTrace,verifyPostSamplingGate,verifyTraceCausalJoin} from '../../acceptance/compaction/native-trace-evidence.mjs';
function line(patch:any={},top:any={}){return JSON.stringify({timestamp:'2026-10-01T14:30:02.500Z',level:'TRACE',target:'codex_core::session::turn',fields:{message:'post sampling token usage',turn_id:'SOURCE-turn',total_usage_tokens:400001,auto_compact_scope_tokens:400001,auto_compact_scope_limit:'Some(400000)',auto_compact_limit_scope:'Total',auto_compact_window_prefill_tokens:'None',full_context_window_limit:'Some(480000)',full_context_window_limit_reached:false,token_limit_reached:true,model_needs_follow_up:true,has_pending_input:false,needs_follow_up:true,...patch},...top})+'\n';}
function joinFixture(){return {lines:[{lineUtf8:line(),stderrSequence:7}],metadata:{thread_id:'SOURCE-parent',turn_id:'SOURCE-turn',request_kind:'compaction',window_number:1,window_id:'SOURCE-parent:1',context_window_id:'SOURCE-context',compaction:{trigger:'auto',reason:'context_limit',implementation:'responses',phase:'mid_turn'}},operation:{nativeThreadId:'SOURCE-parent',nativeTurnId:'SOURCE-turn',method:'turn/start',request:{value:{method:'turn/start',params:{threadId:'SOURCE-parent'}}},ack:{value:{result:{turn:{id:'SOURCE-turn'}}}},completed:{value:{params:{turn:{status:'completed'}}}},cleanup:{confirmed:true},gateway:{confirmed:true,nativeThreadId:'SOURCE-parent',nativeTurnId:'SOURCE-turn'}},producer:{launchNonce:'SOURCE-nonce',processId:'SOURCE-process'},clock:{source:'source-resolved-native-clock-causal-bracket',clockDomain:'native-rust-systemtime',launchNonce:'SOURCE-nonce',processId:'SOURCE-process',threadId:'SOURCE-parent',turnId:'SOURCE-turn',requestId:'SOURCE-request',windowId:'SOURCE-parent:1',contextWindowId:'SOURCE-context',samplingCompletedNativeUtc:'2026-10-01T14:30:02.000Z',compactionStartedNativeUtc:'2026-10-01T14:30:03.000Z',sourceControlFlow:'064c-turn.rs:post-sampling-before-mid-turn-auto'},gateway:{requestId:'SOURCE-request',nativeThreadId:'SOURCE-parent',nativeTurnId:'SOURCE-turn',windowId:'SOURCE-parent:1',contextWindowId:'SOURCE-context',state:'settled'},resolvedConfig:{contextWindow:480000,autoCompactTokenLimit:400000,maxOutputTokens:65536,effectiveScope:'total',tokenBudgetEnabled:false,fallbackBufferTokens:0,postTurnPercent:0}};}
test('SOURCE ORIGINAL pinned TRACE format preserves unknown spans/bytes; no absent/estimated/low/hardcap gate fabrication',()=>{const bytes=line({}, {span:{turn_id:'FOREIGN'}}),p=parsePostSamplingTrace(bytes);assert.equal(p.nativeTurnId,'SOURCE-turn');assert.equal(p.lineUtf8,bytes);assert.equal(p.lineSha256,sha256(bytes));assert.equal(verifyPostSamplingGate(bytes).status,'SOURCE_VALID');for(const patch of [{total_usage_tokens:399999,auto_compact_scope_tokens:399999},{total_usage_tokens:480000,auto_compact_scope_tokens:480000},{auto_compact_scope_limit:400000},{full_context_window_limit:'None'},{auto_compact_window_prefill_tokens:0},{turn_id:undefined},{full_context_window_limit_reached:true},{needs_follow_up:false},{auto_compact_limit_scope:'Prefill'},{token_limit_reached:undefined}])assert.throws(()=>verifyPostSamplingGate(line(patch)));assert.throws(()=>parsePostSamplingTrace(line({}, {target:'codex_core::post_sampling_token_estimate'})));assert.throws(()=>parsePostSamplingTrace(line({}, {timestamp:'invalid'})));assert.throws(()=>parsePostSamplingTrace(line()+line()));});
test('SOURCE separate pipe causality requires single native-clock bracket + owned canonical operation/gateway/config; delayed host read cannot reorder native event',()=>{const x=joinFixture();assert.equal(verifyTraceCausalJoin(x).status,'SOURCE_VALID');(x.lines[0] as any).hostObservedAt='2026-10-01T15:00:00Z';assert.equal(verifyTraceCausalJoin(x).status,'SOURCE_VALID');for(const mutate of [(v:any)=>v.clock.clockDomain='host-pipe-arrival',(v:any)=>v.clock.compactionStartedNativeUtc=v.clock.samplingCompletedNativeUtc,(v:any)=>v.lines.push(v.lines[0]),(v:any)=>v.clock=null,(v:any)=>v.operation.cleanup.confirmed=false,(v:any)=>v.gateway.requestId='FOREIGN',(v:any)=>v.metadata.compaction.trigger='manual',(v:any)=>v.metadata.compaction.phase='pre_turn',(v:any)=>v.resolvedConfig.fallbackBufferTokens=1,(v:any)=>v.producer.processId='FOREIGN']){const v=joinFixture();mutate(v);assert.throws(()=>verifyTraceCausalJoin(v));}});
import {verifyRetainedTrace} from '../../acceptance/compaction/native-trace-evidence.mjs';import {verifyManualCallerFiles,requireStageReceipt} from '../../acceptance/compaction/native-adapter/manual-entry.js';import {AUTHORIZATIONS,reviewedAuthorization} from '../../acceptance/compaction/authorization.mjs';
function traceReceiptFixture(){const f=receiptFixture(),raw=line(),launchReceiptUtf8=JSON.stringify(f.rawLaunch),settlementReceiptUtf8=JSON.stringify(f.rawSettlement),t={schema:'codex-native-trace-v1',nonce:f.binding.nonce,sessionId:f.binding.sessionId,runId:f.binding.runId,mode:'post-sampling-token-usage-v1',producer:f.rawLaunch.producer,containerId:f.rawLaunch.container.id,environment:{RUST_LOG:'off,codex_core::session::turn=trace',LOG_FORMAT:'json'},sources:f.binding.sources,events:[{file:'trace-event-0000.raw',sha256:sha256(raw),bytes:Buffer.byteLength(raw),stderrSequence:1,stderrOffset:0,chain:sha256('SOURCE-stream-prefix'),turnId:'SOURCE-turn',nativeTimestamp:JSON.parse(raw).timestamp,observedAtMs:Date.parse('2026-10-01T14:31:00Z'),observedMonotonicNs:1}],stderrBytes:Buffer.byteLength(raw),stderrSHA256:sha256(raw),stderrChain:sha256('SOURCE-stream-complete'),complete:true,cleanupOk:true,engineExitStatus:f.rawSettlement.engineExitStatus,requestedStop:f.rawSettlement.requestedStop},traceReceiptUtf8=JSON.stringify(t),packet={traceReceiptUtf8,traceReceiptSha256:sha256(traceReceiptUtf8),launchReceiptUtf8,launchReceiptSha256:sha256(launchReceiptUtf8),settlementReceiptUtf8,settlementReceiptSha256:sha256(settlementReceiptUtf8),events:[{lineUtf8:raw}]},expected={sessionId:f.binding.sessionId,receiptSources:f.binding.sources,traceReceiptSha256:packet.traceReceiptSha256,launchReceiptSha256:packet.launchReceiptSha256,settlementReceiptSha256:packet.settlementReceiptSha256};return {packet,expected,t};}
test('SOURCE actual A receipt shape consumes ORIGINAL selected files and independent root digests; altered raw/index/public env/owner/settlement deny',()=>{const f=traceReceiptFixture();assert.equal(verifyRetainedTrace(f.packet,f.expected).lines[0].lineUtf8,f.packet.events[0].lineUtf8);for(const mutate of [(x:any)=>x.packet.events[0].lineUtf8=line({turn_id:'FOREIGN'}),(x:any)=>x.t.nonce='FOREIGN',(x:any)=>x.t.environment.RUST_LOG='trace',(x:any)=>x.t.complete=false,(x:any)=>x.t.events[0].stderrOffset++,(x:any)=>x.t.events[0].turnId='FOREIGN',(x:any)=>x.t.producer.pid++,(x:any)=>x.t.cleanupOk=false]){const x=traceReceiptFixture();mutate(x);x.packet.traceReceiptUtf8=JSON.stringify(x.t);x.packet.traceReceiptSha256=sha256(x.packet.traceReceiptUtf8);x.expected.traceReceiptSha256=x.packet.traceReceiptSha256;assert.throws(()=>verifyRetainedTrace(x.packet,x.expected));}const x=traceReceiptFixture();x.expected.traceReceiptSha256=sha256('FOREIGN');assert.throws(()=>verifyRetainedTrace(x.packet,x.expected));});
test('SOURCE disabled connected manual caller rejects BEFORE application/credential/native launch; stage alone cannot claim fullPASS',async()=>{await assert.rejects(verifyManualCallerFiles({enabled:false,review:{}},'/SOURCE'));for(const r of [{qualification:'synthetic'},{qualification:'native',profile:'h041-summary-stage-v1',observedStatus:'PASS',actionCount:9,records:[],nativeAcceptance:'PASS',semanticAcceptance:'PASS'}]){const bytes=stableJson(r);assert.throws(()=>requireStageReceipt(bytes,sha256(bytes)));}});
test('SOURCE exact root DELIVERY05 is distinct; original04 remains expired at isolated fixtureclock, arbitrary expiry rejects',()=>{const now=Date.parse('2026-10-01T16:00:00Z'),a=AUTHORIZATIONS['H041-COMPACTION-DELIVERY-05'],review={authorization:{...a,windowId:'SOURCE-05'},notAfterUtc:a.capUtc,settlementReserveMs:120000};assert.equal(reviewedAuthorization(review,now).dispatchCutoffAt,Date.parse(a.capUtc)-120000);assert.throws(()=>reviewedAuthorization({...review,notAfterUtc:'2026-10-02T00:00:00Z'},now));const old=AUTHORIZATIONS['H041-COMPACTION-DELIVERY-04'];assert.throws(()=>reviewedAuthorization({authorization:{...old,windowId:'SOURCE-expired04'},notAfterUtc:old.capUtc,settlementReserveMs:120000},now));});
test('SOURCE actual vmSTAT08 sourceSHA256 receipt carrier is exact, conflicting legacy/source digests and historical NaN dates deny',()=>{const x=retainedArtifactSourceFixture();x.refreshCurrent(x.current,{sourceSHA256:x.freshExpected.scriptSha256,stdinSHA256:undefined});assert.equal(verify(x).status,'SOURCE_VALID');x.refreshCurrent(x.current,{sourceSHA256:sha256('FOREIGN'),stdinSHA256:x.freshExpected.scriptSha256});assert.throws(()=>verify(x),/source_digest/);for(const name of ['manifest','model','pass71','pass3']){const y=retainedArtifactSourceFixture(),file=(y.packet.files as any)[name],command=JSON.parse(file.receiptUtf8);command.finishedUtc='invalid';file.receiptUtf8=JSON.stringify(command);(y.expected.files as any)[name].receiptSha256=sha256(file.receiptUtf8);assert.throws(()=>verify(y),/retained_command_timestamps/);}});
import {NormalProductProducer} from '../../acceptance/compaction/native-adapter/normal-product.js';
test('SOURCE actual normal TRACE callback refuses JSON attestation; failure leaves automatic generation disabled and default hooks omit TRACE',t=>{t.mock.method(Date,'now',()=>Date.parse('2026-10-01T15:00:00Z'));const a=AUTHORIZATIONS['H041-COMPACTION-DELIVERY-05'],plan={autoCompactTokenLimit:400000},review={authorization:{...a,windowId:'SOURCE-trace'},notAfterUtc:a.capUtc,settlementReserveMs:120000,automaticPlan:plan},producer=new NormalProductProducer({sessionId:'SOURCE-session',hostPrivate:'/SOURCE',review:{...review,nativeTrace:{mode:'post-sampling-token-usage-v1'}}},{} as any),hooks=producer.hooks({} as any);assert.throws(()=>hooks.onNativeTraceReceipt!({sessionId:'SOURCE-session'} as any),/actual_owned/);assert.equal(producer.prepareAutomatic(plan,new AbortController().signal).generationAllowed,false);assert.equal(new NormalProductProducer({sessionId:'SOURCE-session',review},{} as any).hooks({} as any).nativeTraceMode,undefined);assert.throws(()=>reviewedAuthorization(review,NaN));});
import {automaticThreshold} from '../../acceptance/compaction/automatic-evidence.mjs';
test('SOURCE connected AUTO consumes original packet; unavailable independent cause/config staysNOT_TESTED, tampered packet fails',()=>{const f=traceReceiptFixture(),bytes=stableJson(f.packet),r={nativeTracePacketUtf8:bytes,nativeTracePacketSha256:sha256(bytes)};assert.equal(automaticThreshold(r,{},{}).status,'NOT_TESTED');assert.throws(()=>automaticThreshold({...r,nativeTracePacketUtf8:bytes+' '},{},{}),/packet_changed/);});
import {withOwnedManualRunner} from '../../acceptance/compaction/native-adapter/manual-entry.js';
test('SOURCE connected caller always shuts owned runner on runtime/pre-open FAIL, cancellation and sink failure; cleanup error remains visible',async()=>{let closures=0;const adapter={shutdown:async()=>{closures++;return {code:0,signal:null};}};assert.deepEqual(await withOwnedManualRunner(adapter,async()=>({status:'FAIL',opened:false})),{status:'FAIL',opened:false});assert.equal(closures,1);await assert.rejects(withOwnedManualRunner(adapter,async()=>{throw Error('SOURCE runtime failed before open');}),/runtime failed/);assert.equal(closures,2);const original=Error('SOURCE controller cancellation'),cleanup=Error('SOURCE owned exit unconfirmed');await assert.rejects(withOwnedManualRunner({shutdown:async()=>{throw cleanup;}},async()=>{throw original;}),(e:any)=>e instanceof AggregateError&&e.errors[0]===original&&e.errors[1]===cleanup);await assert.rejects(withOwnedManualRunner({shutdown:async()=>{throw cleanup;}},async()=>({status:'PASS'})),/exit unconfirmed/);});
import {OwnedApplicationRunner,observeApplicationIdentity} from '../../acceptance/compaction/native-adapter/process-runner.js';import {fixture,runAcceptance} from '../../acceptance/compaction/controller.mjs';
test('SOURCE real Node IPC runtime failure before controller open still confirms owned exit, second confirmation is bounded; no native process/model',async t=>{const d=realpathSync(mkdtempSync(join(tmpdir(),'h041-source08-preopen-')));t.after(()=>rmSync(d,{recursive:true,force:true}));const configPath=join(d,'source-config.json'),workerPath=join(d,'source-worker.mjs'),config='{}',code="import{readFileSync}from'node:fs';import{createHash}from'node:crypto';process.send({ready:true,protocol:'h041-owned-application-ipc-v1',configSha256:createHash('sha256').update(readFileSync(process.argv[2])).digest('hex')});process.on('message',m=>{if(m.method==='runtime')process.send({id:m.id,error:'SOURCE runtime failed before open'});if(m.method==='shutdown'){process.send({id:m.id,result:{closed:true}},()=>{process.disconnect();process.exit(0);});}});";writeFileSync(configPath,config,{mode:0o600});writeFileSync(workerPath,code,{mode:0o600});const a=AUTHORIZATIONS['H041-COMPACTION-DELIVERY-05'],runner=new OwnedApplicationRunner({workerPath,workerSha256:sha256(code),configPath,configSha256:sha256(config),hostPrivate:d,review:{authorization:{...a,windowId:'SOURCE-real-node-only'},notAfterUtc:a.capUtc,settlementReserveMs:120000},operationTimeoutMs:3000});await runner.start();const pid=runner.identitySnapshot().pid;let opened=0,closed=0;const packet=await fixture();Object.assign(packet.config,{enabled:true,profile:'h041-summary-stage-v1',cycles:[1],maximumNativeActions:9});const adapter={interfaceVersion:'h039-compaction-adapter-v1',kind:'synthetic',capabilities:['qualified-summary-fork','host-captured-probe-input','tools-and-files-denied-for-summary','settlement-receipts'],runtime:()=>runner.call('runtime'),open:()=>{opened++;throw Error('SOURCE unexpected open');},close:()=>{closed++;}};const result=await withOwnedManualRunner({shutdown:()=>runner.shutdownAndConfirm()},()=>runAcceptance({packet,adapter,qualification:'synthetic',sink:{record:async()=>{},private:async()=>{}}}));assert.equal(result.status,'FAIL');assert.equal(opened,0);assert.equal(closed,0);await assert.rejects(observeApplicationIdentity(pid));assert.deepEqual(await runner.shutdownAndConfirm(),{code:0,signal:null});});
