/** Synthetic actual ledger/default recovery composition; no Linux/native acceptance. */
import test,{type TestContext} from "node:test";import assert from "node:assert/strict";import {DatabaseSync} from "node:sqlite";import {mkdtempSync,realpathSync,chmodSync,rmSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {PassThrough} from "node:stream";
import {GatewayOwnership,GatewayOwnershipLedger} from "../src/gateway-ownership.js";import {observeGatewayNoGeneration} from "../src/codex-no-generation.js";import {createCodexRecoveryHost} from "../src/codex-recovery.js";import {Store} from "../src/store.js";import {Files} from "../src/files.js";import {CODEX_PIN,type CodexRuntime} from "../src/codex-engine.js";import type {Gateway} from "../src/gateway.js";import {receiptFixture} from "./helpers/codex-receipt-fixture.js";import {validateCodexLaunchReceipt,validateCodexSettlementReceipt} from "../src/codex-receipts.js";

import {writeFileSync} from "node:fs";
import {Broker} from "../src/broker.js";
import fs from "node:fs";import {syncBuiltinESMExports} from "node:module";import {createHash} from "node:crypto";
import {createCodexReceiptChannel,CODEX_RECEIPT_SOURCES,readCodexReceiptFile} from "../src/codex-receipts.js";
import {validateGatewayNoGeneration} from "../src/codex-no-generation.js";
import type {CodexRecoveryObservers} from "../src/codex-recovery-observation.js";
function setup(t:TestContext){const root=realpathSync(mkdtempSync(join(tmpdir(),"h041-recovery-"))),store=new Store(join(root,"harness.sqlite"));chmodSync(store.databasePath,0o600);const files=new Files(root,store),session=store.createSession(undefined,"codex",{engineVersion:CODEX_PIN.version,modelPolicyVersion:"recovery-fixture"});store.setNative(session.id,"old-retained-parent","codex");store.setNativeState(session.id,"codex",{ownership:"idle",activeTurnId:null,eventCursor:11});const run=store.createRun(session,"message","synthetic",[]),cp=store.checkpoints.prepare(session.id,run.id,"message","old-retained-parent");store.checkpoints.finish(session.id,run.id,"failed");store.updateRun(run.id,"failed");store.checkpoints.acknowledge(session.id,cp.id,"Synthetic human correction");const owner=new GatewayOwnership(new GatewayOwnershipLedger(store.db).options());let issued=0,revoked=0;const gateway:Pick<Gateway,"issueToken"|"revokeToken"|"observeNoGeneration">={issueToken:()=>{issued++;owner.registerSession(session.id);return "synthetic-owned-token";},revokeToken:()=>{revoked++;},observeNoGeneration:<T>(id:string,work:()=>Promise<T>)=>observeGatewayNoGeneration(id,()=>owner.admissionObservation(id),work)};const runtime:CodexRuntime={pin:CODEX_PIN,protocolQualified:true,nativeReceiptsRequired:true,ordinaryMemoryAdmission:async()=>{},modelPolicyVersion:"recovery-fixture",model:"qwen3.8-27b",provider:"sova",gatewayUrl:"http://10.0.2.2:8081/v1",contextLimit:480000,launchRootless:async()=>{throw Error("Synthetic launch reached");},revokeGatewaySession:()=>{},confirmGatewaySettlement:async()=>true};t.after(()=>{store.close();rmSync(root,{recursive:true,force:true});});return {store,files,session,cp,runtime,gateway,host:()=>createCodexRecoveryHost({store,files,runtime,gateway:()=>gateway,launcher:"/NEVER-EXECUTED",dispatchHeld:()=>false}),input:{signal:new AbortController().signal,reservation:store.reserveWorkspaceRecovery(session.id,cp.id),sessionId:session.id,checkpointId:cp.id,memory:store.memory.bridge(session.id)},counts:()=>({issued,revoked})};}
function nativeFixture(f:ReturnType<typeof setup>,t:TestContext){
 // Synthetic Linux receipt filesystem mapping only. Actual channel.wait mints its own
 // transport objects; neither JSON validation nor generated IDs supply that provenance.
 const platform=Object.getOwnPropertyDescriptor(process,"platform")!;Object.defineProperty(process,"platform",{...platform,value:"linux"});t.after(()=>Object.defineProperty(process,"platform",platform));
 const uid=process.getuid!(),logical=`/run/user/${uid}/ai-harness-codex-receipts`,physical=join(f.files.root,"channel");
 const map=(p:any)=>typeof p==="string"&&(p===logical||p.startsWith(logical+"/"))?physical+p.slice(logical.length):p;
 for(const key of ["mkdirSync","mkdtempSync","lstatSync","realpathSync","openSync","writeFileSync"] as const){
  const original=fs[key];t.mock.method(fs,key,(...args:any[])=>{args[0]=map(args[0]);const result=(original as any)(...args);return (key==="realpathSync"||key==="mkdtempSync")&&typeof result==="string"&&result.startsWith(physical)?logical+result.slice(physical.length):result;});
 }
 syncBuiltinESMExports();t.after(()=>{t.mock.restoreAll();syncBuiltinESMExports();});
 const stdin=new PassThrough(),stdout=new PassThrough(),requests:string[]=[];let exit!:()=>void;const exited=new Promise<void>(r=>exit=r);let launch:ReturnType<typeof validateCodexLaunchReceipt>;let resolveSettlement!:(s:ReturnType<typeof validateCodexSettlementReceipt>)=>void;const settlementReceipt=new Promise<ReturnType<typeof validateCodexSettlementReceipt>>(r=>resolveSettlement=r);let cleans=0;
 f.runtime.launchRootless=async input=>{
  const rf=receiptFixture(),deploy=realpathSync(join(import.meta.dirname,"../../deploy"));
  const channel=createCodexReceiptChannel({sessionId:input.sessionId,runId:"source-recovery",profileDir:input.profileDir,workspace:input.workspace,launcherPath:join(deploy,"run-codex.sh")},{linuxTransportQualified:true,sourceSha256:Object.fromEntries(CODEX_RECEIPT_SOURCES.map(k=>[k,createHash("sha256").update(fs.readFileSync(join(deploy,k))).digest("hex")]))});
  const binding=channel.binding,raw=JSON.parse(JSON.stringify(rf.rawLaunch).replaceAll("/task/profile",input.profileDir).replaceAll("/task/workspace",input.workspace).replaceAll("/trusted",join(deploy,"..")));raw.sessionId=input.sessionId;raw.runId=binding.runId;raw.nonce=binding.nonce;raw.checkedAtMs=Date.now();raw.sources=binding.sources;raw.producer.uid=binding.uid;raw.producer.cgroupPath=raw.producer.cgroupPath.replaceAll("1000",String(binding.uid));raw.egress.uid=binding.uid;raw.egress.cgroupPath=raw.egress.cgroupPath.replaceAll("1000",String(binding.uid));raw.container.user=`${binding.uid}:${binding.gid}`;
  fs.writeFileSync(join(channel.directory,"launch.json"),JSON.stringify(raw),{mode:0o600,flag:"wx"});fs.writeFileSync(join(channel.directory,"launch.ready"),"",{mode:0o600,flag:"wx"});launch=validateCodexLaunchReceipt(await channel.wait("launch",1000,()=>false),binding,raw.producer,raw.checkedAtMs);
  return {stdin,stdout,exited,launchReceipt:Promise.resolve(launch),settlementReceipt,terminateAndConfirm:async()=>{cleans++;const value={...rf.rawSettlement,producer:raw.producer,nonce:binding.nonce,runId:binding.runId,sessionId:input.sessionId,checkedAtMs:Date.now()};fs.writeFileSync(join(channel.directory,"settlement.json"),JSON.stringify(value),{mode:0o600,flag:"wx"});fs.writeFileSync(join(channel.directory,"settlement.ready"),"",{mode:0o600,flag:"wx"});resolveSettlement(validateCodexSettlementReceipt(await channel.wait("settlement",1000,()=>false),binding,launch,value.checkedAtMs));exit();return true;}};
 };
 stdin.on("data",chunk=>{for(const line of String(chunk).trim().split("\n")){const p=JSON.parse(line);if(!p.id)continue;requests.push(p.method);const result=p.method==="initialize"?{codexHome:f.files.profile(f.session.id)+"/codex-home",platformOs:"linux",platformFamily:"unix",userAgent:"codex/0.158.0"}:{thread:{id:"fresh-source-recovery",path:"/private/synthetic-rollout"},model:"qwen3.8-27b",modelProvider:"sova",cwd:f.files.workspace(f.session.workspaceId),approvalPolicy:"never"};stdout.write(JSON.stringify({id:p.id,result})+"\n");}});
 return {requests,cleans:()=>cleans};
}
function composed(f:ReturnType<typeof setup>,hooks:CodexRecoveryObservers={},held=()=>false){
 f.store.finishWorkspaceRecovery(f.input.reservation,false);
 const broker=new Broker({store:f.store,files:f.files,engineFactory:()=>{throw Error("No ordinary source runner");},launcher:"/NEVER",gatewayUrl:"http://127.0.0.1",issueToken:()=>"synthetic",revokeToken:()=>{},dispatchHeld:held,beforeNativeRecovery:hooks.beforeNativeRecovery});
 const host=createCodexRecoveryHost({store:f.store,files:f.files,runtime:f.runtime,gateway:()=>f.gateway,launcher:"/NEVER",dispatchHeld:held,observers:hooks});return {broker,run:()=>broker.recoverMemory(f.session.id,f.cp.id,host)};
}
test("actual normal recovery preserves opaque proof identity through observer and Store CAS",async t=>{
 const f=setup(t),n=nativeFixture(f,t),order:string[]=[];let seen:unknown;const prior=f.store.checkpoints.recoverWithFreshParent.bind(f.store.checkpoints);
 f.store.checkpoints.recoverWithFreshParent=(sid,cid,e)=>{assert.equal(e,seen);order.push("CAS");return prior(sid,cid,e);};
 const c=composed(f,{beforeNativeRecovery:(i,signal)=>{assert.equal(signal.aborted,false);order.push(i.stage);},onNativeRecoveryObserved:({evidence},signal)=>{assert.equal(n.cleans(),1);assert.equal(signal.aborted,false);seen=evidence;assert.ok(Object.isFrozen(evidence));if(evidence.launch.kind!=="launch"||evidence.settlement.kind!=="settlement")throw Error("fixture event kind");validateGatewayNoGeneration(evidence.noGeneration,f.session.id,evidence.launch.receipt,evidence.settlement.receipt);order.push("observed");}});
 const result=await c.run();assert.equal(result.nativeThreadId,"fresh-source-recovery");assert.deepEqual(order,["before-launch","observed","before-commit","CAS"]);assert.deepEqual(n.requests,["initialize","thread/start"]);assert.equal(f.store.checkpoints.status(f.session.id)[0]!.status,"recovered");assert.deepEqual(f.counts(),{issued:1,revoked:1});await c.broker.close();
});
test("cutoff after files prepare rejects before real launcher and revokes token",async t=>{
 const f=setup(t);let expired=false,launches=0;f.files.prepare=async()=>{expired=true;};f.runtime.launchRootless=async()=>{launches++;throw Error("must not launch");};const c=composed(f,{beforeNativeRecovery:()=>{if(expired)throw Error("synthetic cutoff");}});await assert.rejects(c.run(),/cutoff/);assert.equal(launches,0);assert.deepEqual(f.counts(),{issued:1,revoked:1});assert.equal(f.store.checkpoints.status(f.session.id)[0]!.status,"recovery_required");await c.broker.close();
});
for(const mode of ["cutoff","freeze","quarantine"] as const)test(`observer wait ${mode} keeps failed checkpoint and forbids CAS`,async t=>{
 const f=setup(t),n=nativeFixture(f,t);let entered!:()=>void,release!:()=>void,expired=false,held=false;const observed=new Promise<void>(r=>entered=r),wait=new Promise<void>(r=>release=r);const c=composed(f,{onNativeRecoveryObserved:async()=>{entered();await wait;},beforeNativeRecovery:i=>{if(i.stage==="before-commit"&&expired)throw Error("synthetic cutoff");}},()=>held);
 const pending=c.run(),reject=assert.rejects(pending);await observed;assert.equal(n.cleans(),1);assert.equal(f.store.workspaceRecoveryBlocked(f.session.workspaceId),true);if(mode==="cutoff")expired=true;if(mode==="freeze")held=true;if(mode==="quarantine")f.store.quarantine(f.session.workspaceId,"Synthetic uncertainty");release();await reject;assert.equal(f.store.getSession(f.session.id).nativeSessionId,"old-retained-parent");assert.equal(f.store.checkpoints.status(f.session.id)[0]!.status,"recovery_required");await c.broker.close();
});
for(const mode of ["abort","timeout"] as const)test(`bounded actual recovery ${mode} suppresses late observer commit`,async t=>{
 const f=setup(t),n=nativeFixture(f,t);let entered!:()=>void,release!:()=>void,signal:AbortSignal|undefined;const observed=new Promise<void>(r=>entered=r),wait=new Promise<void>(r=>release=r);const c=composed(f,{onNativeRecoveryObserved:async(_i,s)=>{signal=s;entered();await wait;}});
 if(mode==="timeout")t.mock.timers.enable({apis:["setTimeout"]});const pending=c.run(),reject=assert.rejects(pending);await observed;assert.equal(f.store.workspaceRecoveryBlocked(f.session.workspaceId),true);if(mode==="abort")await c.broker.close();else t.mock.timers.tick(5001);await reject;assert.equal(signal!.aborted,true);release();await Promise.resolve();assert.equal(n.cleans(),1);assert.equal(f.store.getSession(f.session.id).nativeSessionId,"old-retained-parent");assert.equal(f.store.checkpoints.status(f.session.id)[0]!.status,"recovery_required");await c.broker.close();
});
