/** SOURCE09 only: real UDS/HMAC transport with explicitly synthetic protected
 * filesystem/kernel readbacks. No native/model/production access or PASS. */
import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';import net from 'node:net';import {syncBuiltinESMExports} from 'node:module';import {createHmac} from 'node:crypto';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {loadQualificationTaskAdmission,isQualificationTaskAdmission} from '../src/qualification-task-admission.js';
import {CarrierAdmission,carrierRowsHeld,validateCarrierBinding} from '../../acceptance/compaction/native-adapter/carrier-admission.js';
import {actionFingerprint,freezeKey} from '../src/dispatch-freeze.js';import {AUTHORIZATIONS} from '../../acceptance/compaction/authorization.mjs';
import {loadReviewedCarrierEntry} from '../../acceptance/compaction/native-adapter/entry.js';
import {nativeTimestampNs,nativeCompactionStart,verifyNativeStartedAtTraceJoin,parseAutoCallTrace} from '../../acceptance/compaction/native-trace-evidence.mjs';
import {sha256,stableJson} from '../../acceptance/compaction/native-adapter/projection.js';
import {OwnedApplicationRunner,observeApplicationIdentity} from '../../acceptance/compaction/native-adapter/process-runner.js';
import {receiptFixture} from './helpers/codex-receipt-fixture.js';
import {verifyRetainedTrace} from '../../acceptance/compaction/native-trace-evidence.mjs';
const now=Date.parse('2026-10-01T15:00:00Z'),authority=AUTHORIZATIONS['H041-COMPACTION-DELIVERY-05'];
const action={action:'service.stop',node_id:'ai-harness',service_id:'harness',idempotency_key:'SOURCE-owned-stop',allow_interrupt:true};
function binding(){return {admissionPath:'/run/ai-harness-qualification/source09-test/admission.json',transactionId:'SOURCE-transaction',sessionId:'SOURCE-parent',ownHold:{key:freezeKey(action as any),fingerprint:actionFingerprint(action as any),action:JSON.stringify(action),scope:JSON.stringify(['harness'])}};}
function row(){return {...binding().ownHold,acknowledged:1};}
const review=()=>({authorization:{...authority,windowId:'SOURCE09'},notAfterUtc:authority.capUtc,settlementReserveMs:120000,carrier:binding()});
test('SOURCE V2 original receipt preserves numeric and unexpected AUTO NEW kinds; V1 environment, projected ancestry and kind transplant deny',()=>{
 const f=receiptFixture(),task={name:'turn','thread.id':'SOURCE-parent','turn.id':'SOURCE-turn'},numeric={timestamp:'2026-10-01T15:00:00.000000001Z',level:'TRACE',target:'codex_core::session::turn',fields:{message:'post sampling token usage',turn_id:'SOURCE-turn',total_usage_tokens:100,auto_compact_scope_tokens:100,auto_compact_scope_limit:'Some(400000)',auto_compact_limit_scope:'Total',auto_compact_window_prefill_tokens:'None',full_context_window_limit:'Some(480000)',full_context_window_limit_reached:false,token_limit_reached:false,model_needs_follow_up:false,has_pending_input:false,needs_follow_up:false},spans:[task],span:task},marker={timestamp:'2026-10-01T15:00:00.000000002Z',level:'TRACE',target:'codex_core::session::turn',fields:{message:'new'},spans:[task],span:{name:'run_auto_compact',reason:'ModelDownshift',phase:'PreTurn'}},events=[numeric,marker].map(x=>({lineUtf8:JSON.stringify(x)+'\n'})),launchReceiptUtf8=JSON.stringify(f.rawLaunch),settlementReceiptUtf8=JSON.stringify(f.rawSettlement);let offset=0;
 const t:any={schema:'codex-native-trace-v2',nonce:f.binding.nonce,sessionId:f.binding.sessionId,runId:f.binding.runId,mode:'post-sampling-token-usage-v2',producer:f.rawLaunch.producer,containerId:f.rawLaunch.container.id,environment:{RUST_LOG:'off,codex_core::session::turn=trace,codex_core::tasks=info',LOG_FORMAT:'json'},sources:f.binding.sources,events:events.map((x,i)=>{const event={file:`trace-event-${String(i).padStart(4,'0')}.raw`,kind:i?'autoCompactNew':'postSampling',threadId:'SOURCE-parent',turnId:'SOURCE-turn',sha256:sha256(x.lineUtf8),bytes:Buffer.byteLength(x.lineUtf8),stderrSequence:i+1,stderrOffset:offset,chain:sha256('SOURCE-chain-'+i),nativeTimestamp:JSON.parse(x.lineUtf8).timestamp,observedAtMs:now,observedMonotonicNs:i+1};offset+=event.bytes;return event;}),stderrBytes:events.reduce((n,x)=>n+Buffer.byteLength(x.lineUtf8),0),stderrSHA256:sha256(events.map(x=>x.lineUtf8).join('')),stderrChain:sha256('SOURCE-complete'),complete:true,cleanupOk:true,engineExitStatus:f.rawSettlement.engineExitStatus,requestedStop:f.rawSettlement.requestedStop};
 const project=()=>{const traceReceiptUtf8=JSON.stringify(t),packet={events,traceReceiptUtf8,traceReceiptSha256:sha256(traceReceiptUtf8),launchReceiptUtf8,launchReceiptSha256:sha256(launchReceiptUtf8),settlementReceiptUtf8,settlementReceiptSha256:sha256(settlementReceiptUtf8)},expected={sessionId:f.binding.sessionId,receiptSources:f.binding.sources,traceReceiptSha256:packet.traceReceiptSha256,launchReceiptSha256:packet.launchReceiptSha256,settlementReceiptSha256:packet.settlementReceiptSha256};return {packet,expected};};
 const x=project(),parsed=verifyRetainedTrace(x.packet,x.expected);assert.equal(parsed.lines.length,1);assert.equal(parsed.autoCalls.length,1);assert.equal(parsed.autoCalls[0].raw.span.reason,'ModelDownshift');
 for(const mutate of [(p:any)=>p.mode='post-sampling-token-usage-v1',(p:any)=>p.environment.RUST_LOG='off,codex_core::session::turn=trace',(p:any)=>p.events[1].kind='postSampling',(p:any)=>p.events[0].threadId='FOREIGN']){const saved=structuredClone(t);mutate(t);const y=project();assert.throws(()=>verifyRetainedTrace(y.packet,y.expected));Object.assign(t,saved);}
});
test('SOURCE real acquired Node pre-READY abort promptly joins owned exit; delayed READY cannot hold cancellation for120s',async t=>{
 t.mock.method(Date,'now',()=>now);const d=fs.realpathSync(fs.mkdtempSync(join(tmpdir(),'h041-source09-pre-ready-')));t.after(()=>fs.rmSync(d,{recursive:true,force:true}));const marker=join(d,'actual-pid'),workerPath=join(d,'source-worker.mjs'),configPath=join(d,'source-config.json'),config=JSON.stringify({marker});
 const code="import{readFileSync,writeFileSync}from'node:fs';const c=JSON.parse(readFileSync(process.argv[2],'utf8'));writeFileSync(c.marker,String(process.pid));const held=setTimeout(()=>process.send({ready:true}),60000);process.on('message',m=>{if(m.method==='shutdown'){clearTimeout(held);process.send({id:m.id,result:{shutdownAcknowledged:true}},()=>{process.disconnect();process.exit(0);});}});";fs.writeFileSync(workerPath,code,{mode:0o600});fs.writeFileSync(configPath,config,{mode:0o600});
 const runner=new OwnedApplicationRunner({workerPath,workerSha256:sha256(code),configPath,configSha256:sha256(config),hostPrivate:d,review:review(),operationTimeoutMs:3000}),abort=new AbortController(),started=runner.start(abort.signal);void started.catch(()=>undefined);
 while(!runner.hasAcquiredProcess())await new Promise(resolve=>setImmediate(resolve));const at=performance.now();abort.abort();await assert.rejects(started,/cancelled/);assert.ok(performance.now()-at<2000);
 const pid=Number(fs.readFileSync(marker,'utf8'));assert.ok(Number.isSafeInteger(pid));await assert.rejects(observeApplicationIdentity(pid));assert.deepEqual(await runner.shutdownAndConfirm(),{code:0,signal:null});
});
test('SOURCE native UTC preserves sub-ms precision; actual V2 i64 carrier survives sorted RESULTS and rejects absent/host/fractional/conflicting starts',()=>{
 assert.equal(nativeTimestampNs('2026-10-01T15:00:00.000000001Z')+1n,nativeTimestampNs('2026-10-01T15:00:00.000000002Z'));assert.equal(nativeTimestampNs('2026-10-01T15:00:00Z'),BigInt(now)*1000000n);
 for(const raw of ['invalid','2026-02-30T15:00:00Z','2026-10-01T15:00:00.1234567890Z','2026-10-01T15:00:00+01:00'])assert.throws(()=>nativeTimestampNs(raw));
 const value={method:'item/started',params:{threadId:'SOURCE-parent',turnId:'SOURCE-turn',item:{type:'contextCompaction',id:'SOURCE-compact'},startedAtMs:now}},bytesUtf8=JSON.stringify(value),frame={direction:'from-native',value:JSON.parse(stableJson(value)),bytesUtf8,sha256:sha256(bytesUtf8)};assert.equal(nativeCompactionStart(frame,'SOURCE-parent','SOURCE-turn').startedAtMs,now);
 for(const patch of [undefined,'2026-10-01T15:00:00Z',now+.1,-1,NaN]){const f=structuredClone(frame);f.value.params.startedAtMs=patch as any;f.bytesUtf8=JSON.stringify(f.value);f.sha256=sha256(f.bytesUtf8);assert.throws(()=>nativeCompactionStart(f,'SOURCE-parent','SOURCE-turn'));}assert.throws(()=>nativeCompactionStart(frame,'FOREIGN','SOURCE-turn'));
});
test('SOURCE original native start gives a strict causal cut; same-ms, stale/duplicate turn, foreign gateway and alternate causes cannot borrow host order',()=>{
 const operation={nativeThreadId:'SOURCE-parent',nativeTurnId:'SOURCE-turn',method:'turn/start',request:{value:{method:'turn/start',params:{threadId:'SOURCE-parent'}}},ack:{value:{result:{turn:{id:'SOURCE-turn'}}}},completed:{value:{params:{turn:{status:'completed'}}}},cleanup:{confirmed:true},gateway:{confirmed:true,nativeThreadId:'SOURCE-parent',nativeTurnId:'SOURCE-turn'}};
 const metadata={thread_id:'SOURCE-parent',turn_id:'SOURCE-turn',request_kind:'compaction',window_id:'SOURCE-parent:1',window_number:1,context_window_id:'SOURCE-context',compaction:{trigger:'auto',reason:'context_limit',implementation:'responses',phase:'mid_turn'}},gateway={requestId:'SOURCE-request',nativeThreadId:'SOURCE-parent',nativeTurnId:'SOURCE-turn',windowId:'SOURCE-parent:1',contextWindowId:'SOURCE-context',state:'settled'};
 const value={method:'item/started',params:{threadId:'SOURCE-parent',turnId:'SOURCE-turn',item:{type:'contextCompaction',id:'SOURCE-compact'},startedAtMs:now+1}},bytesUtf8=JSON.stringify(value),startFrame={direction:'from-native',value,bytesUtf8,sha256:sha256(bytesUtf8)};
 const line=JSON.stringify({timestamp:'2026-10-01T15:00:00.000999999Z',level:'TRACE',target:'codex_core::session::turn',fields:{message:'post sampling token usage',turn_id:'SOURCE-turn',total_usage_tokens:400001,auto_compact_scope_tokens:400001,auto_compact_scope_limit:'Some(400000)',auto_compact_limit_scope:'Total',auto_compact_window_prefill_tokens:'None',full_context_window_limit:'Some(480000)',full_context_window_limit_reached:false,token_limit_reached:true,model_needs_follow_up:true,has_pending_input:false,needs_follow_up:true}})+'\n';
 const input={lines:[{lineUtf8:line,stderrSequence:1}],startFrame,metadata,operation,gateway,producer:{launchNonce:'SOURCE-nonce',processId:'SOURCE-owned-process'},resolvedConfig:{contextWindow:480000,autoCompactTokenLimit:400000,maxOutputTokens:65536,effectiveScope:'total',tokenBudgetEnabled:false,fallbackBufferTokens:0,postTurnPercent:0}};
 assert.equal(verifyNativeStartedAtTraceJoin(input).status,'SOURCE_VALID');(input.lines[0] as any).hostObservedAt='2026-10-01T16:00:00Z';assert.equal(verifyNativeStartedAtTraceJoin(input).status,'SOURCE_VALID');
 const continued:any=structuredClone(input),later=JSON.parse(line);later.timestamp='2026-10-01T15:00:00.002Z';later.fields.total_usage_tokens=later.fields.auto_compact_scope_tokens=1000;later.fields.token_limit_reached=false;later.fields.needs_follow_up=false;continued.lines.push({lineUtf8:JSON.stringify(later)+'\n',stderrSequence:2});assert.equal(verifyNativeStartedAtTraceJoin(continued).totalUsageTokens,400001);const stale:any=structuredClone(input),low=JSON.parse(line);low.fields.total_usage_tokens=low.fields.auto_compact_scope_tokens=1000;low.fields.token_limit_reached=false;stale.lines.push({lineUtf8:JSON.stringify(low)+'\n',stderrSequence:2});assert.throws(()=>verifyNativeStartedAtTraceJoin(stale));
 for(const mutate of [(x:any)=>{x.startFrame.value.params.startedAtMs=now;x.startFrame.bytesUtf8=JSON.stringify(x.startFrame.value);x.startFrame.sha256=sha256(x.startFrame.bytesUtf8);},(x:any)=>x.lines.push(x.lines[0]),(x:any)=>x.gateway.nativeThreadId='FOREIGN',(x:any)=>x.metadata.compaction.trigger='manual',(x:any)=>x.operation.cleanup.confirmed=false,(x:any)=>x.resolvedConfig.tokenBudgetEnabled=true]){const x=structuredClone(input);mutate(x);assert.throws(()=>verifyNativeStartedAtTraceJoin(x));}
 const raw=JSON.parse(line),task={name:'turn','thread.id':'SOURCE-parent','turn.id':'SOURCE-turn'};raw.spans=[task];raw.span=task;
 const marker={timestamp:'2026-10-01T15:00:00.000999999Z',level:'TRACE',target:'codex_core::session::turn',fields:{message:'new'},spans:[task],span:{name:'run_auto_compact',reason:'ContextLimit',phase:'MidTurn'}};
 const stronger:any=structuredClone(input);stronger.startFrame.value.params.startedAtMs=now;stronger.startFrame.bytesUtf8=JSON.stringify(stronger.startFrame.value);stronger.startFrame.sha256=sha256(stronger.startFrame.bytesUtf8);stronger.lines=[{lineUtf8:JSON.stringify(raw)+'\n',stderrSequence:1}];stronger.autoCalls=[{lineUtf8:JSON.stringify(marker)+'\n',stderrSequence:2}];assert.equal(parseAutoCallTrace(stronger.autoCalls[0].lineUtf8).autoCallNativeUtc,marker.timestamp);assert.equal(verifyNativeStartedAtTraceJoin(stronger).status,'SOURCE_VALID');
 for(const mutate of [(x:any)=>x.autoCalls.push(x.autoCalls[0]),(x:any)=>x.autoCalls[0].stderrSequence=1,(x:any)=>{const p=JSON.parse(x.autoCalls[0].lineUtf8);p.spans[0]['thread.id']='FOREIGN';x.autoCalls[0].lineUtf8=JSON.stringify(p)+'\n';},(x:any)=>{const p=JSON.parse(x.autoCalls[0].lineUtf8);p.span.reason='ExhaustedReviewBudget';x.autoCalls[0].lineUtf8=JSON.stringify(p)+'\n';},(x:any)=>{const p=JSON.parse(x.autoCalls[0].lineUtf8);p.timestamp='2026-10-01T15:00:00.002Z';x.autoCalls[0].lineUtf8=JSON.stringify(p)+'\n';},(x:any)=>{const p=JSON.parse(x.lines[0].lineUtf8);p.fields.total_usage_tokens=p.fields.auto_compact_scope_tokens=399999;x.lines[0].lineUtf8=JSON.stringify(p)+'\n';x.lines.push({lineUtf8:JSON.stringify(raw)+'\n',stderrSequence:3});}]){const x=structuredClone(stronger);mutate(x);assert.throws(()=>verifyNativeStartedAtTraceJoin(x));}
});
test('SOURCE exact own STOP exclusion preserves foreign holds, immutable rows and whole-node frontier semantics',()=>{
 assert.equal(carrierRowsHeld([row()],binding(),'qwen3.8-27b'),false);
 const foreign={...row(),key:'SOURCE-foreign',scope:JSON.stringify(['qwen-gpu1'])};assert.equal(carrierRowsHeld([row(),foreign],binding(),'qwen3.8-27b'),true);assert.equal(carrierRowsHeld([row(),foreign],binding(),'qwen3.8-27b-gpu0'),false);
 for(const bad of [{...row(),acknowledged:0},{...row(),fingerprint:'CHANGED'},{...row(),action:row().action+' '},{...row(),scope:'[]'}])assert.throws(()=>carrierRowsHeld([bad],binding()));assert.throws(()=>carrierRowsHeld([],binding()));assert.throws(()=>carrierRowsHeld([row(),row()],binding()));assert.throws(()=>carrierRowsHeld([row(),{...foreign,scope:'broken'}],binding()));
 assert.equal(carrierRowsHeld([row(),{...foreign,action:JSON.stringify({node_id:'ai-vm',action:'node.reboot'}),scope:'[]'}],binding(),'glm-5.3-flash'),true);
});
test('SOURCE carrier rejects JSON brands and cross-config STOP bindings before files/workers/native',async t=>{
 t.mock.method(Date,'now',()=>now);await assert.rejects(loadReviewedCarrierEntry('/SOURCE-never-read',{} as any),/actual_A_carrier/);assert.throws(()=>new CarrierAdmission({verify:async()=>({status:'admit'})} as any,binding(),review()),/brand_required/);
 assert.deepEqual(validateCarrierBinding({carrier:binding(),bootstrap:{review:review()}}),binding());const config={carrier:binding(),bootstrap:{review:review()}};config.carrier.transactionId='FOREIGN';assert.throws(()=>validateCarrierBinding(config),/exact_root_reviewed/);
});
test('SOURCE actual A challenge + E retained parsed response; fresh exact owner/STOP/request only, no session alias or stale grant',async t=>{
 const directory=fs.realpathSync(fs.mkdtempSync(join(tmpdir(),'h041-source09-uds-'))),socketPath=join(directory,'source.sock'),key=Buffer.alloc(32,7),boot='00000000-0000-0000-0000-000000000009',fields=Array(20).fill('0');fields[19]='123';
 const platform=Object.getOwnPropertyDescriptor(process,'platform')!;Object.defineProperty(process,'platform',{value:'linux'});t.mock.method(Date,'now',()=>now);
 const b=binding(),p={schema:'qualification-task-admission-v1',maxOwnedSessions:64,carrier:{pid:9999,startTicks:'123',bootId:boot},dispatchCutoffMs:Date.parse(authority.capUtc)-120000,expiresAtMs:Date.parse(authority.capUtc),key:key.toString('hex'),lane:'qwen3.8-27b',ownHoldKey:b.ownHold.key,sessionId:b.sessionId,socketPath:b.admissionPath.replace('admission.json','admission.sock'),transactionId:b.transactionId};
 let fault='',seen=0;const server=net.createServer(socket=>{let raw='';socket.on('data',chunk=>{raw+=chunk;if(!raw.endsWith('\n'))return;seen++;const e=JSON.parse(raw),q=JSON.parse(e.body);assert.equal(e.mac,createHmac('sha256',key).update(e.body).digest('hex'));const v={...q,ownHoldKey:b.ownHold.key,ownerStartTicks:'123',status:q.operation==='register'?'registered':'admit',observedAtMs:now};if(fault==='transaction')v.transactionId='FOREIGN';if(fault==='freshness')v.observedAtMs=NaN;const body=JSON.stringify(v);socket.end(JSON.stringify({body,mac:createHmac('sha256',key).update(body).digest('hex')})+'\n');});});
 await new Promise<void>(resolve=>server.listen(socketPath,resolve));
 const read=fs.readFileSync,lstat=fs.lstatSync,realpath=fs.realpathSync,connect=net.connect;
 t.mock.method(fs,'readFileSync',(path:any,...args:any[])=>{if(path===b.admissionPath)return JSON.stringify(p);if(path==='/proc/9999/stat')return `9999 (SOURCE mocked kernel) ${fields.join(' ')}`;if(path==='/proc/9999/status')return 'Uid:\t0\t0\t0\t0\n';if(path==='/proc/sys/kernel/random/boot_id')return boot;return (read as any)(path,...args);});
 t.mock.method(fs,'lstatSync',(path:any,...args:any[])=>path===b.admissionPath||path===p.socketPath?{uid:0,mode:path===b.admissionPath?0o640:0o660,nlink:1,size:1000,isFile:()=>path===b.admissionPath,isSocket:()=>path===p.socketPath}:(lstat as any)(path,...args));
 t.mock.method(fs,'realpathSync',(path:any,...args:any[])=>path===b.admissionPath?path:(realpath as any)(path,...args));t.mock.method(net,'connect',((path:any,...args:any[])=>path===p.socketPath?connect(socketPath):(connect as any)(path,...args)) as any);syncBuiltinESMExports();
 t.after(async()=>{t.mock.restoreAll();syncBuiltinESMExports();Object.defineProperty(process,'platform',platform);await new Promise<void>(resolve=>server.close(()=>resolve()));fs.rmSync(directory,{recursive:true,force:true});});
 const admission=loadQualificationTaskAdmission(b.admissionPath);assert.equal(isQualificationTaskAdmission(admission),true);const gate=new CarrierAdmission(admission,b,review());assert.equal(gate.held([row()],'harness'),true);
 const actual=await gate.verify('SOURCE-parent','SOURCE-request',undefined,directory);assert.equal(actual.requestId,'SOURCE-request');assert.equal(gate.held([row()],'harness'),false);assert.equal(gate.held([row(),{...row(),key:'FOREIGN'}],'harness'),true);assert.equal(fs.readdirSync(directory).filter(n=>n.startsWith('carrier-')).length,1);
 await assert.rejects(gate.verify('FOREIGN-probe','SOURCE-request'),/unregistered_owned_task_session/);assert.equal(seen,1);await gate.registerSession({sessionId:'SOURCE-real-parent',role:'parent'});await gate.registerSession({sessionId:'SOURCE-real-probe',role:'probe',parentSessionId:'SOURCE-real-parent'});assert.equal((await gate.verify('SOURCE-real-probe','SOURCE-probe-request')).sessionId,'SOURCE-real-probe');fault='transaction';await assert.rejects(gate.verify('SOURCE-parent','SOURCE-request2'),/challenge_scope/);assert.equal(gate.held([row()],'harness'),true);fault='freshness';await assert.rejects(gate.verify('SOURCE-parent','SOURCE-request3'),/current_exact|challenge_scope/);
 t.mock.method(Date,'now',()=>Date.parse(authority.capUtc));assert.equal(gate.held([row()],'harness'),true);await assert.rejects(gate.verify('SOURCE-parent','SOURCE-request4'));
});
