// SOURCE protocol/capture fixtures only. No runtime, provider or native PASS.
import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,realpathSync,rmSync,readFileSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {DelegatedChildProducer} from '../../acceptance/compaction/native-adapter/delegated-child.js';
import {DispatchGuard} from '../../acceptance/compaction/native-adapter/dispatch-guard.js';
import {sha256,stableJson} from '../../acceptance/compaction/native-adapter/projection.js';
import {bindChildEnvelope,childRequestMetadata,verifyChildLineage} from '../../acceptance/compaction/child-lineage.mjs';
import {NativeObserver} from '../../acceptance/compaction/native-adapter/native-observer.js';
import {PassThrough} from 'node:stream';
import {translateResponses} from '../src/codex-responses.js';
import {createCodexRetentionParentPolicy,assertCodexTextOnlyPolicy} from '../src/codex-probe.js';
const parent='SOURCE-parent',child='SOURCE-child',turn='SOURCE-parent-turn',childTurn='SOURCE-child-turn';
const template={model:'qwen3.8-27b',instructions:'SOURCE frozen policy',client_metadata:{'x-codex-turn-metadata':JSON.stringify({request_kind:'turn',subagent_kind:'thread_spawn',thread_id:'@h041:child-thread-id',turn_id:'@h041:child-turn-id',parent_thread_id:'@h041:parent-thread-id',parent_turn_id:'@h041:parent-turn-id',root_turn_id:'@h041:root-turn-id'}),'x-codex-parent-thread-id':'@h041:parent-thread-id','x-openai-subagent':'collab_spawn'}};
const ids={childId:child,childTurnId:childTurn,parentId:parent,parentTurnId:turn};
test('SOURCE independently frozen canonical envelope binds actual child/parent/root IDs; carrier faults deny',()=>{
 const expected=bindChildEnvelope(template,ids);assert.equal(childRequestMetadata(expected,parent,turn).turn_id,childTurn);assert.deepEqual(template.client_metadata['x-codex-parent-thread-id'],'@h041:parent-thread-id');
 for(const field of ['parent_thread_id','root_turn_id','turn_id','subagent_kind']){const changed=structuredClone(expected),c=JSON.parse(changed.client_metadata['x-codex-turn-metadata']);c[field]='FOREIGN';changed.client_metadata['x-codex-turn-metadata']=JSON.stringify(c);if(field==='turn_id')assert.notDeepEqual(changed,expected);else assert.throws(()=>childRequestMetadata(changed,parent,turn));}
 for(const alias of [{'x-codex-parent-thread-id':'FOREIGN'},{'x-openai-subagent':'thread_spawn'},{thread_id:'FOREIGN'},{subagent_kind:'collab_spawn'}])assert.throws(()=>childRequestMetadata({...expected,client_metadata:{...expected.client_metadata,...alias}},parent,turn));
 const flat={client_metadata:JSON.parse(expected.client_metadata['x-codex-turn-metadata'])};assert.throws(()=>childRequestMetadata(flat,parent,turn),/canonical/);
 assert.throws(()=>bindChildEnvelope(template,{...ids,parentTurnId:''}));
});
test('SOURCE historical fixture clock is explicit and expiry remains enforced',t=>{
 t.mock.method(Date,'now',()=>Date.parse('2026-10-01T10:08:00Z'));const fields={sessionId:'SOURCE-session',runId:'SOURCE-run',configSha256:'a'.repeat(64),modelCatalogSha256:'b'.repeat(64),collaborationVersion:'v1' as const};assert.equal(createCodexRetentionParentPolicy(fields).mode,'retention-parent');
 t.mock.method(Date,'now',()=>Date.parse('2030-01-01T00:00:00Z'));assert.throws(()=>assertCodexTextOnlyPolicy(createCodexRetentionParentPolicy(fields)));
});
function frame(value:any,sequence:number,direction='from-native'){const bytesUtf8=JSON.stringify(value)+'\n';return {value,sequence,direction,bytesUtf8,sha256:sha256(bytesUtf8),observedAt:'2026-10-01T10:08:00Z'};}
test('SOURCE genuine producer consumer arms on the same live parent and awaits raw child read before translated count',async t=>{
 const root=realpathSync(mkdtempSync(join(tmpdir(),'h041-source04-')));t.after(()=>rmSync(root,{recursive:true,force:true}));
 const guard=new DispatchGuard(root),signal=new AbortController().signal,producer=new DelegatedChildProducer(),brief='Return SOURCE-child-nonce and UNKNOWN.',canary='SOURCE-parent-only-canary',state={capturedBy:'host',nativeThreadId:parent,stateUtf8:canary,stateSha256:sha256(canary),receiptUtf8:'SOURCE state receipt',receiptSha256:sha256('SOURCE state receipt')},launch={} as any;
 let frames:any[]=[],reads=0,counts=0,settlements=0;
 const host:any={guard,layout:{hostPrivate:root},observer:{frames:()=>structuredClone(frames),waitFrames:async(_id:string,ready:any)=>{if(!ready(frames))await new Promise<void>(r=>setImmediate(()=>{frames.push(frame({method:'turn/started',params:{threadId:child,turn:{id:childTurn,status:'inProgress'}}},frames.length));r();}));return structuredClone(frames);},settled:()=>true},evidence:{delegatedOperation:async(result:any)=>{assert.equal(result.nativeThreadId,child);assert.equal(result.requests[0].authenticationSessionId,'SOURCE-session');settlements++;}},application:{files:{profile:()=>root,assertNoLinks:async()=>{}}}};
 const parentResult=(id:string)=>({actionId:id,nativeThreadId:parent,nativeTurnId:turn,settledAt:'2026-10-01T10:08:01Z',settlement:{receiptSha256:sha256(id)},tokens:{SOURCE:'absent'},durationMs:{state:'measured',value:1,source:'SOURCE',receiptSha256:sha256('SOURCE duration')}});
 const runParent=async(text:string,id:string,purpose:string)=>{
  if(purpose==='append'){assert.ok(text.includes(canary));return parentResult(id);}
  assert.match(text,/fork_context/);assert.match(text,/false/);
  guard.register({sessionId:'SOURCE-session',actionId:id,runId:'SOURCE-store-run',mode:'parent-artifacts',purpose:'child',expiresAt:Date.now()+60000,signal,identity:()=>({nativeThreadId:parent,nativeTurnId:turn,activeRunId:'SOURCE-store-run'})});
  const readChildThread=async(candidate:string)=>{reads++;assert.equal(candidate,child);const thread={id:child,parentThreadId:parent,forkedFromId:null,modelProvider:'sova',model:'qwen3.8-27b',cliVersion:'0.158.0',turns:[],environments:[],source:{subAgent:{thread_spawn:{parent_thread_id:parent,depth:1}}}};frames.push(frame({id:11,method:'thread/read',params:{threadId:candidate,includeTurns:false}},frames.length,'to-native'),frame({id:11,result:{thread}},frames.length+1));return thread;};
  await producer.observe({sessionId:'SOURCE-session',threadId:parent,rolloutPath:join(root,'rollout.jsonl'),launchReceipt:launch,method:'thread/resume',observedSettings:{},readChildThread});
  await producer.arm({sessionId:'SOURCE-session',threadId:parent,method:'turn/start',launchReceipt:launch,params:{threadId:parent},readChildThread});
  frames.push(frame({method:'item/started',params:{threadId:parent,turnId:turn,item:{id:'SOURCE-spawn',type:'collabAgentToolCall',tool:'spawnAgent',prompt:brief,status:'inProgress'}}},0));
  // Parent followup can precede the child's provider ingress. Bind the real
  // canonical completed spawn receiver, then verify actual owned file bytes.
  frames.push(frame({method:'item/completed',params:{threadId:parent,turnId:turn,item:{id:'SOURCE-spawn',type:'collabAgentToolCall',tool:'spawnAgent',prompt:brief,receiverThreadIds:[child]}}},frames.length));
  const parentPrefix=[{type:'message',role:'user',content:[{type:'input_text',text:'SOURCE frozen parent spawn'}]}],followup=[...parentPrefix,{type:'function_call',call_id:'SOURCE-spawn',name:'spawn_agent',arguments:JSON.stringify({message:brief,fork_context:false})},{type:'function_call_output',call_id:'SOURCE-spawn',output:'SOURCE canonical spawn result'}];
  writeFileSync(join(root,'rollout.jsonl'),[{type:'session_meta',payload:{id:parent}},...followup.map(payload=>({type:'response_item',payload}))].map(v=>JSON.stringify(v)).join('\n')+'\n',{mode:0o600});
  await producer.followup('SOURCE-session',followup,parentPrefix);assert.equal(reads,0);assert.equal(counts,0);
  const original=JSON.parse(readFileSync(new URL('./fixtures/codex/native-requests.json',import.meta.url),'utf8'))[0].body,body={...original,...bindChildEnvelope(template,ids),tools:[],input:[{type:'message',role:'user',content:[{type:'input_text',text:brief}]}]};
  // Preserve the full independently approved envelope, including original native options.
  const rawEnvelope=Object.fromEntries(Object.entries(original).filter(([k])=>!['input','tools','client_metadata','instructions','model'].includes(k)));
  Object.assign(review.childProjectionSpec.envelope,rawEnvelope);
  guard.capture({sessionId:'SOURCE-session',requestId:'SOURCE-child-request',model:'qwen3.8-27b',phase:'pre_normalization',bytes:Buffer.from(JSON.stringify(body))});
  const translated={...translateResponses(body).body,model:'qwen3.8-27b'},count=guard.wrap((async()=>{assert.equal(reads,1);counts++;return 12;}) as any);
  await count!(translated,{alias:'qwen3.8-27b'} as any,'SOURCE',signal,{requestId:'SOURCE-child-request'} as any);
  guard.capture({sessionId:'SOURCE-session',requestId:'SOURCE-child-request',model:'qwen3.8-27b',phase:'normalized_request',bytes:Buffer.from(JSON.stringify(translated))});
  frames.push(frame({method:'item/completed',params:{threadId:child,turnId:childTurn,item:{type:'agentMessage',text:JSON.stringify({childNonce:'SOURCE-child-nonce',parentCanary:'UNKNOWN'})}}},frames.length+1),frame({method:'turn/completed',params:{threadId:child,turn:{id:childTurn,status:'completed',error:null}}},frames.length+2));
  return parentResult(id);
 };
 const review:any={authorization:{windowId:'SOURCE-window'},retentionParentPolicy:{collaborationVersion:'v1',collaborationToolNames:{spawnAgent:'spawn_agent'},childPolicy:{SOURCE:'not-qualified'}},childProjectionSpec:{prefixInput:[],envelope:structuredClone(template)}};
 const result=await producer.run({host,parentId:'SOURCE-session',collector:{captureState:async()=>state},signal,actionId:'SOURCE-child-action',brief,hostOnlyParentCanary:canary,childNonce:'SOURCE-child-nonce',runParent,review,runId:'SOURCE-run',parentPrefix:[]});
 assert.equal(counts,1);assert.equal(settlements,1);assert.equal(result.probe.childId,child);assert.equal(result.probe.parentId,parent);assert.equal(result.probe.reply.parentCanary,'UNKNOWN');assert.equal(result.ownedSettlements.length,2);assert.equal(verifyChildLineage(result.probe.nativeLineage,{childId:child,parentId:parent,firstDispatchAt:result.probe.firstDispatchAt}).status,'PASS');assert.equal(guard.activeScope(child),undefined);
});

test('SOURCE real stdio observer awaits reordered child turn frames and bounds cancellation/deadline',async t=>{
 const root=realpathSync(mkdtempSync(join(tmpdir(),'h041-source04-wait-')));t.after(()=>rmSync(root,{recursive:true,force:true}));const observer=new NativeObserver(root),stdout=new PassThrough(),stdin=new PassThrough();const process=observer.wrap('SOURCE-session',{stdin,stdout,exited:Promise.resolve(),terminateAndConfirm:async()=>true});process.stdout.resume();
 const abort=new AbortController(),wanted=(frames:any[])=>frames.some(f=>f.value.method==='turn/started'&&f.value.params.threadId===child);let returned=false;const waiting=observer.waitFrames('SOURCE-session',wanted,abort.signal,Date.now()+1000).then(f=>{returned=true;return f;});await new Promise<void>(r=>setImmediate(r));assert.equal(returned,false);const raw=JSON.stringify({method:'turn/started',params:{threadId:child,turn:{id:childTurn}}})+'\n';stdout.write(raw);const received=await waiting;assert.equal(received[0].bytesUtf8,raw);assert.equal(received[0].sha256,sha256(raw));
 const cancel=new AbortController(),cancelled=observer.waitFrames('SOURCE-session',()=>false,cancel.signal,Date.now()+1000);cancel.abort();await assert.rejects(cancelled,/cancelled/);await assert.rejects(observer.waitFrames('SOURCE-session',()=>false,new AbortController().signal,Date.now()+1),/deadline|cancelled/);
});
import {verifyObservedDelegatedScope} from '../../acceptance/compaction/model-scope.mjs';
test('SOURCE independent delegated scope verifies actual carriers, mount/egress and native frames; recomputed tampering denies',()=>{
 const raw={...JSON.parse(readFileSync(new URL('./fixtures/codex/native-requests.json',import.meta.url),'utf8'))[0].body,...bindChildEnvelope(template,ids),tools:[],input:[{type:'message',role:'user',content:[{type:'input_text',text:'SOURCE brief'}]}]},normalized={...translateResponses(raw).body,model:'qwen3.8-27b'},sources={source:sha256('SOURCE protected helper')};
 const policy:any={sourceRevision:'064c6b8c737f5b41d171fdda80bd9ef10ad06eb3',imageId:sha256('SOURCE image'),receiptSources:sources,nftSha256:sha256('SOURCE egress'),network:'gateway-only',gatewayUrl:'http://10.0.2.2:8081/v1',parentHousekeeping:'native-only-no-model-tools',rawTools:[],normalizedTools:[],mounts:[{source:'@profile',destination:'@profile',readOnly:false},{source:'@workspace',destination:'@workspace',readOnly:false}],forbiddenPaths:['/private/oracle','/private/originals','/private/captures','/private/controller'],parentThreadParams:{approvalPolicy:'never',sandbox:'read-only'},parentThreadAck:{sandbox:{type:'readOnly'}}};
 const launch={schema:'codex-launch-v1',sessionId:'SOURCE-session',nonce:sha256('SOURCE nonce'),sources,container:{imageRevision:policy.sourceRevision,imageId:policy.imageId,rootless:true,readOnly:true,privileged:false,network:'slirp4netns:allow_host_loopback=true',profileDir:'/native/profile',workspace:'/native/workspace',mounts:[{source:'/native/profile',destination:'/native/profile',readOnly:false},{source:'/native/workspace',destination:'/native/workspace',readOnly:false}],additionalMounts:[]},egress:{nftSha256:policy.nftSha256,receiptSha256:sha256('SOURCE nft receipt'),bootId:'SOURCE-boot',uid:501},producer:{bootId:'SOURCE-boot',uid:501}};
 const thread={id:child,parentThreadId:parent,forkedFromId:null,modelProvider:'sova',model:null,cliVersion:'0.158.0',turns:[],environments:[],source:{subAgent:{thread_spawn:{parent_thread_id:parent,depth:1}}}};
 const frames=[frame({id:1,method:'thread/resume',params:{threadId:parent,cwd:'/native/workspace',...policy.parentThreadParams}},0,'to-native'),frame({id:1,result:{thread:{id:parent},...policy.parentThreadAck}},1),frame({method:'item/started',params:{threadId:parent,turnId:turn,item:{id:'SOURCE-spawn',type:'collabAgentToolCall',tool:'spawnAgent',prompt:'SOURCE brief'}}},2),frame({method:'turn/started',params:{threadId:child,turn:{id:childTurn}}},3),frame({id:9,method:'thread/read',params:{threadId:child,includeTurns:false}},4,'to-native'),frame({id:9,result:{thread}},5)];
 const proof={lineage:{requestUtf8:frames[4].bytesUtf8,responseUtf8:frames[5].bytesUtf8,requestSha256:frames[4].sha256,responseSha256:frames[5].sha256,requestSequence:4,responseSequence:5,observedAt:frames[5].observedAt},parentTurnId:turn,spawnCallId:'SOURCE-spawn',brief:'SOURCE brief',firstDispatchAt:'2026-10-01T10:08:01Z'};
 const receipt:any={source:'h041-observed-delegated-model-scope',sessionId:child,authenticationSessionId:'SOURCE-session',actionId:'SOURCE-action',runId:'SOURCE-run',windowId:'SOURCE-window',nativeThreadId:child,nativeTurnId:childTurn,proof,scopePolicySha256:sha256(stableJson(policy)),launchReceiptUtf8:JSON.stringify(launch),launchReceiptSha256:sha256(JSON.stringify(launch)),nativeFramesUtf8:JSON.stringify(frames),nativeFramesSha256:sha256(JSON.stringify(frames)),firstRequestUtf8:JSON.stringify(raw),normalizedRequestUtf8:JSON.stringify(normalized)};
 const expected={scopePolicy:policy,probeThreadId:child,probeTurnId:childTurn,actionId:'SOURCE-action',runId:'SOURCE-run',windowId:'SOURCE-window'},probe=(s:any)=>({scopeReceiptUtf8:stableJson(s),scopeReceiptSha256:sha256(stableJson(s)),firstRequestUtf8:s.firstRequestUtf8,normalizedRequestUtf8:s.normalizedRequestUtf8});assert.equal(verifyObservedDelegatedScope(probe(receipt),expected).status,'PASS');
 for(const mutate of [(s:any)=>{const v=JSON.parse(s.firstRequestUtf8),m=JSON.parse(v.client_metadata['x-codex-turn-metadata']);m.turn_id='FOREIGN';v.client_metadata['x-codex-turn-metadata']=JSON.stringify(m);s.firstRequestUtf8=JSON.stringify(v);},(s:any)=>{const l=JSON.parse(s.launchReceiptUtf8);l.container.mounts[0].source='/private/oracle';s.launchReceiptUtf8=JSON.stringify(l);s.launchReceiptSha256=sha256(s.launchReceiptUtf8);},(s:any)=>{const n=JSON.parse(s.normalizedRequestUtf8);n.tools=[{name:'shell'}];s.normalizedRequestUtf8=JSON.stringify(n);},(s:any)=>{s.proof.parentTurnId='FOREIGN';},(s:any)=>{const f=JSON.parse(s.nativeFramesUtf8);f.splice(3,1);s.nativeFramesUtf8=JSON.stringify(f);s.nativeFramesSha256=sha256(s.nativeFramesUtf8);}]){const changed=structuredClone(receipt);mutate(changed);assert.equal(verifyObservedDelegatedScope(probe(changed),expected).status,'FAIL');}
});
