/** Explicit SOURCE fixtures. No native/GPU/runtime qualification or PASS. */
import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,realpathSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import * as policies from '../src/codex-probe.js';
import {selectPolicyFactories} from '../../acceptance/compaction/native-adapter/policy-selection.js';
import {reviewedAuthorization,AUTHORIZATIONS} from '../../acceptance/compaction/authorization.mjs';
import {NativeCountObserver} from '../../acceptance/compaction/native-adapter/count-observer.js';
import {OrdinaryClient,parseOrdinarySse} from '../../acceptance/compaction/native-adapter/ordinary-client.js';
import {projectBrowserNetwork,verifyBrowserReconnectReceipt} from '../../acceptance/compaction/native-adapter/browser-evidence.js';
import {automaticMetadata,automaticFrames,automaticThreshold} from '../../acceptance/compaction/automatic-evidence.mjs';
import {requireFullManualReceipt,assertOrdinaryDispatch} from '../../acceptance/compaction/native-adapter/ordinary-runner.js';
import {sha256} from '../../acceptance/compaction/native-adapter/projection.js';
import {createApp} from '../src/app.js';
const task='H041-COMPACTION-DELIVERY-04',parent='SOURCE-parent',turn='SOURCE-turn';
function directory(t:any){const p=realpathSync(mkdtempSync(join(tmpdir(),'h041-source05-')));t.after(()=>rmSync(p,{recursive:true,force:true}));return p;}
test('SOURCE exact distinct04 A factory/window; explicit fixture clock and expired originals remain expired',t=>{
 t.mock.method(Date,'now',()=>Date.parse('2026-10-01T11:30:00Z'));const chosen=selectPolicyFactories(policies,task,true);assert.equal(chosen.factory,policies.createCodexDelivery04Policy);assert.equal(chosen.parentFactory,policies.createCodexRetentionParent04Policy);assert.equal(chosen.adoptionAuthorization,'delivery04');assert.equal(selectPolicyFactories(policies,'H041-COMPACTION-DELIVERY-03',true).factory,policies.createCodexDeliveryPolicy);
 const a=AUTHORIZATIONS[task],review={authorization:{...a,windowId:'SOURCE-04'},settlementReserveMs:120000,notAfterUtc:a.capUtc};assert.equal(reviewedAuthorization(review).settlementReserveMs,120000);
 for(const changed of [{...review,notAfterUtc:'2030-01-01T00:00:00Z'},{...review,settlementReserveMs:1},{...review,authorization:{...a,capUtc:'2030-01-01T00:00:00Z',windowId:'SOURCE'}}])assert.throws(()=>reviewedAuthorization(changed));
 assert.throws(()=>reviewedAuthorization({...review,authorization:{...AUTHORIZATIONS.H040,windowId:'SOURCE'},notAfterUtc:AUTHORIZATIONS.H040.capUtc}));
 t.mock.method(Date,'now',()=>Date.parse(a.capUtc));assert.throws(()=>reviewedAuthorization(review));assert.throws(()=>selectPolicyFactories({...policies,CODEX_H041_DELIVERY04_WINDOW:policies.CODEX_H041_DELIVERY_WINDOW},task,true));
});
test('SOURCE complete translated count callback bytes bind actual request/result; mutation and missing ID deny',async t=>{
 const observer=new NativeCountObserver(directory(t)),body:any={model:'qwen3.8-27b',max_tokens:65536,messages:[{role:'user',content:'SOURCE µA'}],tools:[]},lane:any={alias:'qwen3.8-27b'},signal=new AbortController().signal;let seen=false;
 const count=observer.wrap(async(actual:any)=>{assert.equal(actual,body);seen=true;return {inputTokens:42,contextWindow:480000} as any;});await count(body,lane,'SOURCE-key',signal,{requestId:'SOURCE-request',phase:'count'} as any);assert.ok(seen);const receipt:any=observer.receipts(['SOURCE-request'])[0],v=JSON.parse(receipt.receiptUtf8);assert.equal(v.requestUtf8,JSON.stringify(body));assert.equal(v.requestSha256,sha256(v.requestUtf8));assert.equal(JSON.parse(v.resultUtf8).inputTokens,42);assert.throws(()=>observer.receipts(['missing']));await assert.rejects(count(body,lane,'SOURCE-key',signal,{requestId:'SOURCE-request',phase:'count'} as any));
 const mutate=observer.wrap(async(actual:any)=>{actual.tools.push({type:'function'});return {inputTokens:1,contextWindow:480000} as any;});await assert.rejects(mutate(body,lane,'SOURCE-key',signal,{requestId:'SOURCE-mutation',phase:'count'} as any));assert.throws(()=>observer.receipts(['SOURCE-mutation']));
});
test('SOURCE real normal app original endpoints and human CAS consumer, no native execution',async t=>{
 const root=directory(t),built=await createApp({dataDir:root,allowedOrigins:['http://localhost'],newChatEngine:'minimax',engineFactory:()=>{throw Error('SOURCE engine must not execute');},launcher:'/NEVER',gatewayUrl:'http://127.0.0.1:1/v1',issueToken:()=>{throw Error('SOURCE no provider');},revokeToken:()=>{},approvalProxyKey:'SOURCE-fixed-not-a-secret'});t.after(()=>built.app.close());
 const session=built.store.createSession(),other=built.store.createSession(),raw=Buffer.from('µA '.repeat(3000)),original=built.store.memory.retain(session.id,'message','SOURCE message',raw);let human=false;
 const client=new OrdinaryClient(session.id,{request:async(path,init)=>{const r=await built.app.inject({url:path,method:init.method,headers:{host:'localhost',...(init.bodyUtf8?{'content-type':'application/json'}:{}),...(human?{'x-ai-harness-approval-proxy':'SOURCE-fixed-not-a-secret'}:{})},payload:init.bodyUtf8});return {status:r.statusCode,bodyBytes:r.rawPayload};}},root);
 const signal=new AbortController().signal,view=(await client.request('/memory','GET',undefined,signal)).value;assert.ok(view.references.some((r:any)=>r.id===original.id));assert.equal((await client.readOriginal(original,signal)).sha256,sha256(raw));assert.ok((await client.searchLiteral('µA',original.id,signal)).value.hits.length);
 const foreign=built.store.memory.retain(other.id,'message','foreign',Buffer.from('foreign'));await assert.rejects(client.readOriginal(foreign,signal));
 const state={objective:'SOURCE fixture',constraints:[],decisions:[],pending:[],checks:[]},proposal=(await client.request('/memory/proposals','POST',{state},signal)).value;await client.request('/memory/accept','POST',{proposalId:proposal.id,expectedVersion:null},signal,403);human=true;await client.request('/memory/accept','POST',{proposalId:proposal.id,expectedVersion:null},signal);await client.request('/memory/accept','POST',{proposalId:proposal.id,expectedVersion:null},signal,409);
});
function frame(value:any,sequence:number,direction='from-native'){const bytesUtf8=JSON.stringify(value)+'\n';return {value,sequence,direction,bytesUtf8,sha256:sha256(bytesUtf8),observedAt:`2026-10-01T11:30:0${sequence}Z`};}
function frames(){return [frame({id:1,method:'turn/start',params:{threadId:parent,input:[{type:'text',text:'SOURCE'}]}},0,'to-native'),frame({method:'turn/started',params:{threadId:parent,turn:{id:turn}}},1),frame({id:1,result:{turn:{id:turn}}},2),frame({method:'item/started',params:{threadId:parent,turnId:turn,item:{id:'SOURCE-compaction',type:'contextCompaction'}}},3),frame({method:'item/completed',params:{threadId:parent,turnId:turn,item:{id:'SOURCE-compaction',type:'contextCompaction'}}},4),frame({method:'turn/completed',params:{threadId:parent,turn:{id:turn,status:'completed'}}},5)];}
function metadata(){return {request_kind:'compaction',thread_id:parent,turn_id:turn,window_number:1,window_id:parent+':1',context_window_id:'SOURCE-context',compaction:{trigger:'auto',reason:'context_limit',implementation:'responses',phase:'pre_turn',strategy:'memento'}};}
test('SOURCE pinned AUTO full canonical tuple, alias conflicts and ordinary raw RPC/ACK/lifecycle independent gates',()=>{
 const raw=(m:any)=>({client_metadata:{'x-codex-turn-metadata':JSON.stringify(m)}});assert.equal(automaticMetadata(raw(metadata()),parent,turn).compaction.phase,'pre_turn');
 for(const patch of [{trigger:'manual'},{reason:'model_downshift'},{phase:'standalone_turn'},{implementation:'responses_compaction_v2'},{strategy:'prefix_compaction'}]){const m=metadata();Object.assign(m.compaction,patch);assert.throws(()=>automaticMetadata(raw(m),parent,turn));}
 assert.throws(()=>automaticMetadata({client_metadata:{...raw(metadata()).client_metadata,thread_id:'FOREIGN'}},parent,turn));assert.throws(()=>automaticMetadata(raw({...metadata(),window_number:'1'}),parent,turn));assert.doesNotThrow(()=>automaticFrames(frames(),parent,turn));
 for(const change of [(f:any[])=>f[2].value.result.turn.id='FOREIGN',(f:any[])=>f[0].value.method='thread/compact/start',(f:any[])=>f[4].value.params.turnId='FOREIGN',(f:any[])=>f[5].value.params.turn.status='failed']){const f=frames();change(f);for(const e of f){e.bytesUtf8=JSON.stringify(e.value)+'\n';e.sha256=sha256(e.bytesUtf8);}assert.throws(()=>automaticFrames(f,parent,turn));}
 assert.equal(automaticThreshold({}, {},metadata()).status,'NOT_TESTED');
});
test('SOURCE ordinary SSE and actual CDP carrier projection strips headers and requires exact reconnect cursor',()=>{
 const session='SOURCE-session',event=(id:number)=>({id,sessionId:session,type:'progress',data:{text:'SOURCE'}}),sse=(id:number)=>`id: ${id}\nevent: progress\ndata: ${JSON.stringify(event(id))}\n\n`;
 assert.equal(parseOrdinarySse(Buffer.from(sse(1)),session,0).cursor,1);assert.throws(()=>parseOrdinarySse(Buffer.from(sse(1)),session,1));assert.throws(()=>parseOrdinarySse(Buffer.from(sse(1).slice(0,-1)),session,0));
 const origin='https://source.invalid',request=(id:string,after:number,time:number)=>projectBrowserNetwork('Network.requestWillBeSent',{requestId:id,timestamp:time,request:{url:`${origin}/api/sessions/${session}/events?after=${after}`,method:'GET',headers:{Authorization:'SOURCE-excluded'}}},origin,session),message=(id:string,n:number,time:number)=>projectBrowserNetwork('Network.eventSourceMessageReceived',{requestId:id,timestamp:time,eventId:String(n),eventName:'progress',data:JSON.stringify(event(n))},origin,session),r={source:'owned-protected-browser-sse-reconnect',sessionId:session,events:[request('SOURCE-network1',0,1),message('SOURCE-network1',1,2),request('SOURCE-network2',1,3),message('SOURCE-network2',2,4)]};
 assert.ok(!JSON.stringify(r).includes('Authorization'));assert.equal(verifyBrowserReconnectReceipt(JSON.stringify(r),session).status,'SOURCE_VALID');r.events[2]!.path='/api/sessions/SOURCE-session/events?after=0';assert.equal(verifyBrowserReconnectReceipt(JSON.stringify(r),session).status,'FAIL');
});
test('SOURCE fixtures and stage-only status cannot authorize the automatic native case',()=>{for(const r of [{qualification:'source',status:'PASS'},{qualification:'native',profile:'h040-summary-stage-v1',status:'PASS'},{qualification:'native',profile:'h041-full-retention-v1',status:'PASS',records:[]}]){const bytes=JSON.stringify(r);assert.throws(()=>requireFullManualReceipt(bytes,sha256(bytes)));}});

test('SOURCE dispatch cutoff is rechecked after asynchronous observation; settlement reserve grants no new dispatch',async()=>{const a={dispatchCutoffAt:Date.parse('2026-10-01T15:24:45.729Z')},signal=new AbortController().signal;assert.doesNotThrow(()=>assertOrdinaryDispatch(a,signal,a.dispatchCutoffAt-1));await Promise.resolve();assert.throws(()=>assertOrdinaryDispatch(a,signal,a.dispatchCutoffAt));const abort=new AbortController();abort.abort();assert.throws(()=>assertOrdinaryDispatch(a,abort.signal,a.dispatchCutoffAt-1));});
