/** Synthetic stdio/local counter fixtures, never Linux or native acceptance. */
import test from "node:test";import assert from "node:assert/strict";import {PassThrough} from "node:stream";import {createServer} from "node:http";
import {CodexConnection} from "../src/codex-connection.js";
import {observeOwnedCodexProcess,type CodexHostObservations} from "../src/codex-host-observation.js";import type {OwnedCodexProcess} from "../src/codex-launcher.js";import {composeCodexHost} from "../src/codex-host.js";import {QWEN_CODEX_PIN} from "../src/codex-qwen.js";import {composeCodexProductObservers} from "../src/codex-product-observation.js";import type {CodexOrdinaryEntry} from "../src/codex-ordinary-entry.js";
function owned(){let cleans=0;const stdin=new PassThrough(),stdout=new PassThrough(),p:OwnedCodexProcess={stdin,stdout,exited:new Promise(()=>{}),terminateAndConfirm:async()=>{cleans++;return true;}};return {p,cleans:()=>cleans};}
test("raw tee preserves exact stream/process identity and does not begin flow before parser",async()=>{const f=owned(),events:any[]=[];const p=observeOwnedCodexProcess(f.p,{sessionId:"owned"},{onRawNative:e=>events.push(e)});assert.equal(p,f.p);assert.equal(p.stdout.readableFlowing,null);p.stdout.push(Buffer.from('ACK\n'));assert.equal(events.length,1);let parsed="";p.stdout.on("data",b=>parsed+=b);await new Promise(r=>setImmediate(r));assert.equal(parsed,"ACK\n");p.stdin.write("request\n");assert.deepEqual(events.map(e=>[e.direction,e.sequence,e.bytes.toString()]),[["output",1,"ACK\n"],["input",2,"request\n"]]);assert.ok(events.every(e=>e.process===p));});
for(const mode of ["throw","async","bound","decoded"] as const)test(`raw capture ${mode} fails closed with exact process cleanup`,async()=>{const f=owned();const observer:CodexHostObservations={maxRawBytesPerProcess:4,onRawNative:()=>{if(mode==="throw")throw Error("private observer detail");if(mode==="async")return Promise.reject(Error("private")) as any;}};observeOwnedCodexProcess(f.p,{sessionId:"owned"},observer);const rejected=assert.rejects(f.p.observationFailure!,/Trusted native observation failed/);if(mode==="decoded")f.p.stdout.push("bad");else assert.throws(()=>f.p.stdin.write(mode==="bound"?"large":"x"),/Trusted native observation/);await rejected;assert.equal(f.cleans(),1);});
test("normal-entry composition keeps ordinary guard first and cannot widen metadata authority",async()=>{const events:string[]=[],base={protocolQualified:true as const,rootlessQualified:true as const,verifyLane:async()=>{throw Error("unused");}},ordinary={approvalId:"synthetic-entry",assertCurrent:()=>{throw Error("not native qualification");},nativeReceiptPolicy:{linuxTransportQualified:true as const,sourceSha256:{}},hooks:{onNativeThread:async()=>{events.push("ordinary");},onNativeSettlementReceipt:()=>{events.push("ordinary-settled");},nativeMetadataAuthority:()=>undefined}} as CodexOrdinaryEntry;const c=composeCodexProductObservers(base,ordinary,{onNativeThread:async()=>{events.push("observer");},onNativeSettlementReceipt:()=>{events.push("observer-settled");}});await c.onNativeThread!({} as any);c.onNativeSettlementReceipt!({} as any);assert.deepEqual(events,["ordinary","observer","ordinary-settled","observer-settled"]);assert.equal(c.nativeMetadataAuthority,ordinary.hooks.nativeMetadataAuthority);ordinary.hooks.onNativeThread=async()=>{throw Error("genuine gate rejects");};const denied=composeCodexProductObservers(base,ordinary,{onNativeThread:async()=>{events.push("must-not-run");}});await assert.rejects(denied.onNativeThread!({} as any),/genuine gate/);assert.equal(events.includes("must-not-run"),false);});
test("real host counter observes actual translated payload after identity bracket and rejects observer failure",async t=>{let identity=1,change=false;const received:any[]=[],captured:any[]=[];const server=createServer(async(req,res)=>{const chunks=[];for await(const c of req)chunks.push(c);received.push(JSON.parse(Buffer.concat(chunks).toString()));if(change)identity++;res.setHeader("content-type","application/json");res.end(JSON.stringify({tokens:[1,2],count:2,max_model_len:480000}));});await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));t.after(()=>new Promise<void>(r=>{server.closeAllConnections();server.close(()=>r());}));let fail=false;const host=composeCodexHost("/trusted/deploy/run-codex.sh",()=>undefined,{protocolQualified:true,rootlessQualified:true,verifyLane:async alias=>({...QWEN_CODEX_PIN,alias,instanceId:String(identity)}),observations:{onVerifiedCount:(e,signal)=>{assert.equal(signal.aborted,false);captured.push(e);if(fail)throw Error("private capture detail");}}});const lane={alias:"qwen3.8-27b",url:`http://127.0.0.1:${(server.address() as any).port}/v1`},body={model:lane.alias,reasoning_effort:"none",messages:[{role:"user",content:"synthetic"}],tools:[],stream:true};const count=()=>host.responses!.countQwen(body,lane,"fixture-key",new AbortController().signal,{requestId:"actual-request",phase:"count"});assert.deepEqual(await count(),{inputTokens:2,contextWindow:480000});assert.deepEqual(captured[0].body,received[0]);assert.equal(captured[0].context.requestId,"actual-request");assert.ok(Object.isFrozen(captured[0].body.messages));change=true;await assert.rejects(count());assert.equal(captured.length,1);change=false;fail=true;await assert.rejects(count(),/Trusted count observation failed/);assert.equal(captured.length,2);});

test("raw capture precedes actual CodexConnection UTF8 decoding and preserves split multibyte ACK",async()=>{const f=owned(),chunks:Buffer[]=[],output='{"id":1,"result":{"thread":{"id":"actual-ack-€"}}}\n';observeOwnedCodexProcess(f.p,{sessionId:"owned"},{onRawNative:e=>{if(e.direction==="output")chunks.push(e.bytes);}});const connection=new CodexConnection(f.p.stdout,f.p.stdin,()=>{},()=>{},1000);const result=connection.request("thread/read",{threadId:"parent"});const raw=Buffer.from(output),at=raw.indexOf(Buffer.from("€"));f.p.stdout.push(raw.subarray(0,at+1));f.p.stdout.push(raw.subarray(at+1,at+2));f.p.stdout.push(raw.subarray(at+2));assert.deepEqual(await result,{thread:{id:"actual-ack-€"}});assert.equal(f.p.stdout.readableEncoding,"utf8");assert.deepEqual(Buffer.concat(chunks),raw);assert.equal(chunks.length,3);assert.equal(f.cleans(),0);});

for(const mode of ["invalid","truncated"] as const)test(`actual raw observer rejects ${mode} UTF8 before parser`,async()=>{const f=owned();observeOwnedCodexProcess(f.p,{sessionId:"owned"},{onRawNative:()=>{}});const failure=assert.rejects(f.p.observationFailure!,/Trusted native observation failed/);f.p.stdout.push(Buffer.from([mode==="invalid"?0xff:0xe2]));if(mode==="truncated")f.p.stdout.push(null);await failure;assert.equal(f.cleans(),1);});
