/** Synthetic protected-file/ledger/schema fixtures; native qualification NOT_TESTED. */
import test from "node:test";import assert from "node:assert/strict";
import {mkdtempSync,realpathSync,mkdirSync,writeFileSync,readFileSync,rmSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {createHash,createHmac,randomBytes} from "node:crypto";
import {loadCodexOrdinaryEntry,assertOrdinaryProtectedPaths} from "../src/codex-ordinary-entry.js";
import {observeGatewayNoGeneration,validateGatewayNoGeneration} from "../src/codex-no-generation.js";
import {validateCodexChildMetadata} from "../src/codex-child-metadata.js";
import {canonicalJson} from "../src/codex-canonical.js";import {receiptFixture} from "./helpers/codex-receipt-fixture.js";
const sha=(b:string|Uint8Array)=>createHash("sha256").update(b).digest("hex");
function fixture(t:import("node:test").TestContext){const root=realpathSync(mkdtempSync(join(tmpdir(),"h041-entry-"))),serverDir=join(root,"server"),deploymentDir=join(root,"deploy");for(const p of [serverDir,join(serverDir,"src"),join(serverDir,"dist"),deploymentDir])mkdirSync(p,{mode:0o700});const files:Record<string,string>={},put=(p:string,s:string)=>{mkdirSync(join(p,".."),{recursive:true,mode:0o700});writeFileSync(p,s,{mode:0o600});return sha(s);};for(const name of ["main","codex-preview-main"]){files[join(serverDir,"dist",name+".js")]=put(join(serverDir,"dist",name+".js"),"export {};");files[join(serverDir,"src",name+".ts")]=put(join(serverDir,"src",name+".ts"),"export {};");}files[join(serverDir,"package-lock.json")]=put(join(serverDir,"package-lock.json"),"{}");const f=receiptFixture();for(const name of Object.keys(f.binding.sources))files[join(deploymentDir,name)]=put(join(deploymentDir,name),"source");const launchPath=join(root,"launch.json"),settlementPath=join(root,"settlement.json"),protocolAckPath=join(root,"acks.json"),binaryPath=join(root,"binary");const qualification={launchPath,settlementPath,protocolAckPath,binaryPath,launchSha256:put(launchPath,JSON.stringify(f.rawLaunch)),settlementSha256:put(settlementPath,JSON.stringify(f.rawSettlement)),protocolAckSha256:put(protocolAckPath,JSON.stringify({schema:"codex-zero-generation-acks-v1",launchNonce:f.rawLaunch.nonce,initialize:{codexHome:f.binding.profileDir+"/codex-home",platformOs:"linux",userAgent:"codex/0.158.0"},threadStart:{thread:{id:"synthetic-thread"},model:"qwen3.8-27b",modelProvider:"sova",cwd:f.binding.workspace},providerRequests:0})),binarySha256:put(binaryPath,"synthetic native bytes"),binaryVersion:"0.158.0",upstream:"064c6b8c737f5b41d171fdda80bd9ef10ad06eb3",binding:f.binding,observedProducer:f.producer,validatedAtMs:f.now};const body={schema:"codex-ordinary-entry-v1",approvalId:"synthetic-root-source",sourceCommit:"a".repeat(40),files,receiptSources:f.binding.sources,qualification},key=randomBytes(32),keyPath=join(root,"key"),path=join(root,"entry");writeFileSync(keyPath,key,{mode:0o600});const seal=()=>put(path,JSON.stringify({body,seal:createHmac("sha256",key).update(canonicalJson(body)).digest("hex")}));seal();t.after(()=>rmSync(root,{recursive:true,force:true}));return {path,keyPath,body,seal,f,serverDir,deploymentDir};}
test("ordinary entry absent is disabled; half configured rejects",()=>{assert.equal(loadCodexOrdinaryEntry(undefined,undefined),undefined);assert.throws(()=>loadCodexOrdinaryEntry("/none",undefined));});
test("synthetic sealed entry requires actual executing graph and does not brand native launch",t=>{const f=fixture(t),e=loadCodexOrdinaryEntry(f.path,f.keyPath,f)!;assert.equal(e.approvalId,"synthetic-root-source");assert.throws(()=>e.assertCurrent(f.f.launch),/genuinely/);});
for(const kind of ["seal","build","missing_graph","binary","raw_ack"] as const)test(`ordinary entry rejects ${kind}`,t=>{const f=fixture(t);if(kind==="seal")writeFileSync(f.path,"{}");if(kind==="build")writeFileSync(join(f.serverDir,"dist/main.js"),"changed");if(kind==="missing_graph"){delete f.body.files[join(f.serverDir,"dist/main.js")];f.seal();}if(kind==="binary")writeFileSync(f.body.qualification.binaryPath,"changed");if(kind==="raw_ack")writeFileSync(f.body.qualification.protocolAckPath,"{}");assert.throws(()=>loadCodexOrdinaryEntry(f.path,f.keyPath,f));});
test("validated tmpfs mounts have no host source; protected physical bind is denied",()=>{const f=receiptFixture(),launch=structuredClone(f.launch);launch.container.additionalMounts=[{source:"",destination:"/tmp",type:"tmpfs",rw:true}];assert.doesNotThrow(()=>assertOrdinaryProtectedPaths(launch,["/private/key"]));launch.container.additionalMounts.push({source:"/private",destination:"/mounted",type:"bind",rw:false});assert.throws(()=>assertOrdinaryProtectedPaths(launch,["/private/key"]));});
test("gateway no-generation proof observes real ledger changes and rejects serialization",async()=>{const f=receiptFixture(),start=Date.now();const observed=await observeGatewayNoGeneration("s",()=>[],async()=>null);const l={...f.launch,checkedAtMs:start},s={...f.settlement,checkedAtMs:observed.proof.endedAtMs};assert.doesNotThrow(()=>validateGatewayNoGeneration(observed.proof,"s",l,s));assert.throws(()=>validateGatewayNoGeneration(structuredClone(observed.proof),"s",l,s));let records:import("../src/gateway-ownership.js").RequestOwnership[]=[];await assert.rejects(()=>observeGatewayNoGeneration("s",()=>records,async()=>{records=[{id:"new",sessionId:"s",state:"settled",updatedAt:"now"}];}),/Provider operation/);});
const child=()=>({id:"child",parentThreadId:"parent",forkedFromId:null,modelProvider:"sova",model:"qwen3.8-27b",cliVersion:"0.158.0",source:{subAgent:{thread_spawn:{parent_thread_id:"parent",depth:1}}},turns:[]});
test("pinned clean child ancestry shape accepts only exact native owner/no-fork",()=>{assert.equal(validateCodexChildMetadata(child(),"parent",["qwen3.8-27b"],"sova").id,"child");for(const patch of [{parentThreadId:"foreign"},{forkedFromId:"parent"},{source:"cli"},{modelProvider:"foreign"},{cliVersion:"0.159.2"},{turns:[{}]}])assert.throws(()=>validateCodexChildMetadata({...child(),...patch},"parent",["qwen3.8-27b"],"sova"));});
