/** Synthetic source guards only; no native trace or Linux transport qualification. */
import test from 'node:test';import assert from 'node:assert/strict';
import {realpathSync,mkdtempSync,mkdirSync,writeFileSync,chmodSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,dirname} from 'node:path';import {createHash} from 'node:crypto';
import {CODEX_RECEIPT_SOURCES,assertCodexReceiptSourceClosure,validateCodexTraceReceipt} from '../src/codex-receipts.js';
import {receiptFixture} from './helpers/codex-receipt-fixture.js';
import {createRootlessCodexLauncher} from '../src/codex-launcher.js';
test('actual receipt ancestry guard reproduces0775 failure before launch and accepts0755 byte-identical closure',()=>{const root=realpathSync(mkdtempSync(join(tmpdir(),'h041-preflight-'))),deploy=join(root,'deploy'),hashes:Record<string,string>={};try{for(const p of CODEX_RECEIPT_SOURCES){const file=join(deploy,p);mkdirSync(dirname(file),{recursive:true,mode:0o755});writeFileSync(file,'source',{mode:0o644});hashes[p]=createHash('sha256').update('source').digest('hex');}chmodSync(deploy,0o775);assert.throws(()=>assertCodexReceiptSourceClosure(deploy,hashes),/ancestry/);chmodSync(deploy,0o755);assert.deepEqual(assertCodexReceiptSourceClosure(deploy,hashes),hashes);chmodSync(join(deploy,'engine'),0o775);assert.throws(()=>assertCodexReceiptSourceClosure(deploy,hashes),/ancestry/);}finally{rmSync(root,{recursive:true,force:true});}});
test('validator JSON even genuine-shaped launch/settlement fixtures cannot grant original trace provenance',()=>{const f=receiptFixture();assert.throws(()=>validateCodexTraceReceipt({schema:'codex-native-trace-v1'}, {...f.binding,nativeTraceMode:'post-sampling-token-usage-v1'},f.launch,f.settlement),/Unbound/);});
test('trace opt-in remains unavailable through unqualified native launcher on Mac',async()=>{await assert.rejects(createRootlessCodexLauncher('/source/deploy/run-codex.sh')({sessionId:'s',profileDir:'/task/p',workspace:'/task/w',codexHome:'/task/p/codex-home',gatewayUrl:'http://10.0.2.2:8081/v1',gatewayToken:'synthetic',modelPolicyVersion:'sova-codex-0.158.0-qwen-text-v2',nativeTraceMode:'post-sampling-token-usage-v1'}));});
