/** SOURCE07 synthetic parser/IPC/browser fixtures; never native acceptance. */
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {artifactSourceFixture} from './fixtures/h041-artifact-source-fixture.js';import {verifyManifestSourceIdentity} from '../../acceptance/compaction/model-artifact-identity.mjs';import {validateRecord,metadata,measured} from '../../acceptance/compaction/evidence.mjs';import {fixture,makeRecord} from '../../acceptance/compaction/controller.mjs';import {sha256,stableJson,actionIdFor} from '../../acceptance/compaction/scorer.mjs';import {requireFullManualReceipt} from '../../acceptance/compaction/native-adapter/ordinary-runner.js';
test('SOURCE original manifest/separate71+3/current owner bytes are independently parsed, not merged projection claims',()=>{const f=artifactSourceFixture();assert.equal(verifyManifestSourceIdentity(f.receipt,f.expected).status,'SOURCE_VALID');for(const name of ['manifest','pass71','pass3','current']){const x=structuredClone(f.producer);x.captures[name].utf8+=' ';const bytes=stableJson(x),r={producerReceiptUtf8:bytes,producerReceiptSha256:sha256(bytes)},e={...f.expected,producerReceiptSha256:r.producerReceiptSha256};assert.equal(verifyManifestSourceIdentity(r,e).status,'FAIL');}const x=structuredClone(f.producer),current=JSON.parse(x.captures.current.utf8);current.files[0].ino++;x.captures.current.utf8=JSON.stringify(current)+'\n';x.captures.current.sha256=sha256(x.captures.current.utf8);const bytes=stableJson(x),r={producerReceiptUtf8:bytes,producerReceiptSha256:sha256(bytes)},e=structuredClone(f.expected);e.producerReceiptSha256=r.producerReceiptSha256;e.captures.current.sha256=x.captures.current.sha256;assert.equal(verifyManifestSourceIdentity(r,e).status,'FAIL');});
test('SOURCE typed native-shape RESULTS sorted write/read roundtrip and full-manual consumer retain NULL origin',async t=>{const dir=await mkdtemp(join(tmpdir(),'h041-typed07-'));t.after(()=>rm(dir,{recursive:true,force:true}));const f=artifactSourceFixture(),verification=verifyManifestSourceIdentity(f.receipt,f.expected),typed={value:null,reason:'SOURCE native revision unknown',identity:verification.identity,artifactEvidence:{receipt:f.receipt,expected:f.expected}},hash=sha256('SOURCE-only receipt'),packet=await fixture(),runId='SOURCE-roundtrip',actionId=actionIdFor(runId,1,'continuation'),compactId=actionIdFor(runId,1,'compact'),runtime={name:'codex',version:metadata('0.158.0'),sourceRevision:metadata('064c6b8c737f5b41d171fdda80bd9ef10ad06eb3'),binarySha256:metadata(hash),model:metadata('qwen3.8-27b'),modelRevision:typed,tokenizerRevision:typed,promptRevision:'kpm-technical-v1'},record=makeRecord({packet,runId,cycle:1,mode:'continuation',qualification:'native',runtime,observation:{outcome:'completed',actionId,nativeThreadId:'SOURCE-parent',nativeTurnId:'SOURCE-turn',durationMs:measured(1,'SOURCE duration',hash),artifacts:{'sensor-policy.json':{},'engineering-calculation.json':{}},settlement:{state:'released',receiptSha256:hash,automaticReplay:false}},compactionObservation:{actionId:compactId,nativeThreadId:'SOURCE-parent',operationWindowId:'SOURCE-window',verifierNativeWindowId:'SOURCE-parent:1',trigger:{type:'manual',evidence:[{kind:'manual-action',ref:'SOURCE-only fixture',sha256:hash,runId,actionId:compactId,nativeThreadId:'SOURCE-parent'}]}},originals:{beforeSha256:hash,afterSha256:hash,recoverable:true,receiptSha256:hash},grade:{status:'PASS',errors:[],failures:[]}});assert.equal(record.status,'PASS');assert.deepEqual(validateRecord(record),[]);const result={qualification:'native',profile:'h041-full-retention-v1',status:'PASS',nativeAcceptance:'PASS',semanticAcceptance:'PASS',runId,records:Array.from({length:12},()=>record)},bytes=stableJson(result);await writeFile(join(dir,'SOURCE-RESULTS.json'),bytes);const reread=await readFile(join(dir,'SOURCE-RESULTS.json'),'utf8');assert.deepEqual(validateRecord(JSON.parse(reread).records[0]),[]);assert.equal(requireFullManualReceipt(reread,sha256(reread)).records[0].runtime.modelRevision.value,null);const changed=JSON.parse(reread);changed.records[0].runtime.modelRevision.identity.revision='b'.repeat(40);const bad=stableJson(changed);assert.throws(()=>requireFullManualReceipt(bad,sha256(bad)));});

import {automaticFrames} from '../../acceptance/compaction/automatic-evidence.mjs';
import {NormalProductProducer} from '../../acceptance/compaction/native-adapter/normal-product.js';
import {NormalOrdinaryHost} from '../../acceptance/compaction/native-adapter/normal-host.js';
import {verifyBrowserHumanReceipt} from '../../acceptance/compaction/native-adapter/browser-evidence.js';
import {AUTHORIZATIONS} from '../../acceptance/compaction/authorization.mjs';
const sourceReview=()=>{const a=AUTHORIZATIONS['H041-COMPACTION-DELIVERY-04'];return {authorization:{...a,windowId:'SOURCE-only'},notAfterUtc:a.capUtc,settlementReserveMs:120000};};
test('SOURCE actual AUTO native frame shape survives durable stableJson reread; raw tamper fails',()=>{
 const thread='SOURCE-parent',turn='SOURCE-turn',values=[{id:1,method:'turn/start',params:{threadId:thread}},{method:'turn/started',params:{threadId:thread,turn:{id:turn}}},{id:1,result:{turn:{id:turn}}},{method:'item/started',params:{threadId:thread,turnId:turn,item:{id:'SOURCE-auto',type:'contextCompaction'}}},{method:'item/completed',params:{threadId:thread,turnId:turn,item:{id:'SOURCE-auto',type:'contextCompaction'}}},{method:'turn/completed',params:{threadId:thread,turn:{id:turn,status:'completed'}}}],frames=values.map((value,sequence)=>{const bytesUtf8=JSON.stringify(value)+'\n';return {bytesUtf8,sha256:sha256(bytesUtf8),value,sequence,direction:sequence===0?'to-native':'from-native',observedAt:'2026-10-01T12:30:00Z'};});
 const persisted=JSON.parse(stableJson(frames));assert.equal(automaticFrames(persisted,thread,turn).start.sequence,3);persisted[3].bytesUtf8=persisted[3].bytesUtf8.replace('SOURCE-auto','FOREIGN');assert.throws(()=>automaticFrames(persisted,thread,turn));
});
test('SOURCE automatic readiness stays unavailable before dispatch without actual pinned history estimator',t=>{
 t.mock.method(Date,'now',()=>Date.parse('2026-10-01T13:00:00Z'));const plan={autoCompactTokenLimit:400000},p=new NormalProductProducer({sessionId:'SOURCE-session',hostPrivate:'/SOURCE',review:{...sourceReview(),automaticPlan:plan}},{qualificationSha256:sha256('SOURCE-packet')} as any);assert.equal(p.prepareAutomatic(plan,new AbortController().signal).generationAllowed,false);assert.throws(()=>p.prepareAutomatic({...plan,autoCompactTokenLimit:399999},new AbortController().signal));
});
test('SOURCE actual connected fault bridge consumes distinct manual endpoint and real controller checkpoint shape',async t=>{
 t.mock.method(Date,'now',()=>Date.parse('2026-10-01T13:00:00Z'));const calls:any[]=[],base={sessionId:'SOURCE-session'},checkpoint={id:'SOURCE-checkpoint',runId:'SOURCE-run',status:'recovery_required',verification:{status:'rejected',physicalCompactions:['SOURCE-compact']}},runner={call:async(method:string,args:any)=>{calls.push({method,args});if(method==='baseline')return base;if(method==='settleRun')return {nativeOutcome:'failed'};if(method==='recoveryRows')return {checkpointUtf8:stableJson(checkpoint)};return {armed:true};}},browser={request:async(path:string,init:any)=>{calls.push({path,init});return {status:202,bodyBytes:Buffer.from(JSON.stringify({runId:'SOURCE-run'}))};}};
 const d=mkdtempSync(join(tmpdir(),'h041-connected-source-'));t.after(()=>rmSync(d,{recursive:true,force:true}));const host=new NormalOrdinaryHost({} as any,runner as any,browser as any,{sessionId:'SOURCE-session',hostPrivate:d,review:sourceReview()}),result=await host.createVerificationFault('SOURCE-session',{kind:'manual-replacement-verification'},base,new AbortController().signal);assert.equal(result.checkpointId,checkpoint.id);assert.equal(calls[0].method,'armVerificationFault');assert.equal(calls[0].args.baseline,base);const sent=calls.find(c=>c.path);assert.equal(sent.path,'/api/sessions/SOURCE-session/compact');assert.ok(JSON.parse(sent.init.bodyUtf8).actionId);assert.equal(calls.find(c=>c.method==='recoveryRows').args.runId,'SOURCE-run');
});
test('SOURCE protected human receipt verifies actual CDP press/release ACK and same network request',()=>{
 const calls=['mousePressed','mouseReleased'].map((type,id)=>{const requestUtf8=JSON.stringify({id,method:'Input.dispatchMouseEvent',params:{type,x:10,y:20,button:'left',clickCount:1}});return {requestUtf8,requestSha256:sha256(requestUtf8),responseUtf8:JSON.stringify({id,result:{}})};}),r={source:'owned-protected-browser-memory-review',sessionId:'SOURCE-session',requestId:'SOURCE-network',responseRequestId:'SOURCE-network',requestPath:'/api/sessions/SOURCE-session/memory/accept',method:'POST',status:200,requestBodyUtf8:JSON.stringify({proposalId:'SOURCE-proposal',expectedVersion:null}),actionReceiptUtf8:stableJson({action:'click',role:'button',name:'Accept reviewed proposal',observedAtMs:1,cdpCalls:calls})};assert.equal(verifyBrowserHumanReceipt(stableJson(r),'SOURCE-session','SOURCE-proposal',null).status,'SOURCE_VALID');assert.equal(verifyBrowserHumanReceipt(stableJson({...r,responseRequestId:'FOREIGN'}),'SOURCE-session','SOURCE-proposal',null).status,'FAIL');
});
import {NormalBrowser} from '../../acceptance/compaction/native-adapter/normal-browser.js';
test('SOURCE protected recovery CDP completion can exceed10s while ordinary calls cannot; no retry',async t=>{
 t.mock.method(Date,'now',()=>Date.parse('2026-10-01T13:00:00Z'));t.mock.timers.enable({apis:['setTimeout']});const browser=new NormalBrowser({review:sourceReview(),webSocketUrl:'ws://127.0.0.1:9222/devtools/page/SOURCE-target',origin:'https://source.invalid',sessionId:'SOURCE-session'});let call:any;(browser as any).socket={send:(s:string)=>{call=JSON.parse(s);},close:()=>{}};const signal=new AbortController().signal,p=browser.request('/api/sessions/SOURCE-session/memory/recovery/SOURCE-checkpoint/recover',{method:'POST',bodyUtf8:'{}',signal});t.mock.timers.tick(11000);assert.equal((browser as any).pending.size,1);(browser as any).pending.get(call.id).resolve({result:{value:{status:200,text:'{}'}}});assert.equal((await p).status,200);const ordinary=browser.command('Runtime.enable',{},signal);const rejected=assert.rejects(ordinary,/timeout/);t.mock.timers.tick(10001);await rejected;browser.close();
});
