/** Synthetic actual ledger/default recovery composition; no Linux/native acceptance. */
import test,{type TestContext} from "node:test";import assert from "node:assert/strict";import {DatabaseSync} from "node:sqlite";import {mkdtempSync,realpathSync,chmodSync,rmSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {PassThrough} from "node:stream";
import {GatewayOwnership,GatewayOwnershipLedger} from "../src/gateway-ownership.js";import {observeGatewayNoGeneration} from "../src/codex-no-generation.js";import {createCodexRecoveryHost} from "../src/codex-recovery.js";import {Store} from "../src/store.js";import {Files} from "../src/files.js";import {CODEX_PIN,type CodexRuntime} from "../src/codex-engine.js";import type {Gateway} from "../src/gateway.js";import {receiptFixture} from "./helpers/codex-receipt-fixture.js";import {validateCodexLaunchReceipt,validateCodexSettlementReceipt} from "../src/codex-receipts.js";
test("real ledger settled removal cannot conceal admission; unrelated sessions do not poison proof",async()=>{const db=new DatabaseSync(":memory:"),ledger=new GatewayOwnershipLedger(db),owner=new GatewayOwnership(ledger.options());owner.registerSession("s");await assert.rejects(()=>observeGatewayNoGeneration("s",()=>owner.admissionObservation("s"),async()=>{const r=owner.begin("s");owner.transition(r,"accepted");owner.transition(r,"settled");assert.deepEqual(owner.snapshot("s"),[]);}),/Provider operation/);const n=owner.admissionObservation("s").sequence;await observeGatewayNoGeneration("s",()=>owner.admissionObservation("s"),async()=>{const r=owner.begin("foreign");owner.transition(r,"settled");});assert.equal(owner.admissionObservation("s").sequence,n);db.close();});
test("durable sequence survives ledger reopening and unknown/restarted/stopped owner rejects",async()=>{const db=new DatabaseSync(":memory:"),ledger=new GatewayOwnershipLedger(db);let owner=new GatewayOwnership(ledger.options());owner.registerSession("s");const r=owner.begin("s");owner.transition(r,"settled");const sequence=owner.admissionObservation("s").sequence;owner=new GatewayOwnership(ledger.options());owner.registerSession("s");assert.equal(owner.admissionObservation("s").sequence,sequence);await assert.rejects(()=>observeGatewayNoGeneration("s",()=>owner.admissionObservation("s"),async()=>{owner=new GatewayOwnership(ledger.options());owner.registerSession("s");}),/Provider operation/);await assert.rejects(()=>observeGatewayNoGeneration("unknown",()=>owner.admissionObservation("unknown"),async()=>null));owner.stopObservation();await assert.rejects(()=>observeGatewayNoGeneration("s",()=>owner.admissionObservation("s"),async()=>null));db.close();});
test("non-durable and failed-write ownership cannot mint proof",async()=>{const owner=new GatewayOwnership({recoveryReady:true,onRequestState:()=>{}});owner.registerSession("s");assert.throws(()=>owner.admissionObservation("s"),/Durable/);const db=new DatabaseSync(":memory:"),ledger=new GatewayOwnershipLedger(db),options=ledger.options(),broken=new GatewayOwnership({...options,onRequestState:()=>{throw Error("disk");}});broken.registerSession("s");assert.throws(()=>broken.begin("s"));await assert.rejects(()=>observeGatewayNoGeneration("s",()=>broken.admissionObservation("s"),async()=>null));db.close();});
function setup(t:TestContext){const root=realpathSync(mkdtempSync(join(tmpdir(),"h041-recovery-"))),store=new Store(join(root,"harness.sqlite"));chmodSync(store.databasePath,0o600);const files=new Files(root,store),session=store.createSession(undefined,"codex",{engineVersion:CODEX_PIN.version,modelPolicyVersion:"recovery-fixture"});store.setNative(session.id,"old-retained-parent","codex");store.setNativeState(session.id,"codex",{ownership:"idle",activeTurnId:null,eventCursor:11});const run=store.createRun(session,"message","synthetic",[]),cp=store.checkpoints.prepare(session.id,run.id,"message","old-retained-parent");store.checkpoints.finish(session.id,run.id,"failed");store.updateRun(run.id,"failed");store.checkpoints.acknowledge(session.id,cp.id,"Synthetic human correction");const owner=new GatewayOwnership(new GatewayOwnershipLedger(store.db).options());let issued=0,revoked=0;const gateway:Pick<Gateway,"issueToken"|"revokeToken"|"observeNoGeneration">={issueToken:()=>{issued++;owner.registerSession(session.id);return "synthetic-owned-token";},revokeToken:()=>{revoked++;},observeNoGeneration:<T>(id:string,work:()=>Promise<T>)=>observeGatewayNoGeneration(id,()=>owner.admissionObservation(id),work)};const runtime:CodexRuntime={pin:CODEX_PIN,protocolQualified:true,nativeReceiptsRequired:true,ordinaryMemoryAdmission:async()=>{},modelPolicyVersion:"recovery-fixture",model:"qwen3.8-27b",provider:"sova",gatewayUrl:"http://10.0.2.2:8081/v1",contextLimit:480000,launchRootless:async()=>{throw Error("Synthetic launch reached");},revokeGatewaySession:()=>{},confirmGatewaySettlement:async()=>true};t.after(()=>{store.close();rmSync(root,{recursive:true,force:true});});return {store,files,session,cp,runtime,gateway,host:()=>createCodexRecoveryHost({store,files,runtime,gateway:()=>gateway,launcher:"/NEVER-EXECUTED",dispatchHeld:()=>false}),input:{signal:new AbortController().signal,reservation:store.reserveWorkspaceRecovery(session.id,cp.id),sessionId:session.id,checkpointId:cp.id,memory:store.memory.bridge(session.id)},counts:()=>({issued,revoked})};}
test("normal recovery default real constructor receives stored metadata and keeps old parent on launch failure",async t=>{const f=setup(t);await assert.rejects(()=>f.host()(f.input),/Synthetic launch reached/);assert.deepEqual(f.counts(),{issued:1,revoked:1});assert.equal(f.store.getSession(f.session.id).nativeSessionId,"old-retained-parent");assert.equal(f.store.checkpoints.status(f.session.id)[0].status,"recovery_required");});
test("real constructor policy fault revokes issued token before any native start",async t=>{const f=setup(t),runtime={...f.runtime,provider:"foreign"};const host=createCodexRecoveryHost({store:f.store,files:f.files,runtime,gateway:()=>f.gateway,launcher:"/NEVER-EXECUTED",dispatchHeld:()=>false});await assert.rejects(()=>host(f.input),/runtime policy/);assert.deepEqual(f.counts(),{issued:1,revoked:1});});
test("real normal recovery initializes only a fresh thread then cleans up; synthetic receipts cannot grant acceptance",async t=>{const f=setup(t),requests:string[]=[],stdin=new PassThrough(),stdout=new PassThrough(),rf=receiptFixture();let launch=rf.launch,settlement=rf.settlement,exit!:()=>void;const exited=new Promise<void>(r=>{exit=r;});f.runtime.launchRootless=async input=>{const serialized=JSON.stringify(rf.rawLaunch).replaceAll("/task/profile",input.profileDir).replaceAll("/task/workspace",input.workspace).replaceAll("session-1",input.sessionId);const binding={...rf.binding,profileDir:input.profileDir,workspace:input.workspace,sessionId:input.sessionId};launch=validateCodexLaunchReceipt(JSON.parse(serialized),binding,rf.producer,rf.now);const raw={...rf.rawSettlement,sessionId:input.sessionId};settlement=validateCodexSettlementReceipt(raw,binding,launch,rf.now+1);return {stdin,stdout,exited,launchReceipt:Promise.resolve(launch),settlementReceipt:Promise.resolve(settlement),terminateAndConfirm:async()=>{exit();return true;}};};stdin.on("data",chunk=>{for(const line of String(chunk).trim().split("\n")){const p=JSON.parse(line);if(!p.id)continue;requests.push(p.method);const result=p.method==="initialize"?{codexHome:f.files.profile(f.session.id)+"/codex-home",platformOs:"linux",platformFamily:"unix",userAgent:"codex/0.158.0"}:{thread:{id:"fresh-source-parent",path:"/private/synthetic-rollout"},model:"qwen3.8-27b",modelProvider:"sova",cwd:f.files.workspace(f.session.workspaceId),approvalPolicy:"never"};stdout.write(JSON.stringify({id:p.id,result})+"\n");}});await assert.rejects(()=>f.host()(f.input),/observations incomplete/);assert.deepEqual(requests,["initialize","thread/start"]);assert.deepEqual(f.counts(),{issued:1,revoked:1});assert.equal(f.store.getSession(f.session.id).nativeSessionId,"old-retained-parent");});

import {Broker} from "../src/broker.js";
function brokerFor(f:ReturnType<typeof setup>){return new Broker({store:f.store,files:f.files,engineFactory:()=>{throw Error("Synthetic unrelated runner");},launcher:"/NEVER",gatewayUrl:"http://127.0.0.1",issueToken:()=>"fixture",revokeToken:()=>{}});}
test("actual Broker blocks sibling workspace during real recovery prepare; unrelated workspace stays usable",async t=>{
 const f=setup(t);f.store.finishWorkspaceRecovery(f.input.reservation,false);const sibling=f.store.createSession(f.session.workspaceId),other=f.store.createSession(),broker=brokerFor(f);
 let entered!:()=>void,release!:()=>void;const preparing=new Promise<void>(r=>entered=r),blocked=new Promise<void>(r=>release=r);f.files.prepare=async()=>{entered();await blocked;};
 const recovery=broker.recoverMemory(f.session.id,f.cp.id,f.host());const rejected=assert.rejects(recovery,/Synthetic launch reached/);await preparing;
 assert.throws(()=>broker.enqueue(sibling.id,"message","no sibling dispatch"),/recovery owner/);
 assert.ok(broker.enqueue(other.id,"message","unrelated allowed"));assert.equal(f.store.db.prepare("SELECT id FROM runs WHERE session_id=?").get(sibling.id),undefined);
 release();await rejected;assert.equal(f.counts().revoked,1);assert.equal(f.store.workspaceRecoveryBlocked(f.session.workspaceId),f.store.isQuarantined(f.session.workspaceId)||f.store.getSession(f.session.id).nativeState.ownership!=="idle");await broker.close();
});
test("shared reservation remains held through Store CAS and releases after safe CAS failure",async t=>{
 const f=setup(t);f.store.finishWorkspaceRecovery(f.input.reservation,false);const sibling=f.store.createSession(f.session.workspaceId),broker=brokerFor(f);
 f.store.checkpoints.recoverWithFreshParent=()=>{assert.equal(f.store.workspaceRecoveryBlocked(f.session.workspaceId),true);assert.throws(()=>broker.enqueue(sibling.id,"message","must wait CAS"),/recovery owner/);throw Error("Synthetic CAS fault");};
 await assert.rejects(broker.recoverMemory(f.session.id,f.cp.id,async()=>({} as import("../src/session-checkpoint.js").FreshParentRecoveryEvidence)),/Synthetic CAS fault/);
 assert.equal(f.store.workspaceRecoveryBlocked(f.session.workspaceId),false);await broker.close();
});
test("constructor failure releases shared reservation and unresolved cold reservation is never replayed",async t=>{
 const f=setup(t);f.store.finishWorkspaceRecovery(f.input.reservation,false);const broker=brokerFor(f);const badHost=createCodexRecoveryHost({store:f.store,files:f.files,runtime:{...f.runtime,provider:"foreign"},gateway:()=>f.gateway,launcher:"/NEVER",dispatchHeld:()=>false});
 await assert.rejects(broker.recoverMemory(f.session.id,f.cp.id,badHost),/runtime policy/);assert.equal(f.store.workspaceRecoveryBlocked(f.session.workspaceId),false);assert.deepEqual(f.counts(),{issued:1,revoked:1});
 const reservation=f.store.reserveWorkspaceRecovery(f.session.id,f.cp.id);assert.throws(()=>f.store.assertWorkspaceRecovery({...reservation},f.session.id,f.cp.id));const reopened=new Store(f.store.databasePath);try{assert.equal(reopened.workspaceRecoveryBlocked(f.session.workspaceId),true);assert.throws(()=>reopened.reserveWorkspaceRecovery(f.session.id,f.cp.id),/recovery owner/);}finally{reopened.close();}await broker.close();
});

test("normal Broker shutdown waits recovery cancellation before releasing owner or gateway",async t=>{
 const f=setup(t);f.store.finishWorkspaceRecovery(f.input.reservation,false);const broker=brokerFor(f);let entered!:()=>void,release!:()=>void;const preparing=new Promise<void>(r=>entered=r),blocked=new Promise<void>(r=>release=r);f.files.prepare=async()=>{entered();await blocked;};
 const recovery=broker.recoverMemory(f.session.id,f.cp.id,f.host()),rejected=assert.rejects(recovery,/shutdown/);await preparing;let closed=false;const closing=broker.close().then(()=>{closed=true;});await Promise.resolve();assert.equal(closed,false);assert.equal(f.store.workspaceRecoveryBlocked(f.session.workspaceId),true);release();await rejected;await closing;assert.equal(f.counts().issued,0);assert.equal(f.store.workspaceRecoveryBlocked(f.session.workspaceId),false);await assert.rejects(broker.recoverMemory(f.session.id,f.cp.id,f.host()),/active work/);
});
