/** Synthetic source/SQLite/filesystem checks; never native semantic acceptance. */
import test,{type TestContext} from "node:test";
import assert from "node:assert/strict";
import {mkdtempSync,rmSync,chmodSync,realpathSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createHash} from "node:crypto";
import {Readable} from "node:stream";
import {Store} from "../src/store.js";
import {Files} from "../src/files.js";
import {executeSessionCheck,type AcceptedStateDraft} from "../src/session-memory.js";
import {validateSessionRestartOwnership} from "../src/session-checkpoint.js";
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
function setup(t:TestContext){const root=realpathSync(mkdtempSync(join(tmpdir(),"h041-memory-"))),db=join(root,"harness.sqlite"),store=new Store(db);chmodSync(db,0o600);const session=store.createSession(undefined,"codex");t.after(()=>{try{store.close();}catch{}rmSync(root,{recursive:true,force:true});});return {root,db,store,session};}
function draft(ref?:{id:string;sha256:string}):AcceptedStateDraft{return {objective:"Maintain 480000 tokens; do not authorize deployment",constraints:[{id:"limit",text:"Do not raise the output ceiling",units:"tokens",negated:true,permissionBoundary:true,sources:ref?[ref]:[]}],decisions:[{id:"route",text:"Keep existing route",status:"current",sources:[]}],pending:[{id:"review",text:"Review native proof",owner:"root",status:"blocked",sources:[]}],checks:[{id:"source",claim:"passed",sources:ref?[ref]:[]}]};}
test("original lookup denies foreign session and paths, and preserves exact source bytes",t=>{const {store,session}=setup(t),other=store.createSession();const raw="\uFEFF4.8 µA; do NOT start";const r=store.memory.retain(session.id,"message","msg",Buffer.from(raw));assert.equal(r.sha256,hash(raw));assert.equal(store.memory.read(session.id,r.id,0,8192).text,raw);assert.throws(()=>store.memory.read(other.id,r.id,0,12),/not found/);assert.throws(()=>store.memory.read(session.id,"/etc/auth.json",0,12));assert.equal(store.memory.retain(session.id,"message","msg",Buffer.from(raw)).id,r.id);});
test("UTF-8 reads reject split offsets, trim end without replacing bytes, and preserve BOM",t=>{const {store,session}=setup(t),r=store.memory.retain(session.id,"message","utf8",Buffer.from("a€𐍈z"));assert.equal(store.memory.read(session.id,r.id,0,3).text,"a");assert.equal(store.memory.read(session.id,r.id,1,3).text,"€");assert.throws(()=>store.memory.read(session.id,r.id,2,8),/boundary/);assert.throws(()=>store.memory.read(session.id,r.id,1,1));assert.equal(store.memory.read(session.id,r.id,8,1).text,"z");});
for(const availability of ["legacy_display_only","native_truncated","missing","protected"] as const)test(`unavailable full original ${availability}`,t=>{const {store,session}=setup(t),r=store.memory.retain(session.id,"tool","legacy",undefined,availability);assert.equal(r.availability,availability);assert.throws(()=>store.memory.read(session.id,r.id,0,10),/unavailable/);});
test("binary original stays hashed but is unavailable as text",t=>{const {store,session}=setup(t),r=store.memory.retain(session.id,"file","binary",Uint8Array.from([255]));assert.equal(r.availability,"not_utf8");assert.ok(r.sha256);assert.throws(()=>store.memory.read(session.id,r.id,0,8));});
test("bounded search is literal, session-predicated and advances past oversized originals",t=>{const {store,session}=setup(t);const other=store.createSession();store.memory.retain(other.id,"message","foreign",Buffer.from("needle [.*]"));const huge=store.memory.retain(session.id,"file","huge",Buffer.alloc(9*1024*1024,97));const r=store.memory.retain(session.id,"message","owned",Buffer.from("µA [.*] exact"));const result=store.memory.search(session.id,"[.*]");assert.equal(result.hits.length,1);assert.equal(result.hits[0]!.id,r.id);assert.equal(result.hits[0]!.offset,4);assert.equal(result.skipped[0]!.id,huge.id);assert.ok(result.nextAfter>0);assert.equal(store.memory.search(session.id,"[.*]",{after:result.nextAfter}).hits.length,0);assert.throws(()=>store.memory.search(session.id,"needle",{reference:store.memory.view(other.id).references[0]!.id}));});
test("model proposal cannot promote claimed PASS and corrections retain previous immutable versions",t=>{const {store,session}=setup(t);const p=store.memory.propose(session.id,draft());assert.equal(store.memory.current(session.id),null);const v=store.memory.acceptHuman(session.id,p.id,null);assert.equal(v.trustedChecks[0]!.status,"unknown");const correction=draft();correction.decisions[0]!.status="superseded";correction.decisions.push({id:"route_corrected",text:"Keep route after review",status:"current",supersedes:"route",sources:[]});const next=store.memory.acceptHuman(session.id,store.memory.propose(session.id,correction).id,v.id);assert.equal(next.parentId,v.id);assert.equal(store.memory.versions(session.id)[0]!.state.decisions[0]!.status,"current");assert.equal(next.state.constraints[0]!.units,"tokens");assert.equal(next.state.constraints[0]!.negated,true);assert.equal(next.state.pending[0]!.owner,"root");});
test("changing or dropping an old decision identity is rejected",t=>{const {store,session}=setup(t),v=store.memory.acceptHuman(session.id,store.memory.propose(session.id,draft()).id,null);for(const mutate of [(d:AcceptedStateDraft)=>d.decisions[0]!.text="Changed under old ID",(d:AcceptedStateDraft)=>d.decisions=[]]){const d=draft();mutate(d);assert.throws(()=>store.memory.acceptHuman(session.id,store.memory.propose(session.id,d).id,v.id));}assert.equal(store.memory.current(session.id)!.id,v.id);});
for(const [field,value] of [["status",["current"]],["status",{}]] as const)test(`genuine enum strings required ${JSON.stringify(value)}`,t=>{const {store,session}=setup(t),d=draft();Object.assign(d.decisions[0]!,{[field]:value});assert.throws(()=>store.memory.propose(session.id,d));});
test("concurrent stale promotions CAS exactly one current pointer",t=>{const {store,session}=setup(t),a=store.memory.propose(session.id,draft()),b=store.memory.propose(session.id,draft());const winner=store.memory.acceptHuman(session.id,a.id,null);assert.throws(()=>store.memory.acceptHuman(session.id,b.id,null),/changed/);assert.equal(store.memory.versions(session.id).length,1);assert.equal(store.memory.current(session.id)!.id,winner.id);});
test("host checks bind exact sources/build, keep failed/unknown status and reject JSON rebranding",async t=>{const {store,session}=setup(t),r=store.memory.retain(session.id,"file","source",Buffer.from("v1")),ref={id:r.id,sha256:r.sha256!},build=hash("build");const d=draft(ref);d.checks=[{id:"pass",claim:"passed",sources:[ref],buildSha256:build},{id:"fail",claim:"passed",sources:[ref],buildSha256:build},{id:"unknown",claim:"passed",sources:[ref],buildSha256:build}];for(const [id,exit] of [["pass",0],["fail",1],["unknown",null]] as const){const receipt=await executeSessionCheck({sessionId:session.id,id,command:["synthetic-host-check"],sources:[ref],buildSha256:build,execute:async()=>({exit,logSha256:hash(id)})});assert.throws(()=>store.memory.recordTrustedCheck(structuredClone(receipt)));store.memory.recordTrustedCheck(receipt);}const v=store.memory.acceptHuman(session.id,store.memory.propose(session.id,d).id,null);assert.deepEqual(v.trustedChecks.map(c=>c.status),["passed","failed","unknown"]);store.memory.retain(session.id,"file","source",Buffer.from("v2"));const updated=store.memory.acceptHuman(session.id,store.memory.propose(session.id,d).id,v.id);assert.deepEqual(updated.trustedChecks.map(c=>c.status),["unknown","unknown","unknown"]);});
test("cold reopened database retains originals/accepted state without history replay",t=>{const {store,session,db}=setup(t),r=store.memory.retain(session.id,"message","stable",Buffer.from("original µA"));const v=store.memory.acceptHuman(session.id,store.memory.propose(session.id,draft()).id,null);store.close();const reopened=new Store(db);try{assert.equal(reopened.memory.read(session.id,r.id,0,8192).text,"original µA");assert.equal(reopened.memory.current(session.id)!.id,v.id);assert.equal(reopened.memory.bridge(session.id).continuationText().includes("permissionBoundary"),true);}finally{reopened.close();}});
test("exact-session failed replacement blocks continuation even after physical release",t=>{const {store,session}=setup(t),other=store.createSession(undefined,"codex"),run=store.createRun(session,"compact","",[]);const before=store.addMessage(session.id,"user","Keep old history");const cp=store.checkpoints.prepare(session.id,run.id,"compact","native-parent");assert.ok(cp.originalInventory.sha256);store.checkpoints.observeCompaction(session.id,run.id,"native-compaction","start");store.checkpoints.finish(session.id,run.id,"failed");store.releaseQuarantineAfterVerifiedCleanup(session.workspaceId);assert.throws(()=>store.memory.bridge(session.id).assertContinuationAllowed(),/uncertain/);store.memory.bridge(other.id).assertContinuationAllowed();assert.equal(store.message(before.id).content,"Keep old history");assert.deepEqual(store.checkpoints.acknowledge(session.id,cp.id,"reviewed preserved originals").continuationBlocked,true);assert.throws(()=>store.memory.bridge(session.id).assertContinuationAllowed());});
test("before-dispatch inventory/state corruption fails closed on apparently completed native outcome",t=>{const {store,session}=setup(t),r=store.memory.retain(session.id,"message","keep",Buffer.from("keep")),run=store.createRun(session,"message","request",[]);store.checkpoints.prepare(session.id,run.id,"message");store.db.prepare("UPDATE h041_originals SET sha256=? WHERE id=?").run(hash("changed"),r.id);const result=store.checkpoints.finish(session.id,run.id,"completed");assert.equal(result.status,"recovery_required");});
test("restart preserves interrupted checkpoint as recovery_required and rejects serialized authority",t=>{const {store,session,db}=setup(t),run=store.createRun(session,"message","do not replay",[]);store.checkpoints.prepare(session.id,run.id,"message");store.updateRun(run.id,"running");store.close();const reopened=new Store(db);try{assert.equal(reopened.checkpoints.status(session.id)[0]!.status,"recovery_required");assert.throws(()=>validateSessionRestartOwnership({sessionId:session.id,runId:run.id,checkpointId:"fake",threadId:"fake"}));assert.throws(()=>reopened.checkpoints.issueRestartOwnership({sessionId:session.id,runId:run.id,checkpointId:"fake",threadId:"fake"}));}finally{reopened.close();}});
test("registered file originals deny foreign owners and protected runner names",async t=>{const {root,store,session}=setup(t),files=new Files(root,store);await files.init();const other=store.createSession();const f=await files.upload(session.id,"notes.txt","text/plain",Readable.from(["owned file"]));const r=await files.retainOriginal(session.id,f.id);assert.equal(store.memory.read(session.id,r.id,0,8192).text,"owned file");await assert.rejects(files.retainOriginal(other.id,f.id));const protectedFile=await files.upload(session.id,"auth.json","application/json",Readable.from(["synthetic protected fixture"]));assert.equal((await files.retainOriginal(session.id,protectedFile.id)).availability,"protected");});

test("unavailable owned search reference is explicitly incomplete rather than no-match",t=>{const {store,session}=setup(t),r=store.memory.retain(session.id,"tool","old",undefined,"legacy_display_only");const result=store.memory.search(session.id,"required",{reference:r.id});assert.equal(result.incomplete,true);assert.equal(result.skipped[0]!.reason,"legacy_display_only");});
test("trusted check snapshots source/build bindings before awaiting executor",async t=>{const {store,session}=setup(t),r=store.memory.retain(session.id,"file","check-source",Buffer.from("v1"));const sources=[{id:r.id,sha256:r.sha256!}],input={sessionId:session.id,id:"check",command:["original-command"],sources,buildSha256:hash("before"),execute:async()=>{sources[0]!.sha256=hash("mutated");input.buildSha256=hash("after");input.command[0]="changed-command";return {exit:0,logSha256:hash("log")};}};const receipt=await executeSessionCheck(input);assert.equal(receipt.sources[0]!.sha256,r.sha256);assert.equal(receipt.buildSha256,hash("before"));assert.equal(receipt.command[0],"original-command");});

test("session-wide unavailable coverage is explicit rather than complete no-match",t=>{const f=setup(t);const ref=f.store.memory.retain(f.session.id,"tool","legacy-search",undefined,"legacy_display_only");const result=f.store.memory.search(f.session.id,"absent");assert.equal(result.incomplete,true);assert.ok(result.skipped.some(r=>r.id===ref.id));});

test("trusted check result extras cannot overwrite pre-dispatch identity",async t=>{const {store,session}=setup(t),ref=store.memory.retain(session.id,"message","binding",Buffer.from("source"));const receipt=await executeSessionCheck({sessionId:session.id,id:"check",command:["bounded"],sources:[{id:ref.id,sha256:ref.sha256!}],buildSha256:hash("build"),execute:async()=>({exit:0,logSha256:hash("log"),sessionId:"foreign",sources:[],command:["forged"],buildSha256:hash("wrong")})});assert.equal(receipt.sessionId,session.id);assert.deepEqual(receipt.command,["bounded"]);assert.equal(receipt.sources[0].sha256,ref.sha256);assert.equal(receipt.buildSha256,hash("build"));});
