/** Synthetic source guards only; no native trace or Linux transport qualification. */
import test from 'node:test';import assert from 'node:assert/strict';
import {realpathSync,mkdtempSync,mkdirSync,writeFileSync,chmodSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,dirname} from 'node:path';import {createHash} from 'node:crypto';
import {CODEX_RECEIPT_SOURCES,assertCodexReceiptSourceClosure,validateCodexTraceReceipt} from '../src/codex-receipts.js';
import {receiptFixture} from './helpers/codex-receipt-fixture.js';
import {createRootlessCodexLauncher} from '../src/codex-launcher.js';
test('actual receipt ancestry guard reproduces0775 failure before launch and accepts0755 byte-identical closure',()=>{const root=realpathSync(mkdtempSync(join(tmpdir(),'h041-preflight-'))),deploy=join(root,'deploy'),hashes:Record<string,string>={};try{for(const p of CODEX_RECEIPT_SOURCES){const file=join(deploy,p);mkdirSync(dirname(file),{recursive:true,mode:0o755});writeFileSync(file,'source',{mode:0o644});hashes[p]=createHash('sha256').update('source').digest('hex');}chmodSync(deploy,0o775);assert.throws(()=>assertCodexReceiptSourceClosure(deploy,hashes),/ancestry/);chmodSync(deploy,0o755);assert.deepEqual(assertCodexReceiptSourceClosure(deploy,hashes),hashes);chmodSync(join(deploy,'engine'),0o775);assert.throws(()=>assertCodexReceiptSourceClosure(deploy,hashes),/ancestry/);}finally{rmSync(root,{recursive:true,force:true});}});
test('validator JSON even genuine-shaped launch/settlement fixtures cannot grant original trace provenance',()=>{const f=receiptFixture();assert.throws(()=>validateCodexTraceReceipt({schema:'codex-native-trace-v1'}, {...f.binding,nativeTraceMode:'post-sampling-token-usage-v1'},f.launch,f.settlement),/Unbound/);});
test('trace opt-in remains unavailable through unqualified native launcher on Mac',async()=>{await assert.rejects(createRootlessCodexLauncher('/source/deploy/run-codex.sh')({sessionId:'s',profileDir:'/task/p',workspace:'/task/w',codexHome:'/task/p/codex-home',gatewayUrl:'http://10.0.2.2:8081/v1',gatewayToken:'synthetic',modelPolicyVersion:'sova-codex-0.158.0-qwen-text-v2',nativeTraceMode:'post-sampling-token-usage-v1'}));});

import {composeCodexProductObservers} from '../src/codex-product-observation.js';import {composeCodexHost} from '../src/codex-host.js';
test('actual normal trusted observer composition forwards fixed mode and receipt callback to real host runtime; ordinary defaults stay absent',()=>{const base={protocolQualified:true as const,rootlessQualified:true as const,verifyLane:async()=>{throw Error('unused');}};const ordinary=composeCodexHost('/source/deploy/run-codex.sh',()=>undefined,composeCodexProductObservers(base,undefined));assert.equal(ordinary.runtime.nativeTraceMode,undefined);let captured:unknown;const observed=composeCodexHost('/source/deploy/run-codex.sh',()=>undefined,composeCodexProductObservers(base,undefined,{nativeTraceMode:'post-sampling-token-usage-v1',onNativeTraceReceipt:r=>{captured=r;}}));assert.equal(observed.runtime.nativeTraceMode,'post-sampling-token-usage-v1');const marker={} as never;observed.runtime.onNativeTraceReceipt!(marker);assert.equal(captured,marker);});
import {CODEX_H041_DELIVERY04_WINDOW,CODEX_H041_DELIVERY05_WINDOW} from '../src/codex-probe.js';
test('distinct05 frozen root authority leaves04 cap and reserve unchanged',()=>{assert.equal(CODEX_H041_DELIVERY04_WINDOW.expiresAtMs,Date.parse('2026-10-01T15:26:45.729698Z'));assert.equal(CODEX_H041_DELIVERY05_WINDOW.startAtMs,Date.parse('2026-10-01T14:30:02.674394Z'));assert.equal(CODEX_H041_DELIVERY05_WINDOW.expiresAtMs,Date.parse('2026-10-01T18:30:02.674394Z'));assert.equal(CODEX_H041_DELIVERY05_WINDOW.settlementReserveMs,120000);});

import {assertOrdinaryNoGenerationObservation} from '../src/codex-ordinary-entry.js';
test('unknown no-turn provider count requires explicit complete unchanged original legacy observations, never zero coercion',()=>{const ack={providerRequests:null},expected={launchSha256:'l',settlementSha256:'s',rawProtocolSha256:'p'},before={schema:'legacy-gateway-retained-id-observation-v1',identity:{pid:1},requestIds:['old'],retainedRecords:{old:'uncertain'},counts:{uncertain:1},nativeOwners:['ambient']};const result={status:'PASS',validatedInitialize:true,validatedThread:true,requestedStop:true,engineExitStatus:143,cleanupOk:true,receipts:{launch:{sha256:'l'},settlement:{sha256:'s'}},rawProtocolSHA256:'p',gatewayBefore:before,gatewayAfter:structuredClone(before)};assertOrdinaryNoGenerationObservation(ack,result,expected);assert.equal(ack.providerRequests,null);assert.throws(()=>assertOrdinaryNoGenerationObservation(ack,{...result,status:'FAIL'},expected));assert.throws(()=>assertOrdinaryNoGenerationObservation(ack,{...result,gatewayAfter:{...before,requestIds:['old','new']}},expected));assert.throws(()=>assertOrdinaryNoGenerationObservation(ack,{...result,gatewayBefore:{...before,nativeOwners:undefined}},expected));});
