/** SOURCE fixtures: actual Python producer + protected file reader + E consumers.
 * Linux/kernel/native formatter and runtime identities remain synthetic. */
import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,realpathSync,writeFileSync,readFileSync,rmSync} from 'node:fs';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';
import {receiptFixture} from './helpers/codex-receipt-fixture.js';
import {waitCodexReceiptFile,validateCodexLaunchReceipt,validateCodexSettlementReceipt,validateCodexTraceReceipt,getCodexTraceEvents,getCodexTraceUtf8,getCodexRetainedTraceEvidence,getCodexTraceAutoCalls,codexTraceSchemaForMode,codexTraceEnvironment,isVerifiedCodexTraceReceipt,type CodexNativeTraceMode,type CodexReceiptBinding} from '../src/codex-receipts.js';
import {verifyRetainedTrace,verifyNativeStartedAtTraceJoin} from '../../acceptance/compaction/native-trace-evidence.mjs';
import {composeCodexProductObservers} from '../src/codex-product-observation.js';import {composeCodexHost} from '../src/codex-host.js';
const sha=(s:string|Buffer)=>createHash('sha256').update(s).digest('hex'),thread='SOURCE-parent',turn='SOURCE-turn',now=Date.parse('2026-10-01T15:00:00Z');
const task=()=>({name:'turn','thread.id':thread,'turn.id':turn});
const numeric=()=>({timestamp:'2026-10-01T15:00:00.000000001Z',level:'TRACE',target:'codex_core::session::turn',fields:{message:'post sampling token usage',turn_id:turn,total_usage_tokens:400001,auto_compact_scope_tokens:400001,auto_compact_scope_limit:'Some(400000)',auto_compact_limit_scope:'Total',auto_compact_window_prefill_tokens:'None',full_context_window_limit:'Some(480000)',full_context_window_limit_reached:false,token_limit_reached:true,model_needs_follow_up:true,has_pending_input:false,needs_follow_up:true},spans:[task()],span:task()});
const marker=()=>({timestamp:'2026-10-01T15:00:00.000000002Z',level:'TRACE',target:'codex_core::session::turn',fields:{message:'new'},spans:[task()],span:{name:'run_auto_compact',reason:'ContextLimit',phase:'MidTurn'}});
const line=(v:unknown)=>JSON.stringify(v)+'\n';
async function fixture(t:any,mode:Exclude<CodexNativeTraceMode,'off'>='post-sampling-token-usage-v2',raws:unknown[]=[numeric(),marker()]){
 const root=realpathSync(mkdtempSync(join(tmpdir(),'h043-trace-')));t.after(()=>rmSync(root,{recursive:true,force:true}));const f=receiptFixture(),uid=process.getuid!(),gid=process.getgid!(),prefix=`user.slice/user-${uid}.slice/user@${uid}.service/aiharnesstasks.slice`;
 Object.assign(f.binding,{uid,gid,nativeTraceMode:mode});Object.assign(f.producer,{uid,cgroupPath:'/'+prefix+'/fixture.scope'});Object.assign(f.rawLaunch,{producer:f.producer});Object.assign(f.rawLaunch.egress,{uid,cgroupPath:prefix});Object.assign(f.rawLaunch.container,{user:`${uid}:${gid}`});Object.assign(f.rawSettlement,{producer:f.producer});
 const publish=async(name:'launch'|'settlement'|'trace',v:unknown)=>{writeFileSync(join(root,name+'.json'),line(v),{mode:0o600});writeFileSync(join(root,name+'.ready'),'',{mode:0o600});return waitCodexReceiptFile(root,uid,name,100,()=>false);};
 const launch=validateCodexLaunchReceipt(await publish('launch',f.rawLaunch),f.binding,f.producer,f.now),settlement=validateCodexSettlementReceipt(await publish('settlement',f.rawSettlement),f.binding,launch,f.now+1);
 writeFileSync(join(root,'trace-env.json'),line({containerId:launch.container.id,producer:f.producer,nonce:f.binding.nonce,environment:codexTraceEnvironment(mode)}),{mode:0o600});
 const code="import runpy,json,sys;from pathlib import Path;v=json.load(sys.stdin);m=runpy.run_path(v['traceSource']);r=runpy.run_path(v['receiptSource']);c=m['TraceCapture']((Path(v['path']),v['binding']));c.feed(''.join(v['lines']).encode(),final=True);c.publish(r,v['producer'],v['containerId'],v['exit'],True,True)";
 const child=spawnSync('python3',['-c',code],{input:JSON.stringify({traceSource:resolve('../deploy/engine/codex_native_trace.py'),receiptSource:resolve('../deploy/engine/codex_receipts.py'),path:root,binding:f.binding,producer:f.producer,containerId:launch.container.id,exit:settlement.engineExitStatus,lines:raws.map(line)}),encoding:'utf8',timeout:5000});assert.equal(child.status,0,child.stderr);
 const raw=JSON.parse(readFileSync(join(root,'trace.json'),'utf8')),value=await waitCodexReceiptFile(root,uid,'trace',100,()=>false),trace=validateCodexTraceReceipt(value,f.binding,launch,settlement);
 const packet={selectedMode:mode,traceReceiptUtf8:getCodexTraceUtf8(trace)!,traceReceiptSha256:sha(getCodexTraceUtf8(trace)!),launchReceiptUtf8:readFileSync(join(root,'launch.json'),'utf8'),launchReceiptSha256:sha(readFileSync(join(root,'launch.json'))),settlementReceiptUtf8:readFileSync(join(root,'settlement.json'),'utf8'),settlementReceiptSha256:sha(readFileSync(join(root,'settlement.json'))),events:getCodexTraceEvents(trace)!.map(e=>({lineUtf8:e.bytes.toString('utf8')}))};
 const expected={mode,sessionId:f.binding.sessionId,receiptSources:f.binding.sources,traceReceiptSha256:packet.traceReceiptSha256,launchReceiptSha256:packet.launchReceiptSha256,settlementReceiptSha256:packet.settlementReceiptSha256};
 const reread=async(v:any)=>{rmSync(join(root,'trace.json'));rmSync(join(root,'trace.ready'));return publish('trace',v);};return {root,f,launch,settlement,raw,trace,packet,expected,reread};
}
function joinInput(e:ReturnType<typeof getCodexRetainedTraceEvidence>){
 const value={method:'item/started',params:{threadId:thread,turnId:turn,startedAtMs:now,item:{id:'compact-1',type:'contextCompaction'}}},bytesUtf8=line(value),startFrame={direction:'from-native',value,bytesUtf8,sha256:sha(bytesUtf8)};
 return {...e,startFrame,metadata:{request_kind:'compaction',thread_id:thread,turn_id:turn,window_id:thread+':1',window_number:1,context_window_id:'window',compaction:{trigger:'auto',reason:'context_limit',implementation:'responses',phase:'mid_turn'}},operation:{method:'turn/start',nativeThreadId:thread,nativeTurnId:turn,request:{value:{method:'turn/start',params:{threadId:thread}}},ack:{value:{result:{turn:{id:turn}}}},completed:{value:{params:{turn:{status:'completed'}}}},cleanup:{confirmed:true},gateway:{confirmed:true,nativeThreadId:thread,nativeTurnId:turn}},gateway:{nativeThreadId:thread,nativeTurnId:turn,windowId:thread+':1',contextWindowId:'window',state:'settled',requestId:'request'},resolvedConfig:{contextWindow:480000,autoCompactTokenLimit:400000,maxOutputTokens:65536,effectiveScope:'total',tokenBudgetEnabled:false,fallbackBufferTokens:0,postTurnPercent:0}};
}
test('actual source-produced V2 raw events join E with native time/hash and genuine transport projection',async t=>{
 const f=await fixture(t);assert.ok(isVerifiedCodexTraceReceipt(f.trace));const e=getCodexRetainedTraceEvidence(f.trace,'post-sampling-token-usage-v2');assert.equal(e.schema,'codex-native-trace-v2');assert.equal(e.autoCalls.length,1);assert.equal(e.lines[0].lineUtf8,line(numeric()));assert.equal(e.autoCalls[0].lineUtf8,line(marker()));assert.equal(verifyRetainedTrace(f.packet,f.expected).autoCalls.length,1);const j=verifyNativeStartedAtTraceJoin(joinInput(e));assert.equal(j.nativeAcceptance,'NOT_TESTED');assert.equal(j.startedAtMs,now);assert.equal(j.autoCallSha256,sha(line(marker())));if(f.trace.schema==='codex-native-trace-v2')assert.equal(getCodexTraceAutoCalls(f.trace)!.length,1);assert.throws(()=>getCodexRetainedTraceEvidence(f.trace,'post-sampling-token-usage-v1'));
});
test('source V2 empty ARRAY remains V2 and missing AUTO cannot qualify; V1 stays exact without AUTO field',async t=>{
 const f=await fixture(t,'post-sampling-token-usage-v2',[numeric()]);assert.deepEqual(f.raw.autoCalls,[]);const e=getCodexRetainedTraceEvidence(f.trace,'post-sampling-token-usage-v2');assert.equal(e.schema,'codex-native-trace-v2');assert.deepEqual(e.autoCalls,[]);assert.throws(()=>verifyNativeStartedAtTraceJoin(joinInput(e)),/unique_actual_same_owned/);
 const v=await fixture(t,'post-sampling-token-usage-v1',[numeric()]);assert.equal(v.trace.schema,'codex-native-trace-v1');assert.equal('autoCalls' in v.raw,false);assert.equal(verifyRetainedTrace(v.packet,v.expected).mode,'post-sampling-token-usage-v1');
});
test('every original numeric and duplicate/foreign AUTO survives capture and fails causal selection',async t=>{
 const foreign=numeric();foreign.fields.turn_id='foreign';foreign.spans[0]['turn.id']='foreign';foreign.span['turn.id']='foreign';foreign.spans[0]['thread.id']='foreign-thread';foreign.span['thread.id']='foreign-thread';
 for(const raws of [[numeric(),marker(),foreign],[numeric(),marker(),marker()]]){const f=await fixture(t,'post-sampling-token-usage-v2',raws);assert.equal(f.raw.events.length,3);assert.throws(()=>verifyNativeStartedAtTraceJoin(joinInput(getCodexRetainedTraceEvidence(f.trace,'post-sampling-token-usage-v2'))));}
 const auto=marker();auto.spans[0]['thread.id']='foreign';const f=await fixture(t,'post-sampling-token-usage-v2',[numeric(),marker(),auto]);assert.equal(f.raw.autoCalls.length,2);assert.throws(()=>verifyNativeStartedAtTraceJoin(joinInput(getCodexRetainedTraceEvidence(f.trace,'post-sampling-token-usage-v2'))));
});
test('original binding/schema/AUTO index/digest/native-time tampering fails before producer branding',async t=>{
 const f=await fixture(t);for(const mutate of [(v:any)=>delete v.autoCalls,(v:any)=>v.autoCalls=[],(v:any)=>v.schema='codex-native-trace-v1',(v:any)=>v.mode='post-sampling-token-usage-v1',(v:any)=>v.producer.pid++,(v:any)=>v.nonce='foreign',(v:any)=>v.sources['run-codex.sh']='0'.repeat(64),(v:any)=>v.events[0].nativeTimestamp='2099-01-01T00:00:00Z',(v:any)=>v.events[0].sha256='0'.repeat(64),(v:any)=>v.events[0].threadId='foreign']){const raw=structuredClone(f.raw);mutate(raw);const value=await f.reread(raw);assert.throws(()=>validateCodexTraceReceipt(value,f.f.binding,f.launch,f.settlement));assert.equal(isVerifiedCodexTraceReceipt(value),false);}
 const f2=await fixture(t);assert.throws(()=>validateCodexTraceReceipt(f2.trace,{...f2.f.binding,runId:'foreign'},f2.launch,f2.settlement));
 assert.throws(()=>validateCodexTraceReceipt(f2.trace,{...f2.f.binding,nativeTraceMode:'off'},f2.launch,f2.settlement));
});
test('source-only mode/type graph preserves explicit off/null and V1/V2 to actual host engine interface',()=>{
 const base={protocolQualified:true as const,rootlessQualified:true as const,verifyLane:async()=>{throw Error('unused');},nativeTraceMode:'post-sampling-token-usage-v1' as const};
 assert.equal(codexTraceSchemaForMode('off'),null);assert.equal(codexTraceSchemaForMode(undefined),null);assert.throws(()=>codexTraceSchemaForMode('unknown' as never));
 for(const mode of ['off','post-sampling-token-usage-v1','post-sampling-token-usage-v2'] as const){const runtime=composeCodexHost('/source/deploy/run-codex.sh',()=>undefined,composeCodexProductObservers(base,undefined,{nativeTraceMode:mode})).runtime;assert.equal(runtime.nativeTraceMode,mode);assert.equal(codexTraceSchemaForMode(runtime.nativeTraceMode),mode==='off'?null:mode==='post-sampling-token-usage-v1'?'codex-native-trace-v1':'codex-native-trace-v2');}
 assert.throws(()=>getCodexRetainedTraceEvidence({} as never,'post-sampling-token-usage-v2'),/Missing original/);
});
