export const statusHtml = (admin: boolean) =>
  `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${admin ? "Admin" : "Status"} · ai-harness</title><link rel="stylesheet" href="/status-assets/status.css"><script src="/status-assets/status.js" defer></script></head><body data-admin="${admin}"><header><a href="/">ai-harness</a><nav><a href="/status">Status</a>${admin ? '<a href="/admin" aria-current="page">Admin</a>' : ""}<a href="/">Chat</a></nav></header><main><p class="eyebrow">SYSTEM OVERVIEW</p><h1>${admin ? "Service administration" : "Service status"}</h1><p>${admin ? "Any trusted LAN or VPN visitor who can reach this page has the same authority. Review the affected work before confirming an action." : "Passive observations refresh every 5 seconds. Unknown or stale observations do not mean hardware is absent."}</p><p id="notice" role="status">Loading observations…</p><section id="nodes" aria-label="Node status"></section>${admin ? '<section class="panel"><h2>Registered actions</h2><form id="action-form"><label>Target<select id="target" required></select></label><label>Action<select id="action" required></select></label><pre id="impact"></pre><label class="confirm"><input type="checkbox" id="interrupt"> I explicitly allow interruption of the affected work, including work whose activity is unknown.</label><button type="submit" id="submit">Confirm action</button><button type="button" id="refresh-targets">Refresh targets</button></form><p id="action-result" role="status"></p><div id="recovery" hidden><pre id="recovery-impact"></pre><label class="confirm"><input type="checkbox" id="recover-interrupt"> I explicitly allow a new recovery restart or whole-node reboot of this target, including interruption of unknown work. This does not replay the earlier action.</label><button type="button" id="recover">Confirm recovery restart</button></div><p class="muted">Actions are asynchronous. A transport timeout can leave the outcome unknown. An unchanged retry returns the retained receipt. Inspect that result before confirming a recovery restart. Stopped targets stay paused until a validated start. An uncertain action retains its result and pause; a separately confirmed recovery restart can settle it without replay.</p></section>' : ""}</main></body></html>`;
export const statusCss = `:root{font-family:ui-sans-serif,system-ui,sans-serif;color:#172a31;background:#f4f6f6;font-synthesis:none}*{box-sizing:border-box}body{margin:0}header{background:#102d35;color:white;display:flex;justify-content:space-between;padding:20px max(24px,calc((100vw - 1160px)/2))}a{color:inherit}header>a{font-weight:700;text-decoration:none}nav{display:flex;gap:24px}main{max-width:1208px;margin:auto;padding:40px 24px 72px}h1{font-size:38px;letter-spacing:-1px;margin:8px 0 16px}h2{font-size:23px;margin:0 0 12px}h3{font-size:16px}.eyebrow{font-size:12px;font-weight:800;letter-spacing:2px;color:#426e71}.panel{background:white;border:1px solid #d5dfdf;border-radius:10px;padding:24px;margin:22px 0}.muted,small{color:#526b70}table{width:100%;border-collapse:collapse;font-size:14px}td,th{text-align:left;padding:12px 8px;border-bottom:1px solid #e1e7e7;vertical-align:top}th{font-size:12px;text-transform:uppercase;letter-spacing:.6px}.badge{display:inline-block;padding:4px 9px;border-radius:20px;background:#e8edef;font-size:12px}.available,.fresh{background:#d6f1e4;color:#164b35}.unavailable,.stale{background:#ffe9d1;color:#713c07}.unknown{background:#e8edef;color:#475c61}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px}.metric{background:#f4f7f7;padding:12px;font-size:13px}.metric strong{display:block;margin-top:6px;font-size:18px}.metric dl{margin:12px 0 0}.metric dt{color:#526b70}.metric dd{margin:2px 0 10px;font-weight:600}.gpu-cell small{display:block;margin-top:5px;line-height:1.4}.gpu-table td:first-child{min-width:190px}label{display:block;margin:16px 0}select{display:block;width:100%;max-width:500px;padding:10px;margin-top:7px;border:1px solid #b7c8c9;border-radius:5px;background:white;color:inherit;font:inherit}.confirm{max-width:750px;line-height:1.5}button{font:inherit;border:0;background:#14676b;color:white;border-radius:5px;padding:11px 18px;margin-right:10px;cursor:pointer}button:disabled{opacity:.5}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f3f5f5;padding:16px;line-height:1.6}#notice{padding:12px 0;color:#526b70}.table-wrap{overflow-x:auto}@media(max-width:650px){header{padding:18px 20px}nav{gap:14px}h1{font-size:30px}.panel{padding:16px}main{padding:24px 16px}}
`;
export const statusJs = `"use strict";
const $=id=>document.getElementById(id);const admin=document.body.dataset.admin==="true";
const nodeNames={"ai-vm":"AI model server","ai-harness":"Chat and tools host"};
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=String(text);if(cls)e.className=cls;return e;}
function badge(value){return el("span",value||"unknown","badge "+(value||"unknown"));}
function table(headers,rows){const w=el("div",undefined,"table-wrap"),t=el("table"),h=el("tr");headers.forEach(v=>h.append(el("th",v)));t.append(h);rows.forEach(row=>{const tr=el("tr");row.forEach(v=>{const td=el("td");td.append(v instanceof Node?v:document.createTextNode(String(v??"Unknown")));tr.append(td);});t.append(tr);});w.append(t);return w;}
async function json(url,options={}){const r=await fetch(url,{...options,credentials:"same-origin",cache:"no-store",signal:AbortSignal.timeout(5000)});const v=await r.json();if(!r.ok)throw Error(v.error?.message||"Request unavailable");return v;}
function numeric(value,unit="",digits=1){return typeof value==="number"&&Number.isFinite(value)?value.toLocaleString(undefined,{maximumFractionDigits:digits})+unit:"Unknown";}
function bytes(value){if(typeof value!=="number"||!Number.isFinite(value))return "Unknown";const units=["B","KiB","MiB","GiB","TiB"];let i=0;while(value>=1024&&i<units.length-1){value/=1024;i++;}return numeric(value," "+units[i],i?1:0);}
function rate(value){return value==null?"Unknown":bytes(value)+"/s";}
function detail(main,lines=[]){const box=el("div",undefined,"gpu-cell");box.append(el("span",main));for(const line of lines)box.append(el("small",line));return box;}
function rangeInterval(g){const range=numeric(g.temperature_min_c," °C")+" – "+numeric(g.temperature_max_c," °C");if(!g.sampling_since||!g.observed_at)return range+" · interval unknown";return range+" · "+new Date(g.sampling_since).toLocaleTimeString()+"–"+new Date(g.observed_at).toLocaleTimeString();}
function metric(title,observation,rows){const box=el("div",undefined,"metric");box.append(el("strong",title),el("small",observation?.freshness||"unknown"));const list=el("dl");for(const [label,value]of rows){list.append(el("dt",label),el("dd",value));}box.append(list);return box;}
function render(data){
  $("nodes").replaceChildren();
  for(const node of data.nodes){
    const p=el("section",undefined,"panel");p.append(el("h2",nodeNames[node.node_id]||node.node_id),badge(node.freshness),el("p","Observation age: "+(node.age_ms==null?"unknown":Math.round(node.age_ms/1000)+"s")+" · Boot: "+(node.boot_id||"unknown"),"muted"));
    p.append(table(["Service","Availability","Ready / admitting","Activity","Work","Reason"],node.services.map(s=>[s.service_id,badge(s.availability),String(s.ready??"unknown")+" / "+String(s.admitting??"unknown"),s.activity,String(s.active_requests??"?")+" active · "+String(s.queue_depth??"?")+" queued",s.hardware_latched?"Hardware disabled for this boot":s.reason])));
    if(node.gpus.length){const gpuTable=table(["GPU / assignment","Temperature / sampled range","Memory used / total","Power draw / limit","ECC","PCIe current / max"],node.gpus.map(g=>[
      detail(g.name||"Unknown GPU",["UUID …"+g.uuid.slice(-8),(g.affected_services||[]).length?"Assigned: "+g.affected_services.join(", "):"Unassigned"]),
      detail(numeric(g.temperature_c," °C"),[rangeInterval(g)]),
      bytes(g.memory_used_mib==null?null:g.memory_used_mib*1048576)+" / "+bytes(g.memory_total_mib==null?null:g.memory_total_mib*1048576),
      numeric(g.power_draw_w," W")+" / "+numeric(g.power_limit_w," W"),
      detail(g.ecc_mode??"Unknown",["Uncorrected: "+numeric(g.ecc_uncorrected_volatile,"",0)]),
      "Gen "+(g.pcie_generation??"?")+" ×"+(g.pcie_width??"?")+" / Gen "+(g.pcie_generation_max??"?")+" ×"+(g.pcie_width_max??"?")
    ]));gpuTable.classList.add("gpu-table");p.append(el("h3","Graphics hardware"),gpuTable);}
    const {cpu={},memory={},disk={},network={}}=node.resources;const metrics=el("div",undefined,"metrics");
    metrics.append(metric("CPU",cpu,[["Utilization · all CPUs = 100%",numeric(cpu.percent,"%")],["Logical CPUs",numeric(cpu.logical_count,"",0)]]),
      metric("Memory",memory,[["Available / total",bytes(memory.available_bytes)+" / "+bytes(memory.total_bytes)],["Swap free / total",bytes(memory.swap_free_bytes)+" / "+bytes(memory.swap_total_bytes)],["Memory pressure · some / full (10s)",numeric(memory.pressure_some_avg10,"%")+" / "+numeric(memory.pressure_full_avg10,"%")]]),
      metric("Disk · root filesystem",disk,[["Available / total",bytes(disk.available_bytes)+" / "+bytes(disk.total_bytes)],["Read / write",rate(disk.read_bytes_per_second)+" / "+rate(disk.write_bytes_per_second)]]),
      metric("Network",network,[["Receive",rate(network.rx_bytes_per_second)],["Transmit",rate(network.tx_bytes_per_second)]]));
    p.append(el("h3","Host metrics"),metrics);
    if(Array.isArray(disk.volumes)&&disk.volumes.length){
      const labels={root:"Root filesystem",data:"Data",models:"Models"};
      const reasons={registration_unknown:"Registration unknown",mount_identity_unavailable:"Mount identity unavailable",capacity_unavailable:"Capacity unavailable"};
      const volumes=table(["Volume / mount","Observation","Available / total","Read / write","Reason"],disk.volumes.map(v=>[
        detail(labels[v.volume_id]||"Unknown volume",[v.mount_point??"Mount unknown",v.filesystem_type??"Filesystem unknown"]),
        detail((v.state||"unknown")+" · "+(v.freshness||"unknown"),[v.age_ms==null?"Age unknown":"Age "+Math.round(v.age_ms/1000)+"s"]),
        bytes(v.available_bytes)+" / "+bytes(v.total_bytes),
        rate(v.read_bytes_per_second)+" / "+rate(v.write_bytes_per_second),
        v.reason?(reasons[v.reason]||"Unknown"):"—"
      ]));volumes.classList.add("volume-table");
      p.append(el("h3","Registered volume roles"),el("p","Each role is shown separately; roles may share a filesystem.","muted"),volumes);
    }
    $("nodes").append(p);
  }
  $("notice").textContent="Last refreshed "+new Date().toLocaleTimeString()+" · Independent of the chat process";
}
let polling=false;async function refresh(){if(polling)return;polling=true;try{render(await json("/api/status/v1/system"));}catch{$("notice").textContent="Status transport unavailable. Previously displayed values may be stale; this does not prove hardware absence.";}finally{polling=false;}}
let targets=[],pending=null,operationTimer=null,dispatchImpact=null,lastOperation=null,recoveryTarget=null,recoveryKey=null;
function selection(){return targets[Number($("target").value)];}
function impact(){const t=selection();pending=null;$("interrupt").checked=false;$("action").replaceChildren();if(!t)return;for(const a of t.actions){const o=el("option",a);o.value=a;$("action").append(o);}$("impact").textContent="Affected services: "+t.affected_services.join(", ")+"\\nActivity: "+t.activity+"; active requests: "+(t.active_requests??"unknown")+"; queued: "+(t.queue_depth??"unknown")+"\\nNew dispatch paused: "+(t.dispatch_scope?.includes("harness")?"all app work":(t.dispatch_scope||[]).join(", ")||"no model lanes")+(t.dispatch_scope?.includes("harness")?"\\nHarness aggregate work: "+(dispatchImpact?.activity||"unknown")+"; active: "+(dispatchImpact?.active_requests??"unknown")+"; queued: "+(dispatchImpact?.queue_depth??"unknown")+" (readiness does not prove idle)":"")+"\\nBoot: "+t.expected_boot_id+"; target generation: "+t.expected_generation+"\\nReboot affects every listed service and requires later boot confirmation. No offline power-on is available.";}
async function loadTargets(){try{const response=await json("/api/admin/v1/targets");targets=response.targets;dispatchImpact=response.dispatch_impact;$("target").replaceChildren();targets.forEach((t,i)=>{const o=el("option",t.node_id+" / "+(t.service_id||t.gpu_uuid||"whole node"));o.value=i;$("target").append(o);});impact();}catch(e){$("action-result").textContent=e.message;}}
async function recoveryImpact(r){const response=await json("/api/admin/v1/targets");recoveryTarget=response.targets.find(t=>t.node_id===r.node_id&&(t.service_id||null)===(r.service_id||null)&&(t.gpu_uuid||null)===(r.gpu_uuid||null));$("recover-interrupt").checked=false;recoveryKey=Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,"0")).join("");$("recovery-impact").textContent=recoveryTarget?"Retained operation: "+r.operation_id+" ("+r.status+")\\nNew recovery action: "+r.recovery_action+"; target: "+r.node_id+" / "+(r.service_id||"whole node")+"\\nAffected services: "+recoveryTarget.affected_services.join(", ")+"; activity: "+recoveryTarget.activity+"\\nDispatch scope: "+recoveryTarget.dispatch_scope.join(", ")+"\\nBoot: "+recoveryTarget.expected_boot_id+"; generation: "+recoveryTarget.expected_generation:"Recovery target unavailable; refresh observations before confirming.";}
async function pollOperation(url){try{const r=await json(url);const changed=lastOperation?.operation_id!==r.operation_id;lastOperation=r;$("action-result").textContent="Operation "+r.operation_id+": "+r.status+(r.reason?" ("+r.reason+")":"")+(r.dispatch_frozen?" · Affected dispatch remains paused.":"");$("recovery").hidden=!r.dispatch_frozen||!r.recovery_action||["accepted","running"].includes(r.status);if(!$("recovery").hidden&&(changed||!recoveryTarget))await recoveryImpact(r);$("recover").textContent=r.recovery_action==="node.reboot"?"Confirm recovery whole-node reboot":"Confirm recovery restart";if(["accepted","running"].includes(r.status)||r.dispatch_frozen)operationTimer=setTimeout(()=>pollOperation(url),2000);}catch{$("action-result").textContent="Operation status unknown; keep the operation ID and refresh later.";}}

if(admin){$("recover").addEventListener("click",async()=>{if(!lastOperation||!recoveryTarget||!$("recover-interrupt").checked){$("action-result").textContent="Explicit interruption confirmation is required for recovery.";return;}$("recover").disabled=true;try{const auth=await json("/api/admin/session");const r=await json(lastOperation.poll_url+"/reconcile",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":auth.csrf},body:JSON.stringify({allow_interrupt:true,expected_boot_id:recoveryTarget.expected_boot_id,expected_generation:recoveryTarget.expected_generation,idempotency_key:recoveryKey})});$("recover-interrupt").checked=false;clearTimeout(operationTimer);await pollOperation(r.poll_url);}catch(e){$("action-result").textContent=e.message;}finally{$("recover").disabled=false;}});$("target").addEventListener("change",impact);$("action").addEventListener("change",()=>{pending=null;$("interrupt").checked=false;});$("refresh-targets").addEventListener("click",loadTargets);$("action-form").addEventListener("submit",async e=>{e.preventDefault();const t=selection();if(!t)return;const action=$("action").value;if((t.activity!=="idle"||action!=="service.start")&&!$("interrupt").checked){$("action-result").textContent="Explicit interruption confirmation is required for this impact.";return;}const candidate={schema_version:1,node_id:t.node_id,action,...(t.service_id?{service_id:t.service_id}:{}),...(t.gpu_uuid?{gpu_uuid:t.gpu_uuid}:{}),expected_boot_id:t.expected_boot_id,expected_generation:t.expected_generation,allow_interrupt:$("interrupt").checked};if(!pending||JSON.stringify(pending.candidate)!==JSON.stringify(candidate))pending={candidate,key:Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,"0")).join("")};$("submit").disabled=true;try{const auth=await json("/api/admin/session");const r=await json("/api/admin/v1/actions",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":auth.csrf},body:JSON.stringify({...candidate,idempotency_key:pending.key})});clearTimeout(operationTimer);pending=null;await pollOperation(r.poll_url);}catch(e){$("action-result").textContent=e.message+" · Action key: "+pending.key+". Unchanged retry reuses this key.";}finally{$("submit").disabled=false;}});void loadTargets();}
void refresh();setInterval(refresh,5000);
`;
